bcgov/sso-terraform

terraform-v2/keycloak-dev/standard-clients/resume-bundler-back-end-4383.tf, terraform-v2/keycloak-prod/standard-clients/resume-bundler-back-end-4383.tf, terraform-v2/keycloak-test/standard-clients/resume-bundler-back-end-4383.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for resume-bundler-back-end-4383

terraform-v2/keycloak-dev/standard-clients/acrfd-api-4384.tf, terraform-v2/keycloak-prod/standard-clients/acrfd-api-4384.tf, terraform-v2/keycloak-test/standard-clients/acrfd-api-4384.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for acrfd-api-4384

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-16-b-ce-id-both-4386.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-11-16-b-ce-id-both-4386.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-11-16-b-ce-id-both-4386

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-16-b-ce-id-business-and-basic-4387.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-11-16-b-ce-id-business-and-basic-4387.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-11-16-b-ce-id-business-and-basic-4387

terraform-v2/keycloak-dev/standard-clients/coco-chefs-4302.tf, terraform-v2/keycloak-prod/standard-clients/coco-chefs-4302.tf, terraform-v2/keycloak-test/standard-clients/coco-chefs-4302.tf
```<ul>✔️Valid Redirect Urls<li>https://chefs-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://chefs-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://submit.digital.gov.bc.ca/app</li>,<li>https://submit.digital.gov.bc.ca/app/form/create</li>,<li>https://submit.digital.gov.bc.ca/app/user/forms</li></ul>```
</details>
=> request: add client files for coco-chefs-4302

terraform-v2/keycloak-dev/standard-clients/isd-forms-uptime-4392.tf, terraform-v2/keycloak-prod/standard-clients/isd-forms-uptime-4392.tf, terraform-v2/keycloak-test/standard-clients/isd-forms-uptime-4392.tf
```<ul>✔️Valid Redirect Urls<li>https://obstatus-dev.apps-isd.sd.gov.bc.ca/oauth2/callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://obstatus-test.apps-isd.sd.gov.bc.ca/oauth2/callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://obstatus.apps-isd.sd.gov.bc.ca/oauth2/callback</li></ul>```
</details>
=> request: add client files for isd-forms-uptime-4392

terraform-v2/keycloak-dev/standard-clients/wildfire-4394.tf, terraform-v2/keycloak-prod/standard-clients/wildfire-4394.tf, terraform-v2/keycloak-test/standard-clients/wildfire-4394.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/wildfire/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/wildfire/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/wildfire/*</li></ul>```
</details>
=> request: add client files for wildfire-4394

terraform-v2/keycloak-dev/standard-clients/isd-sonar-qube-4393.tf, terraform-v2/keycloak-prod/standard-clients/isd-sonar-qube-4393.tf, terraform-v2/keycloak-test/standard-clients/isd-sonar-qube-4393.tf
```<ul>✔️Valid Redirect Urls<li>https://sonarqube-dev.apps-isd.sd.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://sonarqube-test.apps-isd.sd.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://sonarqube.apps-isd.sd.gov.bc.ca/oauth2/callback/oidc</li></ul>```
</details>
=> request: add client files for isd-sonar-qube-4393

terraform-v2/keycloak-dev/standard-clients/property-services-project-local-devin-4395.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for property-services-project-local-devin-4395

terraform-v2/keycloak-dev/standard-clients/bc-athcomm-4397.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/callback</li></ul>```
</details>
=> request: add client files for bc-athcomm-4397

terraform-v2/keycloak-dev/standard-clients/tidd-gold-4398.tf, terraform-v2/keycloak-prod/standard-clients/tidd-gold-4398.tf, terraform-v2/keycloak-test/standard-clients/tidd-gold-4398.tf
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc--meldev.my.salesforce.com/services/authcallback/BCGovSSOIdir</li>,<li>https://tradeandinvestbclightning--dev.my.salesforce.com/services/authcallback/BCGovSSOIdir</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc--test.my.salesforce.com/services/authcallback/BCGovSSOIdir</li>,<li>https://tradeandinvestbclightning--test.my.salesforce.com/services/authcallback/BCGovSSOIdir</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc.my.salesforce.com/services/authcallback/BCGovSSOIdir</li>,<li>https://tradeandinvestbclightning.my.salesforce …
```
=> request: add client files for tidd-gold-4398

terraform-v2/keycloak-dev/standard-clients/alcs-portal-4399.tf, terraform-v2/keycloak-prod/standard-clients/alcs-portal-4399.tf, terraform-v2/keycloak-test/standard-clients/alcs-portal-4399.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://alcs.nr.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for alcs-portal-4399

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1291-4401.tf
=> request: add client files for service-account-team-1291-4401

terraform-v2/keycloak-dev/standard-clients/registries-4402.tf, terraform-v2/keycloak-prod/standard-clients/registries-4402.tf, terraform-v2/keycloak-test/standard-clients/registries-4402.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcregistry/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcregistry/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/bcregistry/broker/bceid/endpoint</li>,<li>https://loginproxy.gov.bc.ca/auth/realms/bcregistry/broker/github/endpoint</li>,<li>https://loginproxy.gov.bc.ca/auth/realms/bcregistry/broker/idir/endpoint</li></ul>```
</details>
=> request: add client files for registries-4402

terraform-v2/keycloak-dev/standard-clients/wally-4389.tf, terraform-v2/keycloak-prod/standard-clients/wally-4389.tf, terraform-v2/keycloak-test/standard-clients/wally-4389.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://wally-grafana.pathfinder.gov.bc.ca/*</li>,<li>https://wally.apps.silver.devops.gov.bc.ca/*</li>,<li>https://wally.nrs.gov.bc.ca/*</li>,<li>https://wally.pathfinder.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for wally-4389

terraform-v2/keycloak-dev/standard-clients/tians-testing-custom-realm-setup-4404.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/zorin-dev-custom-realm/*</li></ul>```
</details>
=> request: add client files for tians-testing-custom-realm-setup-4404

terraform-v2/keycloak-dev/standard-clients/ti-gr-s-gold-4405.tf, terraform-v2/keycloak-prod/standard-clients/ti-gr-s-gold-4405.tf, terraform-v2/keycloak-test/standard-clients/ti-gr-s-gold-4405.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/callback</li></ul>```
</details>
=> request: add client files for ti-gr-s-gold-4405

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1092-4406.tf
=> request: add client files for service-account-team-1092-4406

terraform-v2/keycloak-dev/standard-clients/pims-frontend-4391.tf, terraform-v2/keycloak-prod/standard-clients/pims-frontend-4391.tf, terraform-v2/keycloak-test/standard-clients/pims-frontend-4391.tf
```<ul>✔️Valid Redirect Urls<li>https://pims-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://pims-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://pims.gov.bc.ca</li>,<li>https://pims.gov.bc.ca/login</li></ul>```
</details>
=> request: add client files for pims-frontend-4391

terraform-v2/keycloak-dev/standard-clients/nr-fsa-web-app-dev-pr-4408.tf
```<ul>✔️Valid Redirect Urls<li>https://nrfesampleapp-24-app.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for nr-fsa-web-app-dev-pr-4408

terraform-v2/keycloak-dev/standard-clients/react-sample-app-test-4409.tf, terraform-v2/keycloak-prod/standard-clients/react-sample-app-test-4409.tf, terraform-v2/keycloak-test/standard-clients/react-sample-app-test-4409.tf
```<ul>✔️Valid Redirect Urls<li>https://nrfesampleapp-test-app.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://nrfesampleapp-test-app.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://nrfesampleapp-test-app.apps.silver.devops.gov.bc.ca/login-success</li></ul>```
</details>
=> request: add client files for react-sample-app-test-4409

terraform-v2/keycloak-dev/standard-clients/community-investment-opportunities-tool-4410.tf, terraform-v2/keycloak-prod/standard-clients/community-investment-opportunities-tool-4410.tf, terraform-v2/keycloak-test/standard-clients/community-investment-opportunities-tool-4410.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.communityinformationtool.gov.bc.ca/investmentopportunities/dashboard</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://communityinformationtool.gov.bc.ca/investmentopportunities/dashboard</li></ul>```
</details>
=> request: add client files for community-investment-opportunities-tool-4410

terraform-v2/keycloak-dev/standard-clients/community-information-tool-4411.tf, terraform-v2/keycloak-prod/standard-clients/community-information-tool-4411.tf, terraform-v2/keycloak-test/standard-clients/community-information-tool-4411.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.communityinformationtool.gov.bc.ca/cit-dashboard/home</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://communityinformationtool.gov.bc.ca/cit-dashboard/home</li></ul>```
</details>
=> request: add client files for community-information-tool-4411

terraform-v2/keycloak-dev/standard-clients/pbgp-4412.tf, terraform-v2/keycloak-prod/standard-clients/pbgp-4412.tf, terraform-v2/keycloak-test/standard-clients/pbgp-4412.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for pbgp-4412

terraform-v2/keycloak-dev/standard-clients/mines-digital-services-mds-public-client-4414.tf, terraform-v2/keycloak-prod/standard-clients/mines-digital-services-mds-public-client-4414.tf, terraform-v2/keycloak-test/standard-clients/mines-digital-services-mds-public-client-4414.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for mines-digital-services-mds-public-client-4414

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-23-b-ce-id-first-name-4416.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-11-23-b-ce-id-first-name-4416.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for tians-testing-11-23-b-ce-id-first-name-4416

terraform-v2/keycloak-dev/standard-clients/test-confidential-client-nk-4417.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
</details>
=> request: add client files for test-confidential-client-nk-4417

terraform-v2/keycloak-dev/standard-clients/test-4418.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:40080/*</li></ul>```
</details>
=> request: add client files for test-4418

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-24-confidential-example-app-4419.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-11-24-confidential-example-app-4419.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-11-24-confidential-example-app-4419.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for tians-testing-11-24-confidential-example-app-4419

terraform-v2/keycloak-dev/standard-clients/tco-4420.tf, terraform-v2/keycloak-prod/standard-clients/tco-4420.tf, terraform-v2/keycloak-test/standard-clients/tco-4420.tf
```<ul>✔️Valid Redirect Urls<li>https://staff-web-0198bb-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://oidc-0198bb-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://oidc-0198bb-prod.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for tco-4420

terraform-v2/keycloak-dev/standard-clients/work-bc-wage-subsidy-front-end-4421.tf, terraform-v2/keycloak-test/standard-clients/work-bc-wage-subsidy-front-end-4421.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
</details>
=> request: add client files for work-bc-wage-subsidy-front-end-4421

terraform-v2/keycloak-dev/standard-clients/seed-planning-dev-pr-only-4423.tf
```<ul>✔️Valid Redirect Urls<li>https://nrfesampleapp-28-app.apps.silver.devops.gov.bc.ca/home</li>,<li>https://nrfesampleapp-28-app.apps.silver.devops.gov.bc.ca/silent-check-sso.html</li></ul>```
</details>
=> request: add client files for seed-planning-dev-pr-only-4423

terraform-v2/keycloak-dev/standard-clients/aest-sims-4424.tf, terraform-v2/keycloak-test/standard-clients/aest-sims-4424.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-aest-sims.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test-aest-sims.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for aest-sims-4424

terraform-v2/keycloak-dev/standard-clients/schoolbus-4425.tf, terraform-v2/keycloak-prod/standard-clients/schoolbus-4425.tf, terraform-v2/keycloak-test/standard-clients/schoolbus-4425.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li>,<li>http://localhost:3000/*</li>,<li>https://dev-schoolbus.th.gov.bc.ca/</li>,<li>https://dev-schoolbus.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-schoolbus.th.gov.bc.ca/</li>,<li>https://tst-schoolbus.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://schoolbus.th.gov.bc.ca/</li>,<li>https://schoolbus.th.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for schoolbus-4425

terraform-v2/keycloak-dev/standard-clients/nov-28-git-hub-test-4426.tf, terraform-v2/keycloak-prod/standard-clients/nov-28-git-hub-test-4426.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for nov-28-git-hub-test-4426

terraform-v2/keycloak-dev/standard-clients/moti-custom-bceid-4427.tf, terraform-v2/keycloak-prod/standard-clients/moti-custom-bceid-4427.tf, terraform-v2/keycloak-test/standard-clients/moti-custom-bceid-4427.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://dev.loginproxy.gov.bc.ca/auth/realms/moti-custom/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://test.loginproxy.gov.bc.ca/auth/realms/moti-custom/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://loginproxy.gov.bc.ca/auth/realms/moti-custom/*</li></ul>```
</details>
=> request: add client files for moti-custom-bceid-4427

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1298-4428.tf
=> request: add client files for service-account-team-1298-4428

terraform-v2/keycloak-dev/standard-clients/isd-cssaps-demo-4429.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>https://pbin.api.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for isd-cssaps-demo-4429

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-30-email-flow-validation-4432.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-11-30-email-flow-validation-4432.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-11-30-email-flow-validation-4432

terraform-v2/keycloak-dev/standard-clients/eao-epic-4433.tf, terraform-v2/keycloak-prod/standard-clients/eao-epic-4433.tf, terraform-v2/keycloak-test/standard-clients/eao-epic-4433.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/admin/eao-epic/console/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/admin/eao-epic/console/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/admin/eao-epic/console/</li></ul>```
</details>
=> request: add client files for eao-epic-4433

terraform-v2/keycloak-dev/standard-clients/hets-standard-4434.tf, terraform-v2/keycloak-prod/standard-clients/hets-standard-4434.tf, terraform-v2/keycloak-test/standard-clients/hets-standard-4434.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li>,<li>http://localhost:3000/*</li>,<li>https://dev-hets.th.gov.bc.ca/</li>,<li>https://dev-hets.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li>,<li>http://localhost:3000/*</li>,<li>https://tst-hets.th.gov.bc.ca/</li>,<li>https://tst-hets.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li>,<li>http://localhost:3000/*</li>,<li>https://hets.th.gov.bc.ca/</li>,<li>https://hets.th.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for hets-standard-4434

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-30-post-release-4436.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-11-30-post-release-4436.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for tians-testing-11-30-post-release-4436

terraform-v2/keycloak-dev/standard-clients/traffic-courts-online-4437.tf, terraform-v2/keycloak-prod/standard-clients/traffic-courts-online-4437.tf, terraform-v2/keycloak-test/standard-clients/traffic-courts-online-4437.tf
```<ul>✔️Valid Redirect Urls<li>https://staff-web-0198bb-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://oidc-0198bb-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://oidc-0198bb-prod.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for traffic-courts-online-4437

terraform-v2/keycloak-dev/standard-clients/wordpress-4439.tf
```<ul>✔️Valid Redirect Urls<li>https://des-test.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for wordpress-4439

terraform-v2/keycloak-dev/standard-clients/ciip-4440.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3004/*</li>,<li>https://dev.ciip.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for ciip-4440

terraform-v2/keycloak-dev/standard-clients/traffic-courts-online-administration-4441.tf, terraform-v2/keycloak-prod/standard-clients/traffic-courts-online-administration-4441.tf, terraform-v2/keycloak-test/standard-clients/traffic-courts-online-administration-4441.tf
```<ul>✔️Valid Redirect Urls<li>https://oidc-0198bb-dev.apps.silver.devops.gov.bc.ca/realms/master/broker/idir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://oidc-0198bb-test.apps.silver.devops.gov.bc.ca/realms/master/broker/idir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://oidc-0198bb-prod.apps.silver.devops.gov.bc.ca/realms/master/broker/idir/endpoint</li></ul>```
</details>
=> request: add client files for traffic-courts-online-administration-4441

terraform-v2/keycloak-dev/standard-clients/bc-box-4442.tf
```<ul>✔️Valid Redirect Urls<li>https://bcbox-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for bc-box-4442

terraform-v2/keycloak-dev/standard-clients/mals-4443.tf, terraform-v2/keycloak-prod/standard-clients/mals-4443.tf, terraform-v2/keycloak-test/standard-clients/mals-4443.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://mals.nrs.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for mals-4443

terraform-v2/keycloak-dev/standard-clients/gdx-suite-crm-4447.tf
```<ul>✔️Valid Redirect Urls<li>https://gdx-suitecrm-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for gdx-suite-crm-4447

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-661-4450.tf
=> request: add client files for service-account-team-661-4450

terraform-v2/keycloak-dev/standard-clients/gdx-suite-crm-4453.tf
```<ul>✔️Valid Redirect Urls<li>https://gdx-suitecrm-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for gdx-suite-crm-4453

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1292-4454.tf
=> request: add client files for service-account-team-1292-4454

terraform-v2/keycloak-dev/standard-clients/tians-testing-12-9-notification-4456.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-12-9-notification-4456

terraform-v2/keycloak-dev/standard-clients/im-boarding-4457.tf, terraform-v2/keycloak-test/standard-clients/im-boarding-4457.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for im-boarding-4457

terraform-v2/keycloak-dev/standard-clients/elmsd-nextjs-headless-4458.tf, terraform-v2/keycloak-test/standard-clients/elmsd-nextjs-headless-4458.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for elmsd-nextjs-headless-4458

terraform-v2/keycloak-dev/standard-clients/pims-backend-4403.tf, terraform-v2/keycloak-prod/standard-clients/pims-backend-4403.tf, terraform-v2/keycloak-test/standard-clients/pims-backend-4403.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for pims-backend-4403

terraform-v2/keycloak-dev/standard-clients/wordpress-prod-4459.tf, terraform-v2/keycloak-prod/standard-clients/wordpress-prod-4459.tf
```<ul>✔️Valid Redirect Urls<li>https://des-test.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://wordpress-prod.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for wordpress-prod-4459

terraform-v2/keycloak-dev/standard-clients/applogs-4460.tf
```<ul>✔️Valid Redirect Urls<li>https://*</li></ul>```
</details>
=> request: add client files for applogs-4460

terraform-v2/keycloak-dev/standard-clients/sims-4461.tf, terraform-v2/keycloak-prod/standard-clients/sims-4461.tf, terraform-v2/keycloak-test/standard-clients/sims-4461.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://sims.nrs.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for sims-4461

terraform/keycloak-dev/realms/onestopauth/client-office-of-the-superintendent-of-prof-governance-3071.tf, terraform/keycloak-prod/realms/onestopauth/client-office-of-the-superintendent-of-prof-governance-3071.tf, terraform/keycloak-test/realms/onestopauth/client-office-of-the-superintendent-of-prof-governance-3071.tf
```<ul>✔️Valid Redirect Urls<li>https://keycloak-e63731-dev.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://keycloak-e63731-test.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://keycloak-e63731-prod.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
</details>
=> request: delete client files for office-of-the-superintendent-of-prof-governance-3071

terraform/keycloak-dev/realms/onestopauth/client-serve-legal-documents-3070.tf, terraform/keycloak-prod/realms/onestopauth/client-serve-legal-documents-3070.tf, terraform/keycloak-test/realms/onestopauth/client-serve-legal-documents-3070.tf
```<ul>✔️Valid Redirect Urls<li>https://keycloak-a60371-dev.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://keycloak-a60371-test.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://keycloak-a60371-prod.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
</details>
=> request: delete client files for serve-legal-documents-3070

terraform-v2/keycloak-dev/standard-clients/digital-gov-bc-ca-prod-idir-4463.tf, terraform-v2/keycloak-prod/standard-clients/digital-gov-bc-ca-prod-idir-4463.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://des-test.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://wordpress-prod.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for digital-gov-bc-ca-prod-idir-4463

terraform-v2/keycloak-dev/standard-clients/sims-svc-4464.tf, terraform-v2/keycloak-prod/standard-clients/sims-svc-4464.tf, terraform-v2/keycloak-test/standard-clients/sims-svc-4464.tf
=> request: add client files for sims-svc-4464

terraform-v2/keycloak-dev/standard-clients/biohub-svc-4466.tf, terraform-v2/keycloak-prod/standard-clients/biohub-svc-4466.tf, terraform-v2/keycloak-test/standard-clients/biohub-svc-4466.tf
=> request: add client files for biohub-svc-4466

terraform-v2/keycloak-dev/standard-clients/isd-forms-runnner-4467.tf
=> request: add client files for isd-forms-runnner-4467

terraform-v2/keycloak-dev/standard-clients/embc-web-eoc-4468.tf, terraform-v2/keycloak-prod/standard-clients/embc-web-eoc-4468.tf, terraform-v2/keycloak-test/standard-clients/embc-web-eoc-4468.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bc.lab.webeocasp.com/bc/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://bc.demo.webeocasp.com/bc/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://bc.webeocasp.com/bc/*</li>
</ul>
</details>
=> request: add client files for embc-web-eoc-4468

terraform-v2/keycloak-dev/standard-clients/sample-app-4469.tf, terraform-v2/keycloak-test/standard-clients/sample-app-4469.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/dashboard</li><li>http://localhost:3000/home</li><li>http://localhost:3000/logout</li><li>http://localhost:3000/silent-check-sso</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://nrfesampleapp-test-app.apps.silver.devops.gov.bc.ca/dashboard</li><li>https://nrfesampleapp-test-app.apps.silver.devops.gov.bc.ca/home</li><li>https://nrfesampleapp-test-app.apps.silver.devops.gov.bc.ca/logout</li><li>https://nrfesampleapp-test-app.apps.silver.devops.gov.bc.ca/silent-check-sso</li>
</ul>
</details>
=> request: add client files for sample-app-4469

terraform-v2/keycloak-dev/standard-clients/property-services-project-geoserver-4472.tf, terraform-v2/keycloak-prod/standard-clients/property-services-project-geoserver-4472.tf, terraform-v2/keycloak-test/standard-clients/property-services-project-geoserver-4472.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://vip-dev-geo.th.gov.bc.ca:8081/ogs-geoV06/psp_dev/ows*</li><li>https://dev.loginproxy.gov.bc.ca/auth/admin/standard/keycloak-oidc/endpoint*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://vip-tst-geo.th.gov.bc.ca:8082/ogs-geoV06/psp_uat/ows*</li><li>https://test.loginproxy.gov.bc.ca/auth/admin/standard/keycloak-oidc/endpoint*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://vip-prd-geo.th.gov.bc.ca:8083/ogs-geoV06/psp_prd/ows*</li><li>https://loginproxy.gov.bc.ca/auth/admin/standard/keycloak-oidc/endpoint*</li>
</ul>
</details>
=> request: add client files for property-services-project-geoserver-4472

terraform-v2/keycloak-dev/standard-clients/on-route-bc-4452.tf, terraform-v2/keycloak-prod/standard-clients/on-route-bc-4452.tf, terraform-v2/keycloak-test/standard-clients/on-route-bc-4452.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.onroutebc.gov.bc.ca/*</li><li>https://localhost/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://tst.onroutebc.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://onroutebc.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for on-route-bc-4452

terraform-v2/keycloak-dev/standard-clients/sheriff-scheduling-4491.tf, terraform-v2/keycloak-prod/standard-clients/sheriff-scheduling-4491.tf, terraform-v2/keycloak-test/standard-clients/sheriff-scheduling-4491.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8080/*</li><li>https://dev.jag.gov.bc.ca/sheriff-scheduling/*</li><li>https://localhost:1338/*</li><li>https://localhost:44370/*</li><li>https://localhost:5000/*</li><li>https://localhost:5001/*</li><li>https://localhost:8080/*</li><li>https://localhost:8081/*</li><li>https://sheriff-scheduling-dev.apps.silver.devops.gov.bc.ca/*</li><li>https://sheriff-scheduling-dev.pathfinder.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://sheriff-scheduling-test.apps.silver.devops.gov.bc.ca/*</li><li>https://sheriff-scheduling-test.pathfinder.gov.bc.ca/*</li><li>https://test.jag.gov.bc.ca/sheriff-scheduling/*</li>
</ul>
</details> …
=> request: add client files for sheriff-scheduling-4491

terraform-v2/keycloak-dev/standard-clients/sso-grafana-4492.tf, terraform-v2/keycloak-prod/standard-clients/sso-grafana-4492.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://sso-dashboard.apps.gold.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for sso-grafana-4492

terraform-v2/keycloak-dev/standard-clients/freedom-of-information-modernization-4493.tf, terraform-v2/keycloak-prod/standard-clients/freedom-of-information-modernization-4493.tf, terraform-v2/keycloak-test/standard-clients/freedom-of-information-modernization-4493.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000</li>
</ul>
</details>
=> request: add client files for freedom-of-information-modernization-4493

terraform-v2/keycloak-dev/standard-clients/sabc-applications-ici-4522.tf, terraform-v2/keycloak-prod/standard-clients/sabc-applications-ici-4522.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://10.0.0.51:8019/app-login</li><li>https://tbtb-ici-06cb9b-dev.apps.silver.devops.gov.bc.ca/app-login</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://10.0.0.51:8019/app-login</li><li>https://tbtb-ici-06cb9b-dev.apps.silver.devops.gov.bc.ca/app-login</li>
</ul>
</details>
=> request: add client files for sabc-applications-ici-4522

terraform-v2/keycloak-dev/standard-clients/chefs-data-ingestion-ministry-of-health-4523.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://medis-chefs-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for chefs-data-ingestion-ministry-of-health-4523

terraform-v2/keycloak-dev/standard-clients/tians-testing-1-3-api-pagination-4526.tf
=> request: add client files for tians-testing-1-3-api-pagination-4526

terraform-v2/keycloak-dev/standard-clients/https-apps-isd-sd-gov-bc-ca-jenkins-4527.tf, terraform-v2/keycloak-prod/standard-clients/https-apps-isd-sd-gov-bc-ca-jenkins-4527.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://apps-isd.sd.gov.bc.ca/jenkins/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://apps-isd.sd.gov.bc.ca/jenkins/</li><li>https://apps-isd.sd.gov.bc.ca/jenkins/*</li>
</ul>
</details>
=> request: add client files for https-apps-isd-sd-gov-bc-ca-jenkins-4527

terraform-v2/keycloak-dev/standard-clients/court-interpreter-scheduling-4528.tf, terraform-v2/keycloak-prod/standard-clients/court-interpreter-scheduling-4528.tf, terraform-v2/keycloak-test/standard-clients/court-interpreter-scheduling-4528.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://127.0.0.1:8080/*</li><li>http://localhost:3000/*</li><li>http://localhost:8080/*</li><li>http://localhost:8081/*</li><li>https://court-interpreter-scheduling-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8080/*</li><li>https://court-interpreter-scheduling-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://court-interpreter-scheduling.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for court-interpreter-scheduling-4528

terraform-v2/keycloak-dev/standard-clients/abc-4530.tf, terraform-v2/keycloak-test/standard-clients/abc-4530.tf
=> request: add client files for abc-4530

terraform-v2/keycloak-dev/standard-clients/azure-idir-test-4529.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://lrb--qa.sandbox.my.salesforce.com/services/authcallback/PathfinderIdir</li>
</ul>
</details>
=> request: add client files for azure-idir-test-4529

terraform-v2/keycloak-dev/standard-clients/business-bceid-registries-idp-4531.tf, terraform-v2/keycloak-test/standard-clients/business-bceid-registries-idp-4531.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcregistry/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/bcregistry/*</li>
</ul>
</details>
=> request: add client files for business-bceid-registries-idp-4531

terraform-v2/keycloak-dev/standard-clients/min-io-551-bf-1-dev-4535.tf
=> request: add client files for min-io-551-bf-1-dev-4535

terraform-v2/keycloak-dev/standard-clients/min-io-console-551-bf-1-dev-4536.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://minio-console-551bf1-dev.apps.silver.devops.gov.bc.ca/oauth_callback</li>
</ul>
</details>
=> request: add client files for min-io-console-551-bf-1-dev-4536

terraform-v2/keycloak-dev/standard-clients/min-io-console-551-bf-1-dev-4537.tf
=> request: add client files for min-io-console-551-bf-1-dev-4537

terraform-v2/keycloak-dev/standard-clients/min-io-console-551-bf-1-dev-2-4538.tf
=> request: add client files for min-io-console-551-bf-1-dev-2-4538

terraform-v2/keycloak-dev/standard-clients/e-tk-sso-4533.tf, terraform-v2/keycloak-prod/standard-clients/e-tk-sso-4533.tf, terraform-v2/keycloak-test/standard-clients/e-tk-sso-4533.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://jh-etk-scweb*</li><li>http://jh-etk-scweb-dev.apps.silver.devops.gov.bc.ca/*</li><li>http://jh-etk-scweb-dev.pathfinder.bcgov/*</li><li>http://jh-etk-scweb-pr*</li><li>http://localhost:8080/*</li><li>http://localhost:8082/*</li><li>https://dev.jag.gov.bc.ca/jh-etk-scweb*</li><li>https://jh-etk-scweb*</li><li>https://jh-etk-scweb-dev*</li><li>https://jh-etk-scweb-dev.apps.silver.devops.gov.bc.ca/*</li><li>https://jh-etk-scweb-dev.pathfinder.bcgov/*</li><li>https://www.jh-etk-scweb-pr*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://dev.justice.gov.bc.ca/jh-etk-scweb*</li><li>http://jh-etk-scweb-pr/*</li><li>http://jh-etk-scweb-stage*</li><li>ht …
=> request: add client files for e-tk-sso-4533

terraform-v2/keycloak-dev/standard-clients/bc-box-local-4540.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://127.0.0.1:5173/*</li><li>http://127.0.0.1:8080/*</li><li>http://127.0.0.1:8081/*</li><li>http://localhost/*</li><li>http://localhost:5173/*</li><li>http://localhost:8080/*</li><li>http://localhost:8081/*</li>
</ul>
</details>
=> request: add client files for bc-box-local-4540

terraform-v2/keycloak-dev/standard-clients/bc-box-local-4541.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://127.0.0.1/*</li><li>http://127.0.0.1:5173/*</li><li>http://127.0.0.1:8080/*</li><li>http://127.0.0.1:8081/*</li><li>http://localhost/*</li><li>http://localhost:5173/*</li><li>http://localhost:8080/*</li><li>http://localhost:8081/*</li>
</ul>
</details>
=> request: add client files for bc-box-local-4541

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-1-service-account-4542.tf
=> request: add client files for tians-testing-11-1-service-account-4542

terraform-v2/keycloak-dev/standard-clients/zeva-on-gold-4543.tf, terraform-v2/keycloak-prod/standard-clients/zeva-on-gold-4543.tf, terraform-v2/keycloak-test/standard-clients/zeva-on-gold-4543.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>https://zeva-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://logontest7.gov.bc.ca/*</li><li>https://zeva-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://logon7.gov.bc.ca/*</li><li>https://zeroemissionvehicles.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for zeva-on-gold-4543

terraform-v2/keycloak-dev/standard-clients/accessibility-feedback-form-test-4525.tf
=> request: add client files for accessibility-feedback-form-test-4525

terraform-v2/keycloak-dev/standard-clients/service-account-test-4451.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://www.serviceaccount.com</li>
</ul>
</details>
=> request: add client files for service-account-test-4451

terraform-v2/keycloak-dev/standard-clients/bc-box-local-4545.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://127.0.0.1/*</li><li>http://127.0.0.1:5173/*</li><li>http://127.0.0.1:8080/*</li><li>http://127.0.0.1:8081/*</li><li>http://localhost/*</li><li>http://localhost:5173/*</li><li>http://localhost:8080/*</li><li>http://localhost:8081/*</li>
</ul>
</details>
=> request: add client files for bc-box-local-4545

terraform-v2/keycloak-dev/standard-clients/https-test-octane-apps-isd-sd-gov-bc-ca-4546.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://test-octane.apps-isd.sd.gov.bc.ca/osp/a/au/auth/saml2/spassertion_consumer</li>
</ul>
</details>
=> request: add client files for https-test-octane-apps-isd-sd-gov-bc-ca-4546

terraform-v2/keycloak-dev/standard-clients/psa-digital-journeys-local-development-4547.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000</li>
</ul>
</details>
=> request: add client files for psa-digital-journeys-local-development-4547

terraform-v2/keycloak-dev/standard-clients/tians-testing-1-16-saml-4549.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-1-16-saml-4549.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-1-16-saml-4549

terraform-v2/keycloak-dev/standard-clients/my-range-3769.tf, terraform-v2/keycloak-prod/standard-clients/my-range-3769.tf, terraform-v2/keycloak-test/standard-clients/my-range-3769.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://myrangebc.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for my-range-3769

terraform-v2/keycloak-dev/standard-clients/public-cloud-4551.tf, terraform-v2/keycloak-prod/standard-clients/public-cloud-4551.tf, terraform-v2/keycloak-test/standard-clients/public-cloud-4551.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/public-cloud/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/public-cloud/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/public-cloud/*</li>
</ul>
</details>
=> request: add client files for public-cloud-4551

terraform-v2/keycloak-dev/standard-clients/saml-test-4552.tf, terraform-v2/keycloak-test/standard-clients/saml-test-4552.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for saml-test-4552

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1301-4553.tf
=> request: add client files for service-account-team-1301-4553

terraform-v2/keycloak-dev/standard-clients/im-boarding-4554.tf
=> request: add client files for im-boarding-4554

terraform-v2/keycloak-dev/standard-clients/bc-box-4555.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bcbox-dev-master.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for bc-box-4555

terraform-v2/keycloak-dev/standard-clients/tians-testing-1-19-23-release-4556.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-1-19-23-release-4556.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-1-19-23-release-4556.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://exampleProd</li>
</ul>
</details>
=> request: add client files for tians-testing-1-19-23-release-4556

terraform-v2/keycloak-dev/standard-clients/kuro-testing-4390.tf, terraform-v2/keycloak-test/standard-clients/kuro-testing-4390.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://test.com</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://test.com</li>
</ul>
</details>
=> request: add client files for kuro-testing-4390

terraform-v2/keycloak-dev/standard-clients/work-bc-mobile-admin-dev-4559.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://workbc-mobile-admin-client-551bf1-dev.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for work-bc-mobile-admin-dev-4559

terraform-v2/keycloak-dev/standard-clients/work-bc-mobile-admin-front-end-4560.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://workbc-mobile-admin-client-551bf1-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for work-bc-mobile-admin-front-end-4560

terraform-v2/keycloak-dev/standard-clients/work-bc-mobile-admin-back-end-4561.tf
=> request: add client files for work-bc-mobile-admin-back-end-4561

terraform-v2/keycloak-dev/standard-clients/invasives-bc-4565.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:8100/*</li><li>https://dev-invasivesbci.apps.silver.devops.gov.bc.ca/home/landing</li><li>https://invasivesbc.gov.bc.ca/home/landing</li><li>https://test-invasivesbci.apps.silver.devops.gov.bc.ca/home/landing</li>
</ul>
</details>
=> request: add client files for invasives-bc-4565

terraform-v2/keycloak-dev/standard-clients/apm-open-search-oidc-4567.tf, terraform-v2/keycloak-prod/standard-clients/apm-open-search-oidc-4567.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://apm.io.nrs.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://apm.io.nrs.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for apm-open-search-oidc-4567

terraform-v2/keycloak-dev/standard-clients/labr-eao-rapid-lms-4569.tf, terraform-v2/keycloak-prod/standard-clients/labr-eao-rapid-lms-4569.tf, terraform-v2/keycloak-test/standard-clients/labr-eao-rapid-lms-4569.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost</li>
</ul>
</details>
=> request: add client files for labr-eao-rapid-lms-4569

terraform-v2/keycloak-dev/standard-clients/cmf-poc-4566.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000</li>
</ul>
</details>
=> request: add client files for cmf-poc-4566

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-463-4570.tf
=> request: add client files for service-account-team-463-4570

terraform-v2/keycloak-dev/standard-clients/tians-testing-2-3-keycloak-upgrade-test-4571.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-2-3-keycloak-upgrade-test-4571.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-2-3-keycloak-upgrade-test-4571

terraform-v2/keycloak-dev/standard-clients/isd-kkcfs-diona-data-manager-4572.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://kkcfs.diona.mobi:9011/oauth2/redirect</li>
</ul>
</details>
=> request: add client files for isd-kkcfs-diona-data-manager-4572

terraform-v2/keycloak-dev/standard-clients/tians-testing-2-3-keycloak-upgrade-testing-2-4574.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-2-3-keycloak-upgrade-testing-2-4574.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-2-3-keycloak-upgrade-testing-2-4574

terraform-v2/keycloak-dev/standard-clients/chefs-fider-4575.tf, terraform-v2/keycloak-prod/standard-clients/chefs-fider-4575.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://chefs-fider.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://chefs-fider.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for chefs-fider-4575

terraform-v2/keycloak-dev/standard-clients/cvcom-4576.tf, terraform-v2/keycloak-prod/standard-clients/cvcom-4576.tf, terraform-v2/keycloak-test/standard-clients/cvcom-4576.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:44328/</li><li>https://localhost:44328/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:44328/</li><li>https://localhost:44328/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:44328/</li><li>https://localhost:44328/*</li>
</ul>
</details>
=> request: add client files for cvcom-4576

terraform-v2/keycloak-dev/standard-clients/mcfd-mobility-4577.tf, terraform-v2/keycloak-test/standard-clients/mcfd-mobility-4577.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for mcfd-mobility-4577

terraform-v2/keycloak-dev/standard-clients/payment-common-component-wordpress-4578.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://wpp-dev.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for payment-common-component-wordpress-4578

terraform-v2/keycloak-dev/standard-clients/isb-mfa-test-4579.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8000/auth/cb/keycloak/</li>
</ul>
</details>
=> request: add client files for isb-mfa-test-4579

terraform-v2/keycloak-dev/standard-clients/tians-testing-2-8-refreshing-fix-4581.tf
=> request: add client files for tians-testing-2-8-refreshing-fix-4581

terraform-v2/keycloak-dev/standard-clients/tians-testing-2-8-b-ce-id-only-4583.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-2-8-b-ce-id-only-4583.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-2-8-b-ce-id-only-4583

terraform-v2/keycloak-dev/standard-clients/tians-testing-2-8-b-ce-id-and-git-hub-4584.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-2-8-b-ce-id-and-git-hub-4584.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-2-8-b-ce-id-and-git-hub-4584

terraform-v2/keycloak-dev/standard-clients/tians-testing-2-8-b-ce-id-email-category-4585.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-2-8-b-ce-id-email-category-4585.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-2-8-b-ce-id-email-category-4585

terraform-v2/keycloak-dev/standard-clients/mds-bcmi-4587.tf, terraform-v2/keycloak-prod/standard-clients/mds-bcmi-4587.tf, terraform-v2/keycloak-test/standard-clients/mds-bcmi-4587.tf
=> request: add client files for mds-bcmi-4587

terraform-v2/keycloak-dev/standard-clients/labr-eao-case-tracking-system-4590.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost/*</li><li>https://localhost/*</li>
</ul>
</details>
=> request: add client files for labr-eao-case-tracking-system-4590

terraform-v2/keycloak-dev/standard-clients/spd-4592.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:4200/*</li><li>https://frontend-dev.apps.emerald.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for spd-4592

terraform-v2/keycloak-dev/standard-clients/hrt-intake-4582.tf, terraform-v2/keycloak-prod/standard-clients/hrt-intake-4582.tf, terraform-v2/keycloak-test/standard-clients/hrt-intake-4582.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://angular-on-nginx-2cf5e3-dev.apps.silver.devops.gov.bc.ca/hrt/hrt</li><li>https://angular-on-nginx-2cf5e3-dev.apps.silver.devops.gov.bc.ca/hrt/hrt-group</li><li>https://angular-on-nginx-2cf5e3-dev.apps.silver.devops.gov.bc.ca/hrt/hrt-retaliation</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://angular-on-nginx-2cf5e3-test.apps.silver.devops.gov.bc.ca/hrt/hrt</li><li>https://angular-on-nginx-2cf5e3-test.apps.silver.devops.gov.bc.ca/hrt/hrt-group</li><li>https://angular-on-nginx-2cf5e3-test.apps.silver.devops.gov.bc.ca/hrt/hrt-retaliation</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect …
=> request: add client files for hrt-intake-4582

terraform-v2/keycloak-dev/standard-clients/tester-marco-4593.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://*</li>
</ul>
</details>
=> request: add client files for tester-marco-4593

terraform-v2/keycloak-dev/standard-clients/one-team-jenkins-4595.tf, terraform-v2/keycloak-prod/standard-clients/one-team-jenkins-4595.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://oneteam-jenkins-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://oneteam-jenkins.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for one-team-jenkins-4595

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1364-4596.tf
=> request: add client files for service-account-team-1364-4596

terraform-v2-custom/keycloak-dev/custom-realms/access-to-court-materials-jag.tf, terraform-v2-custom/keycloak-dev/custom-realms/court-services-jag.tf, terraform-v2-custom/keycloak-prod/custom-realms/access-to-court-materials-jag.tf, terraform-v2-custom/keycloak-prod/custom-realms/court-services-jag.tf, terraform-v2-custom/keycloak-test/custom-realms/access-to-court-materials-jag.tf, terraform-v2-custom/keycloak-test/custom-realms/court-services-jag.tf
1. court-services-jag
2. access-to-court-materials-jag
=> chore: creating court custom realms

terraform-v2/keycloak-dev/standard-clients/gdx-suite-crm-open-id-4597.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://gdx-suitecrm-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for gdx-suite-crm-open-id-4597

terraform-v2/keycloak-dev/standard-clients/on-route-bc-direct-4598.tf, terraform-v2/keycloak-test/standard-clients/on-route-bc-direct-4598.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000</li><li>https://*.silver.devops.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost*</li><li>https://onroutebc-test-frontend.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for on-route-bc-direct-4598

terraform-v2/keycloak-dev/standard-clients/tacs-bc-athletic-commissioner-4599.tf, terraform-v2/keycloak-prod/standard-clients/tacs-bc-athletic-commissioner-4599.tf, terraform-v2/keycloak-test/standard-clients/tacs-bc-athletic-commissioner-4599.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8000/auth/v1/callback</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8000/auth/v1/callback</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://dg0000000jk0rmae.lightning.force.com/services/authcallback/BCGovSSO</li>
</ul>
</details>
=> request: add client files for tacs-bc-athletic-commissioner-4599

terraform-v2/keycloak-dev/standard-clients/test-auth-sync-4600.tf
=> request: add client files for test-auth-sync-4600

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1366-4601.tf
=> request: add client files for service-account-team-1366-4601

terraform-v2/keycloak-dev/standard-clients/bc-parks-dam-4602.tf, terraform-v2/keycloak-prod/standard-clients/bc-parks-dam-4602.tf, terraform-v2/keycloak-test/standard-clients/bc-parks-dam-4602.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://devapps.nrs.gov.bc.ca/int/parksdam/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://testapps.nrs.gov.bc.ca/int/parksdam/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://apps.nrs.gov.bc.ca/int/parksdam/</li>
</ul>
</details>
=> request: add client files for bc-parks-dam-4602

terraform-v2/keycloak-dev/standard-clients/mds-fider-4603.tf, terraform-v2/keycloak-prod/standard-clients/mds-fider-4603.tf, terraform-v2/keycloak-test/standard-clients/mds-fider-4603.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://fider-4c2ba9-test.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://fider-4c2ba9-test.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://fider.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for mds-fider-4603

terraform-v2/keycloak-dev/standard-clients/mds-fider-app-4621.tf, terraform-v2/keycloak-prod/standard-clients/mds-fider-app-4621.tf, terraform-v2/keycloak-test/standard-clients/mds-fider-app-4621.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://fider-4c2ba9-test.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://fider-4c2ba9-test.apps.silver.devops.gov.bc.ca/</li><li>https://fider-4c2ba9-test.apps.silver.devops.gov.bc.ca/oauth/_6tb93ffege/callback</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://fider.apps.silver.devops.gov.bc.ca/</li><li>https://fider.apps.silver.devops.gov.bc.ca/oauth/_utqsayjs2a/callback</li>
</ul>
</details>
=> request: add client files for mds-fider-app-4621

terraform-v2/keycloak-dev/standard-clients/rocket-chat-sso-4623.tf, terraform-v2/keycloak-prod/standard-clients/rocket-chat-sso-4623.tf, terraform-v2/keycloak-test/standard-clients/rocket-chat-sso-4623.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://chat-dev.developer.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://chat-test.developer.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://chat.developer.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for rocket-chat-sso-4623

terraform-v2/keycloak-dev/standard-clients/jpidp-4624.tf, terraform-v2/keycloak-prod/standard-clients/jpidp-4624.tf, terraform-v2/keycloak-test/standard-clients/jpidp-4624.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.common-sso.justice.gov.bc.ca/auth/realms/IDIR/broker/idir/endpoint</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.common-sso.justice.gov.bc.ca/auth/realms/IDIR/broker/idir/endpoint</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://common-sso.justice.gov.bc.ca/auth/realms/IDIR/broker/idir/endpoint</li>
</ul>
</details>
=> request: add client files for jpidp-4624

terraform-v2/keycloak-dev/standard-clients/access-to-court-materials-4625.tf, terraform-v2/keycloak-prod/standard-clients/access-to-court-materials-4625.tf, terraform-v2/keycloak-test/standard-clients/access-to-court-materials-4625.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/access-to-court-materials-jag/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/access-to-court-materials-jag/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/access-to-court-materials-jag/*</li>
</ul>
</details>
=> request: add client files for access-to-court-materials-4625

terraform-v2/keycloak-dev/standard-clients/court-services-4626.tf, terraform-v2/keycloak-prod/standard-clients/court-services-4626.tf, terraform-v2/keycloak-test/standard-clients/court-services-4626.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/court-services-jag/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/court-services-jag/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/court-services-jag/*</li>
</ul>
</details>
=> request: add client files for court-services-4626

terraform-v2/keycloak-dev/standard-clients/stack-overflow-sso-4628.tf, terraform-v2/keycloak-prod/standard-clients/stack-overflow-sso-4628.tf, terraform-v2/keycloak-test/standard-clients/stack-overflow-sso-4628.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://stackoverflow-dev.developer.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://stackoverflow-test.developer.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://stackoverflow.developer.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for stack-overflow-sso-4628

terraform-v2/keycloak-dev/standard-clients/critterbase-4629.tf, terraform-v2/keycloak-prod/standard-clients/critterbase-4629.tf, terraform-v2/keycloak-test/standard-clients/critterbase-4629.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost/*</li><li>http://localhost:1111/*</li><li>http://localhost:80/*</li><li>http://localhost:8080/*</li><li>http://moe-critterbase-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://moe-critterbase-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://critterbase.nrs.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for critterbase-4629

terraform-v2/keycloak-dev/standard-clients/test-git-action-nk-4630.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://example</li>
</ul>
</details>
=> request: add client files for test-git-action-nk-4630

terraform-v2/keycloak-dev/standard-clients/dev-hub-4632.tf, terraform-v2/keycloak-prod/standard-clients/dev-hub-4632.tf, terraform-v2/keycloak-test/standard-clients/dev-hub-4632.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://developer-dev.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://developer-test.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://developer.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for dev-hub-4632

terraform-v2/keycloak-dev/standard-clients/first-nations-spill-notification-project-4633.tf, terraform-v2/keycloak-prod/standard-clients/first-nations-spill-notification-project-4633.tf, terraform-v2/keycloak-test/standard-clients/first-nations-spill-notification-project-4633.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000</li>
</ul>
</details>
=> request: add client files for first-nations-spill-notification-project-4633

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1367-4634.tf
=> request: add client files for service-account-team-1367-4634

terraform-v2/keycloak-dev/standard-clients/tians-testing-2-27-service-account-4635.tf
=> request: add client files for tians-testing-2-27-service-account-4635

terraform-v2/keycloak-dev/standard-clients/test-saml-client-nk-4658.tf, terraform-v2/keycloak-prod/standard-clients/test-saml-client-nk-4658.tf, terraform-v2/keycloak-test/standard-clients/test-saml-client-nk-4658.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://*</li>
</ul>
</details>
=> request: add client files for test-saml-client-nk-4658

terraform-v2/keycloak-dev/standard-clients/first-nations-spill-notification-project-4660.tf, terraform-v2/keycloak-prod/standard-clients/first-nations-spill-notification-project-4660.tf, terraform-v2/keycloak-test/standard-clients/first-nations-spill-notification-project-4660.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://portal.alertable.ca/sso/saml/970939fa-56cb-46cb-80ba-865c088c6a2f/acs/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://portal.alertable.ca/sso/saml/970939fa-56cb-46cb-80ba-865c088c6a2f/acs/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://portal.alertable.ca/sso/saml/970939fa-56cb-46cb-80ba-865c088c6a2f/acs/</li>
</ul>
</details>
=> request: add client files for first-nations-spill-notification-project-4660

terraform-v2/keycloak-dev/standard-clients/tians-testing-3-8-git-hub-only-1-4662.tf
=> request: add client files for tians-testing-3-8-git-hub-only-1-4662

terraform-v2/keycloak-dev/standard-clients/tians-testing-3-8-git-hub-only-2-4663.tf
=> request: add client files for tians-testing-3-8-git-hub-only-2-4663

terraform-v2/keycloak-dev/standard-clients/tians-testing-3-8-multiple-id-ps-4664.tf
=> request: add client files for tians-testing-3-8-multiple-id-ps-4664

terraform-v2/keycloak-dev/standard-clients/tians-testing-3-8-idir-only-4665.tf
=> request: add client files for tians-testing-3-8-idir-only-4665

terraform-v2/keycloak-dev/standard-clients/tians-testing-3-9-idir-azure-idir-4666.tf
=> request: add client files for tians-testing-3-9-idir-azure-idir-4666

terraform-v2/keycloak-dev/standard-clients/bwat-4667.tf
=> request: add client files for bwat-4667

terraform-v2/keycloak-dev/standard-clients/grace-4668.tf, terraform-v2/keycloak-prod/standard-clients/grace-4668.tf, terraform-v2/keycloak-test/standard-clients/grace-4668.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost</li>
</ul>
</details>
=> request: add client files for grace-4668

terraform-v2/keycloak-dev/standard-clients/bwat-4669.tf
=> request: add client files for bwat-4669

terraform-v2/keycloak-dev/standard-clients/integrated-project-services-ips-4659.tf, terraform-v2/keycloak-prod/standard-clients/integrated-project-services-ips-4659.tf, terraform-v2/keycloak-test/standard-clients/integrated-project-services-ips-4659.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://ipsmotit.pmweb.com/PMWebSAML/</li><li>https://ipsmotit.pmweb.com/PMWebSAML/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://ipsmotit.pmweb.com/PMWebSAML/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://ipsmoti.pmweb.com/PMWebSAML/</li>
</ul>
</details>
=> request: add client files for integrated-project-services-ips-4659

terraform-v2/keycloak-dev/standard-clients/ecobase-4689.tf, terraform-v2/keycloak-prod/standard-clients/ecobase-4689.tf, terraform-v2/keycloak-test/standard-clients/ecobase-4689.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost/*</li><li>http://localhost:1111/*</li><li>http://localhost:80/*</li><li>http://localhost:8080/*</li><li>http://moe-ecobase-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://moe-ecobase-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://ecobase.nrs.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for ecobase-4689

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-827-4163.tf
=> request: delete client files for service-account-team-827-4163

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1455-4690.tf
=> request: add client files for service-account-team-1455-4690

terraform-v2/keycloak-dev/standard-clients/services-billing-4693.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:7150/</li>
</ul>
</details>
=> request: add client files for services-billing-4693

terraform-v2/keycloak-dev/standard-clients/flow-fit-sso-4697.tf, terraform-v2/keycloak-test/standard-clients/flow-fit-sso-4697.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://eductrabc.flowfitservices.com/FlowFitAPI/api/saml/AssertionConsumerServiceTMS</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://eductrabc.flowfitservices.com/FlowFitAPI/api/saml/AssertionConsumerServiceTMS</li>
</ul>
</details>
=> request: add client files for flow-fit-sso-4697

terraform-v2/keycloak-dev/standard-clients/property-services-project-app-dev-only-4699.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>https://dev-pims.th.gov.bc.ca/*</li><li>https://pims-app-3cd915-dev.apps.silver.devops.gov.bc.ca/*</li><li>https://pims-app-devin-3cd915-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for property-services-project-app-dev-only-4699

terraform-v2/keycloak-dev/standard-clients/wordpress-dev-4701.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dm-wp-mig-test.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for wordpress-dev-4701

terraform-v2/keycloak-dev/standard-clients/digital-talent-hms-www-4702.tf
=> request: add client files for digital-talent-hms-www-4702

terraform-v2/keycloak-dev/standard-clients/trans-action-deploy-4704.tf
=> request: add client files for trans-action-deploy-4704

terraform-v2/keycloak-dev/standard-clients/digital-gov-bc-ca-4705.tf, terraform-v2/keycloak-prod/standard-clients/digital-gov-bc-ca-4705.tf, terraform-v2/keycloak-test/standard-clients/digital-gov-bc-ca-4705.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dm-wp-mig-test.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://dm-wp-test.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://digital-wp.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for digital-gov-bc-ca-4705

terraform-v2/keycloak-dev/standard-clients/icm-isd-sandbox-4706.tf
=> request: add client files for icm-isd-sandbox-4706

terraform-v2/keycloak-dev/standard-clients/isd-forms-cf-4116-4707.tf
=> request: add client files for isd-forms-cf-4116-4707

terraform-v2/keycloak-dev/standard-clients/samplea-4710.tf, terraform-v2/keycloak-test/standard-clients/samplea-4710.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://platsrv-registry-web-101ed4-test.apps.silver.devops.gov.bc.ca/callback_url</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://platsrv-registry-web-101ed4-test.apps.silver.devops.gov.bc.ca/callback_url</li>
</ul>
</details>
=> request: add client files for samplea-4710

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1293-4711.tf
=> request: add client files for service-account-team-1293-4711

terraform-v2/keycloak-dev/standard-clients/chefs-data-ingestion-ministry-of-health-4712.tf, terraform-v2/keycloak-test/standard-clients/chefs-data-ingestion-ministry-of-health-4712.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/standard/*</li><li>https://keycloak-c2da03-dev.apps.silver.devops.gov.bc.ca/*</li><li>https://medis-chefs-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/standard/*</li><li>https://keycloak-c2da03-test.apps.silver.devops.gov.bc.ca/*</li><li>https://medis-chefs-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for chefs-data-ingestion-ministry-of-health-4712

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1061-4713.tf
=> request: add client files for service-account-team-1061-4713

terraform-v2/keycloak-dev/standard-clients/ag-azure-ad-4714.tf, terraform-v2/keycloak-prod/standard-clients/ag-azure-ad-4714.tf, terraform-v2/keycloak-test/standard-clients/ag-azure-ad-4714.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.common-sso.justice.gov.bc.ca/auth/realms/AG-AzureAD/broker/azuread/endpoint</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.common-sso.justice.gov.bc.ca/auth/realms/AG-AzureAD/broker/azuread/endpoint</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://common-sso.justice.gov.bc.ca/auth/realms/AG-AzureAD/broker/azuread/endpoint</li>
</ul>
</details>
=> request: add client files for ag-azure-ad-4714

terraform-v2/keycloak-dev/standard-clients/tians-testing-3-28-saml-4715.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8080/*</li>
</ul>
</details>
=> request: add client files for tians-testing-3-28-saml-4715

terraform-v2/keycloak-dev/standard-clients/test-redirect-uri-nk-prod-4716.tf
=> request: add client files for test-redirect-uri-nk-prod-4716

terraform-v2/keycloak-dev/standard-clients/abc-4717.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://zeva-dev-*.apps.silver/</li>
</ul>
</details>
=> request: add client files for abc-4717

terraform-v2/keycloak-dev/standard-clients/habitat-restoration-tracker-4718.tf, terraform-v2/keycloak-prod/standard-clients/habitat-restoration-tracker-4718.tf, terraform-v2/keycloak-test/standard-clients/habitat-restoration-tracker-4718.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://restorationtracker.nrs.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for habitat-restoration-tracker-4718

terraform-v2/keycloak-dev/standard-clients/habitat-restoration-tracker-svc-4719.tf, terraform-v2/keycloak-prod/standard-clients/habitat-restoration-tracker-svc-4719.tf, terraform-v2/keycloak-test/standard-clients/habitat-restoration-tracker-svc-4719.tf
=> request: add client files for habitat-restoration-tracker-svc-4719

terraform-v2/keycloak-dev/standard-clients/spd-dynamics-api-4721.tf, terraform-v2/keycloak-test/standard-clients/spd-dynamics-api-4721.tf
=> request: add client files for spd-dynamics-api-4721

terraform-v2/keycloak-dev/standard-clients/chefs-4724.tf
=> request: add client files for chefs-4724

terraform-v2/keycloak-dev/standard-clients/chefs-local-4725.tf
=> request: add client files for chefs-local-4725

terraform-v2/keycloak-dev/standard-clients/chefs-localhost-4753.tf
=> request: add client files for chefs-localhost-4753

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1458-4788.tf
=> request: add client files for service-account-team-1458-4788

terraform-v2/keycloak-dev/standard-clients/modern-engagement-tools-4787.tf
=> request: add client files for modern-engagement-tools-4787

terraform-v2/keycloak-dev/standard-clients/mds-gentax-4790.tf, terraform-v2/keycloak-prod/standard-clients/mds-gentax-4790.tf, terraform-v2/keycloak-test/standard-clients/mds-gentax-4790.tf
=> request: add client files for mds-gentax-4790

terraform-v2/keycloak-dev/standard-clients/mds-nris-4791.tf, terraform-v2/keycloak-prod/standard-clients/mds-nris-4791.tf, terraform-v2/keycloak-test/standard-clients/mds-nris-4791.tf
=> request: add client files for mds-nris-4791

terraform-v2/keycloak-dev/standard-clients/mds-bcgw-4792.tf, terraform-v2/keycloak-prod/standard-clients/mds-bcgw-4792.tf, terraform-v2/keycloak-test/standard-clients/mds-bcgw-4792.tf
=> request: add client files for mds-bcgw-4792

terraform-v2/keycloak-dev/standard-clients/compliance-and-enforcement-digital-services-4793.tf
=> request: add client files for compliance-and-enforcement-digital-services-4793

terraform-v2/keycloak-dev/standard-clients/compliance-and-enforcement-digital-services-web-4794.tf
=> request: add client files for compliance-and-enforcement-digital-services-web-4794

terraform-v2/keycloak-dev/standard-clients/citz-imb-sandbox-4796.tf, terraform-v2/keycloak-prod/standard-clients/citz-imb-sandbox-4796.tf, terraform-v2/keycloak-test/standard-clients/citz-imb-sandbox-4796.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost/*</li>
</ul>
</details>
=> request: add client files for citz-imb-sandbox-4796

terraform-v2/keycloak-dev/standard-clients/nmp-msa-4797.tf, terraform-v2/keycloak-prod/standard-clients/nmp-msa-4797.tf, terraform-v2/keycloak-test/standard-clients/nmp-msa-4797.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>http://localhost:5001</li><li>https://agri-nmp-msa-test.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://agri-nmp-msa-dev.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for nmp-msa-4797

terraform-v2/keycloak-dev/standard-clients/nr-broker-4799.tf, terraform-v2/keycloak-prod/standard-clients/nr-broker-4799.tf, terraform-v2/keycloak-test/standard-clients/nr-broker-4799.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>https://nr-broker-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://nr-broker-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://nr-broker.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for nr-broker-4799

terraform-v2/keycloak-dev/standard-clients/af-pods-4800.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000</li>
</ul>
</details>
=> request: add client files for af-pods-4800

terraform-v2/keycloak-dev/standard-clients/nr-brmb-chefs-4801.tf
=> request: add client files for nr-brmb-chefs-4801

terraform-v2/keycloak-dev/standard-clients/cvcom-dev-4803.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev-cvcom-proxied.th.gov.bc.ca/</li><li>https://dev-cvcom-proxied.th.gov.bc.ca/*</li><li>https://dev-cvcom.th.gov.bc.ca/</li><li>https://dev-cvcom.th.gov.bc.ca/*</li><li>https://localhost:44328/</li><li>https://localhost:44328/*</li>
</ul>
</details>
=> request: add client files for cvcom-dev-4803

terraform-v2/keycloak-dev/standard-clients/nrpti-4804.tf, terraform-v2/keycloak-prod/standard-clients/nrpti-4804.tf, terraform-v2/keycloak-test/standard-clients/nrpti-4804.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>http://localhost:8080</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://nrpti-f00029-prod.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for nrpti-4804

terraform-v2/keycloak-dev/standard-clients/iosis-test-4807.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost</li>
</ul>
</details>
=> request: add client files for iosis-test-4807

terraform-v2/keycloak-dev/standard-clients/abc-4798.tf, terraform-v2/keycloak-prod/standard-clients/abc-4798.tf, terraform-v2/keycloak-test/standard-clients/abc-4798.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://platsrv-registry-web-101ed4-test.apps.silver.devops.gov.bc.ca/callback_url</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost</li>
</ul>
</details>
=> request: add client files for abc-4798

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1027-4809.tf
=> request: add client files for service-account-team-1027-4809

terraform-v2/keycloak-dev/standard-clients/may-1-4722.tf
=> request: add client files for may-1-4722

terraform-v2/keycloak-dev/standard-clients/test-marco-4811.tf, terraform-v2/keycloak-test/standard-clients/test-marco-4811.tf
=> request: add client files for test-marco-4811

terraform-v2/keycloak-dev/standard-clients/hestia-4813.tf, terraform-v2/keycloak-prod/standard-clients/hestia-4813.tf, terraform-v2/keycloak-test/standard-clients/hestia-4813.tf
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>hestia://mobile-client</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>hestia://mobile-client</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>hestia://mobile-client</li>
</ul>
</details>
=> request: add client files for hestia-4813

terraform-v2/keycloak-dev/standard-clients/tians-testing-5-3-saml-4814.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-5-3-saml-4814.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-5-3-saml-4814

terraform-v2/keycloak-dev/standard-clients/testing-nk-saml-4815.tf
=> request: add client files for testing-nk-saml-4815

terraform-v2/keycloak-dev/standard-clients/inspect-bc-mussels-4817.tf
=> request: add client files for inspect-bc-mussels-4817

terraform-v2/keycloak-dev/standard-clients/tians-testing-5-3-saml-id-change-4818.tf
=> request: add client files for tians-testing-5-3-saml-id-change-4818

terraform-v2/keycloak-dev/standard-clients/tians-testing-saml-5-3-test-4819.tf
=> request: add client files for tians-testing-saml-5-3-test-4819

terraform-v2/keycloak-dev/standard-clients/spd-screening-portal-4592.tf, terraform-v2/keycloak-test/standard-clients/spd-screening-portal-4592.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:4200</li><li>http://localhost:4200/*</li><li>https://spd-screening-portal-dev.apps.emerald.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://spd-screening-portal-test.apps.emerald.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for spd-screening-portal-4592

terraform-v2/keycloak-dev/standard-clients/gwells-api-tests-4820.tf, terraform-v2/keycloak-test/standard-clients/gwells-api-tests-4820.tf
=> request: add client files for gwells-api-tests-4820

terraform-v2/keycloak-dev/standard-clients/service-now-api-4821.tf, terraform-v2/keycloak-prod/standard-clients/service-now-api-4821.tf
=> request: add client files for service-now-api-4821

terraform-v2/keycloak-dev/standard-clients/lucy-api-4822.tf
=> request: add client files for lucy-api-4822

terraform-v2/keycloak-dev/standard-clients/test-service-account-4823.tf, terraform-v2/keycloak-prod/standard-clients/test-service-account-4823.tf
=> request: add client files for test-service-account-4823

terraform-v2/keycloak-dev/standard-clients/invasives-bc-4824.tf
=> request: add client files for invasives-bc-4824

terraform-v2/keycloak-dev/standard-clients/tians-testing-service-account-5-4-4825.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-service-account-5-4-4825.tf
=> request: add client files for tians-testing-service-account-5-4-4825

terraform-v2/keycloak-dev/standard-clients/may-4-test-6-pm-4826.tf
=> request: add client files for may-4-test-6-pm-4826

terraform-v2/keycloak-dev/standard-clients/spd-screening-portal-4828.tf, terraform-v2/keycloak-test/standard-clients/spd-screening-portal-4828.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:4200</li><li>http://localhost:4200/*</li><li>https://spd-screening-portal-dev.apps.emerald.devops.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://spd-screening-portal-test.apps.emerald.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for spd-screening-portal-4828

terraform-v2/keycloak-dev/standard-clients/tians-testing-5-3-service-account-4829.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-5-3-service-account-4829.tf
=> request: add client files for tians-testing-5-3-service-account-4829

terraform-v2/keycloak-dev/standard-clients/tians-testing-5-5-post-test-4833.tf
=> request: add client files for tians-testing-5-5-post-test-4833

terraform-v2/keycloak-dev/standard-clients/service-now-login-4834.tf, terraform-v2/keycloak-prod/standard-clients/service-now-login-4834.tf, terraform-v2/keycloak-test/standard-clients/service-now-login-4834.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://econsdev.service-now.com/oauth_redirect.do</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://econstest.service-now.com/oauth_redirect.do</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://econ.service-now.com/oauth_redirect.do</li>
</ul>
</details>
=> request: add client files for service-now-login-4834

terraform-v2/keycloak-prod/standard-service-accounts/service-account-for-team-694-4838.tf
=> request: add client files for service-account-for-team-694-4838

terraform-v2/keycloak-dev/standard-clients/service-account-browser-login-4839.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.com</li>
</ul>
</details>
=> request: add client files for service-account-browser-login-4839

terraform-v2/keycloak-dev/standard-clients/tians-testing-5-10-both-4842.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-5-10-both-4842.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-5-10-both-4842

terraform-v2/keycloak-dev/standard-clients/wally-api-4845.tf, terraform-v2/keycloak-test/standard-clients/wally-api-4845.tf
=> request: add client files for wally-api-4845

terraform-v2/keycloak-dev/standard-clients/visitz-4846.tf, terraform-v2/keycloak-prod/standard-clients/visitz-4846.tf, terraform-v2/keycloak-test/standard-clients/visitz-4846.tf
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>visitz://mobile-client</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>visitz://mobile-client</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>visitz://mobile-client</li>
</ul>
</details>
=> request: add client files for visitz-4846

terraform-v2/keycloak-dev/standard-clients/af-cdss-4847.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://cdss.powerappsportals.com/*</li>
</ul>
</details>
=> request: add client files for af-cdss-4847

terraform-v2/keycloak-dev/standard-clients/digital-wordpress-4701.tf, terraform-v2/keycloak-prod/standard-clients/digital-wordpress-4701.tf, terraform-v2/keycloak-test/standard-clients/digital-wordpress-4701.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://digital-dev.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://digital-test.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://digital.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for digital-wordpress-4701

terraform-v2/keycloak-dev/standard-clients/iosas-4848.tf, terraform-v2/keycloak-prod/standard-clients/iosas-4848.tf, terraform-v2/keycloak-test/standard-clients/iosas-4848.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://soam-dev.apps.silver.devops.gov.bc.ca/auth/realms/IOSAS/broker/basic-bceid/endpoint</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://soam-test.apps.silver.devops.gov.bc.ca/auth/realms/IOSAS/broker/basic-bceid/endpoint</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://soam-prod.apps.silver.devops.gov.bc.ca/auth/realms/IOSAS/broker/basic-bceid/endpoint</li>
</ul>
</details>
=> request: add client files for iosas-4848

terraform-v2/keycloak-dev/standard-clients/test-oidc-proj-name-nk-1-4850.tf
=> request: add client files for test-oidc-proj-name-nk-1-4850

terraform-v2/keycloak-dev/standard-clients/realm-profile-app-gold-4849.tf, terraform-v2/keycloak-test/standard-clients/realm-profile-app-gold-4849.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:8000/*</li><li>http://localhost:8080/*</li><li>http://localhost:8081/*</li><li>http://localhost:8089/*</li><li>http://realm-registry-b861c7-dev.apps.silver.devops.gov.bc.ca/*</li><li>http://realm-registry-dev.apps.silver.devops.gov.bc.ca/*</li><li>http://realm-registry.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for realm-profile-app-gold-4849

terraform-v2/keycloak-dev/standard-clients/emcr-web-eoc-training-4852.tf, terraform-v2/keycloak-test/standard-clients/emcr-web-eoc-training-4852.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bctraining.demo.webeocasp.com/bctraining/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://bctraining.demo.webeocasp.com/bctraining/*</li>
</ul>
</details>
=> request: add client files for emcr-web-eoc-training-4852

terraform-v2/keycloak-dev/standard-clients/tians-testing-5-18-oidc-4854.tf
=> request: add client files for tians-testing-5-18-oidc-4854

terraform-v2/keycloak-dev/standard-clients/tians-testing-5-18-saml-4855.tf
=> request: add client files for tians-testing-5-18-saml-4855

terraform-v2/keycloak-dev/standard-clients/isd-alm-4856.tf, terraform-v2/keycloak-prod/standard-clients/isd-alm-4856.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://qc-icm-test.apps.gov.bc.ca/osp/a/alm/auth/oauth2/landingpad</li><li>https://qc.icm.gov.bc.ca/osp/a/alm/auth/oauth2/landingpad</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://qc-icm-test.apps.gov.bc.ca/osp/a/alm/auth/oauth2/landingpad</li><li>https://qc.icm.gov.bc.ca/osp/a/alm/auth/oauth2/landingpad</li>
</ul>
</details>
=> request: add client files for isd-alm-4856

terraform-v2/keycloak-dev/standard-clients/dotnet-6-test-4857.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:5001/*</li>
</ul>
</details>
=> request: add client files for dotnet-6-test-4857

terraform-v2/keycloak-dev/standard-clients/ride-sso-4861.tf, terraform-v2/keycloak-prod/standard-clients/ride-sso-4861.tf, terraform-v2/keycloak-test/standard-clients/ride-sso-4861.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8080</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8080</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8080</li>
</ul>
</details>
=> request: add client files for ride-sso-4861

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1487-4862.tf
=> request: add client files for service-account-for-team-1487-4862

terraform-v2/keycloak-dev/standard-clients/met-gold-4795.tf, terraform-v2/keycloak-prod/standard-clients/met-gold-4795.tf, terraform-v2/keycloak-test/standard-clients/met-gold-4795.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://met-oidc-dev.apps.gold.devops.gov.bc.ca/auth/realms/met/broker/idir/endpoint</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://met-oidc-test.apps.gold.devops.gov.bc.ca/auth/realms/met/broker/idir/endpoint/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://met-oidc.apps.gold.devops.gov.bc.ca/auth/realms/met/broker/idir/endpoint</li><li>https://met-oidc.apps.gold.devops.gov.bc.ca/auth/realms/met/broker/idir/endpoint/logout_response</li>
</ul>
</details>
=> request: add client files for met-gold-4795

terraform-v2/keycloak-dev/standard-clients/spd-integration-tests-4864.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:4200/*</li>
</ul>
</details>
=> request: add client files for spd-integration-tests-4864

terraform-v2/keycloak-dev/standard-clients/mds-docman-celery-internal-4865.tf, terraform-v2/keycloak-prod/standard-clients/mds-docman-celery-internal-4865.tf, terraform-v2/keycloak-test/standard-clients/mds-docman-celery-internal-4865.tf
=> request: add client files for mds-docman-celery-internal-4865

terraform-v2/keycloak-dev/standard-clients/waiting-queue-4805.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:5027/</li><li>https://waitingqueue-admin-dev.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for waiting-queue-4805

terraform/keycloak-dev/realms/onestopauth-both/client-ceed-evolution-3334.tf, terraform/keycloak-test/realms/onestopauth-both/client-ceed-evolution-3334.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://funding-guide-dev.powerappsportals.com/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://ceed.microsoftcrmportals.com/signin-openid_1</li>
</ul>
</details>
=> request: delete client files for ceed-evolution-3334

terraform-v2/keycloak-dev/standard-clients/nrpti-4866.tf, terraform-v2/keycloak-prod/standard-clients/nrpti-4866.tf, terraform-v2/keycloak-test/standard-clients/nrpti-4866.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://nrpti-f00029-prod.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for nrpti-4866

terraform-v2/keycloak-dev/standard-clients/nrpti-4869.tf, terraform-v2/keycloak-prod/standard-clients/nrpti-4869.tf, terraform-v2/keycloak-test/standard-clients/nrpti-4869.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://nrpti-f00029-prod.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for nrpti-4869

terraform-v2/keycloak-dev/standard-clients/cmf-sonar-qube-4871.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://sonarqube-48aa05-tools.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for cmf-sonar-qube-4871

terraform-v2/keycloak-dev/standard-clients/wsdl-test-as-4885.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://keycloak-example-apps/examples/oidc/public/react</li>
</ul>
</details>
=> request: add client files for wsdl-test-as-4885

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1497-4886.tf
=> request: add client files for service-account-for-team-1497-4886

terraform-v2/keycloak-dev/standard-clients/test-cache-nk-1-4890.tf
=> request: add client files for test-cache-nk-1-4890

terraform-v2/keycloak-dev/standard-clients/test-cache-nk-2-4891.tf
=> request: add client files for test-cache-nk-2-4891

terraform-v2/keycloak-dev/standard-clients/saw-sx-4892.tf, terraform-v2/keycloak-prod/standard-clients/saw-sx-4892.tf, terraform-v2/keycloak-test/standard-clients/saw-sx-4892.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>https://dev-awp.th.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://tst-awp.th.gov.bc.ca/*</li><li>https://uat-awp.th.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://awp.th.gov.bc.ca/*</li><li>https://rft-awp.th.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for saw-sx-4892

terraform-v2/keycloak-dev/standard-clients/test-for-hyperlinks-4894.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://abc123</li>
</ul>
</details>
=> request: add client files for test-for-hyperlinks-4894

terraform-v2/keycloak-dev/standard-clients/unity-4896.tf
=> request: add client files for unity-4896

terraform-v2/keycloak-dev/standard-clients/unity-4898.tf
=> request: add client files for unity-4898

terraform-v2/keycloak-dev/standard-clients/unity-4899.tf, terraform-v2/keycloak-prod/standard-clients/unity-4899.tf, terraform-v2/keycloak-test/standard-clients/unity-4899.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8080</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8081</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8082</li>
</ul>
</details>
=> request: add client files for unity-4899

terraform-v2/keycloak-dev/standard-clients/test-22-4900.tf, terraform-v2/keycloak-test/standard-clients/test-22-4900.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://www.test.com</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://www.test.com</li>
</ul>
</details>
=> request: add client files for test-22-4900

terraform-v2/keycloak-dev/standard-clients/bwat-business-4901.tf, terraform-v2/keycloak-prod/standard-clients/bwat-business-4901.tf, terraform-v2/keycloak-test/standard-clients/bwat-business-4901.tf
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://bwat.foundryspatial.com</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://bwat-test.bcwatertool.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://bwat-prod.bcwatertool.ca</li>
</ul>
</details>
=> request: add client files for bwat-business-4901

terraform-v2/keycloak-dev/standard-clients/june-26-test-b-ce-id-flow-4853.tf, terraform-v2/keycloak-prod/standard-clients/june-26-test-b-ce-id-flow-4853.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for june-26-test-b-ce-id-flow-4853

terraform-v2/keycloak-dev/standard-clients/june-26-b-ce-id-basic-business-test-4904.tf, terraform-v2/keycloak-prod/standard-clients/june-26-b-ce-id-basic-business-test-4904.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for june-26-b-ce-id-basic-business-test-4904

terraform-v2/keycloak-dev/standard-clients/june-26-b-ce-id-n-on-p-rods-test-4906.tf, terraform-v2/keycloak-test/standard-clients/june-26-b-ce-id-n-on-p-rods-test-4906.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for june-26-b-ce-id-n-on-p-rods-test-4906

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1524-4907.tf
=> request: delete client files for service-account-for-team-1524-4907

terraform-v2/keycloak-dev/standard-clients/june-26-only-traning-account-prod-4909.tf, terraform-v2/keycloak-prod/standard-clients/june-26-only-traning-account-prod-4909.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for june-26-only-traning-account-prod-4909

terraform-v2/keycloak-dev/standard-clients/fin-pay-transparency-4912.tf, terraform-v2/keycloak-prod/standard-clients/fin-pay-transparency-4912.tf, terraform-v2/keycloak-test/standard-clients/fin-pay-transparency-4912.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://fin-pay-transparency.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for fin-pay-transparency-4912

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1362-4914.tf
=> request: add client files for service-account-for-team-1362-4914

terraform-v2/keycloak-dev/standard-clients/chefs-local-4915.tf
=> request: add client files for chefs-local-4915

terraform-v2/keycloak-dev/standard-clients/tians-testing-6-29-team-then-no-team-4916.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-6-29-team-then-no-team-4916.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-6-29-team-then-no-team-4916

terraform-v2/keycloak-dev/standard-clients/common-hosted-form-service-elmsd-4917.tf
=> request: add client files for common-hosted-form-service-elmsd-4917

terraform-v2/keycloak-dev/standard-clients/chefs-4918.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:8080/*</li><li>https://localhost:8081/*</li><li>https://localhost:8082/*</li>
</ul>
</details>
=> request: add client files for chefs-4918

terraform-v2/keycloak-dev/standard-clients/sidetake-4920.tf, terraform-v2/keycloak-prod/standard-clients/sidetake-4920.tf, terraform-v2/keycloak-test/standard-clients/sidetake-4920.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>pcs-non-urgent://dummy-uri</li>
</ul>
</details>
=> request: add client files for sidetake-4920

terraform-v2/keycloak-dev/standard-clients/tians-testing-7-5-idir-only-4921.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-7-5-idir-only-4921.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
=> request: add client files for tians-testing-7-5-idir-only-4921

terraform-v2/keycloak-dev/standard-clients/tians-testing-7-5-all-idps-4922.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-7-5-all-idps-4922.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
=> request: add client files for tians-testing-7-5-all-idps-4922

terraform-v2/keycloak-dev/standard-clients/tians-testing-7-6-all-idps-2-4923.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-7-6-all-idps-2-4923.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
=> request: add client files for tians-testing-7-6-all-idps-2-4923

terraform-v2/keycloak-dev/standard-clients/bc-stats-coms-4924.tf
=> request: add client files for bc-stats-coms-4924

terraform-v2/keycloak-dev/standard-clients/bc-stats-coms-4925.tf
=> request: add client files for bc-stats-coms-4925

terraform-v2/keycloak-dev/standard-clients/bc-stats-coms-bc-box-4926.tf
=> request: add client files for bc-stats-coms-bc-box-4926

terraform-v2/keycloak-dev/standard-clients/aestintra-4927.tf, terraform-v2/keycloak-prod/standard-clients/aestintra-4927.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://test2.aestintra.gov.bc.ca/</li><li>https://test2.aestintra.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://gww.aestintra.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for aestintra-4927

terraform-v2/keycloak-dev/standard-clients/test-4929.tf
=> request: add client files for test-4929

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1065-4930.tf
=> request: add client files for service-account-for-team-1065-4930

terraform-v2/keycloak-dev/standard-clients/virtual-home-energy-rating-system-4932.tf, terraform-v2/keycloak-prod/standard-clients/virtual-home-energy-rating-system-4932.tf, terraform-v2/keycloak-test/standard-clients/virtual-home-energy-rating-system-4932.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://cleanbc.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://cleanbc.gov.bc.ca/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://cleanbc.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for virtual-home-energy-rating-system-4932

terraform-v2/keycloak-dev/standard-clients/aps-ops-grafana-4933.tf, terraform-v2/keycloak-prod/standard-clients/aps-ops-grafana-4933.tf, terraform-v2/keycloak-test/standard-clients/aps-ops-grafana-4933.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://ops-grafana-dev-b8840c-dev.apps.gold.devops.gov.bc.ca/*</li><li>https://ops-grafana-dev-b8840c-dev.apps.golddr.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://ops-grafana-test-b8840c-test.apps.gold.devops.gov.bc.ca/*</li><li>https://ops-grafana-test-b8840c-test.apps.golddr.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://ops-grafana-prod-b8840c-prod.apps.gold.devops.gov.bc.ca</li><li>https://ops-grafana-prod-b8840c-prod.apps.golddr.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for aps-ops-grafana-4933

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1261-4935.tf
=> request: add client files for service-account-for-team-1261-4935

terraform-v2/keycloak-dev/standard-clients/bc-stats-coms-bc-box-4936.tf, terraform-v2/keycloak-test/standard-clients/bc-stats-coms-bc-box-4936.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for bc-stats-coms-bc-box-4936

terraform-v2/keycloak-dev/standard-clients/open-school-bc-4937.tf, terraform-v2/keycloak-prod/standard-clients/open-school-bc-4937.tf, terraform-v2/keycloak-test/standard-clients/open-school-bc-4937.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost</li>
</ul>
</details>
=> request: add client files for open-school-bc-4937

terraform-v2/keycloak-dev/standard-clients/test-int-nk-1-4910.tf
=> request: add client files for test-int-nk-1-4910

terraform-v2/keycloak-dev/standard-clients/ministry-of-finance-data-catalogue-4832.tf, terraform-v2/keycloak-prod/standard-clients/ministry-of-finance-data-catalogue-4832.tf, terraform-v2/keycloak-test/standard-clients/ministry-of-finance-data-catalogue-4832.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://mfin-data-catalogue.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://mfin-data-catalogue.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for ministry-of-finance-data-catalogue-4832

terraform-v2/keycloak-dev/standard-clients/drive-bc-4941.tf, terraform-v2/keycloak-test/standard-clients/drive-bc-4941.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8000/*</li><li>https://drivebc-backend-c59ecc-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://drivebc-backend-c59ecc-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for drive-bc-4941

terraform-v2/keycloak-dev/standard-clients/bc-stats-co-ms-4938.tf, terraform-v2/keycloak-prod/standard-clients/bc-stats-co-ms-4938.tf, terraform-v2/keycloak-test/standard-clients/bc-stats-co-ms-4938.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://coms-df9936-dev.apps.silver.devops.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for bc-stats-co-ms-4938

terraform-v2/keycloak-dev/standard-clients/test-project-july-26-4942.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000</li>
</ul>
</details>
=> request: add client files for test-project-july-26-4942

terraform-v2/keycloak-dev/standard-clients/dmft-4580.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.common-sso.justice.gov.bc.ca/auth/realms/IDIR/broker/idir/endpoint</li>
</ul>
</details>
=> request: add client files for dmft-4580

terraform-v2/keycloak-dev/standard-clients/epd-digital-services-4945.tf, terraform-v2/keycloak-prod/standard-clients/epd-digital-services-4945.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://epd-keycloak-prod.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/idir/endpoint</li>
</ul>
</details>
=> request: add client files for epd-digital-services-4945

terraform-v2/keycloak-dev/standard-clients/epd-digital-services-4946.tf, terraform-v2/keycloak-prod/standard-clients/epd-digital-services-4946.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://epd-keycloak-prod.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/bceid/endpoint</li>
</ul>
</details>
=> request: add client files for epd-digital-services-4946

terraform-v2/keycloak-dev/standard-clients/met-gdx-4948.tf, terraform-v2/keycloak-prod/standard-clients/met-gdx-4948.tf, terraform-v2/keycloak-test/standard-clients/met-gdx-4948.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://met-oidc-dev.apps.gold.devops.gov.bc.ca/auth/realms/met/broker/idir/endpoint/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://met-oidc-test.apps.gold.devops.gov.bc.ca/auth/realms/met/broker/idir/endpoint/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://met-oidc.apps.gold.devops.gov.bc.ca/auth/realms/met/broker/idir/endpoint</li>
</ul>
</details>
=> request: add client files for met-gdx-4948

terraform-v2/keycloak-dev/standard-clients/tians-testing-8-1-terraform-run-4949.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-8-1-terraform-run-4949.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-8-1-terraform-run-4949

terraform-v2/keycloak-dev/standard-clients/bcat-standard-4952.tf, terraform-v2/keycloak-prod/standard-clients/bcat-standard-4952.tf, terraform-v2/keycloak-test/standard-clients/bcat-standard-4952.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for bcat-standard-4952

terraform-v2/keycloak-dev/standard-clients/tians-testing-8-4-email-flow-4954.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-8-4-email-flow-4954.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-8-4-email-flow-4954.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-8-4-email-flow-4954

terraform-v2/keycloak-dev/standard-clients/tians-testing-8-4-email-flow-2-4955.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-8-4-email-flow-2-4955.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-8-4-email-flow-2-4955.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-8-4-email-flow-2-4955

terraform-v2/keycloak-dev/standard-clients/chefs-back-end-4957.tf
=> request: add client files for chefs-back-end-4957

terraform-v2/keycloak-dev/standard-clients/chefs-front-end-4958.tf
=> request: add client files for chefs-front-end-4958

terraform-v2/keycloak-dev/standard-clients/chefs-back-end-w-browser-4959.tf
=> request: add client files for chefs-back-end-w-browser-4959

terraform-v2/keycloak-dev/standard-clients/digital-talent-hms-app-4960.tf
=> request: add client files for digital-talent-hms-app-4960

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1365-4961.tf
=> request: add client files for service-account-for-team-1365-4961

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1552-4984.tf
=> request: add client files for service-account-for-team-1552-4984

terraform-v2/keycloak-dev/standard-clients/citz-imb-august-hack-4988.tf
=> request: add client files for citz-imb-august-hack-4988

terraform-v2/keycloak-dev/standard-clients/gdx-postgres-authentication-4989.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://0.0.0.0/*</li>
</ul>
</details>
=> request: add client files for gdx-postgres-authentication-4989

terraform-v2/keycloak-dev/standard-clients/test-ea-4992.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8081/*</li>
</ul>
</details>
=> request: add client files for test-ea-4992

terraform-v2/keycloak-dev/standard-clients/conf-brw-lgn-nk-4996.tf
=> request: add client files for conf-brw-lgn-nk-4996

terraform-v2/keycloak-dev/standard-clients/chefs-localhost-5000.tf
=> request: add client files for chefs-localhost-5000

terraform-v2/keycloak-dev/standard-clients/visitz-confidential-5001.tf
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://socialsector-sso-dev.apps.gov.bc.ca/realms/mcfd/broker/azureidir/endpoint</li>
</ul>
</details>
=> request: add client files for visitz-confidential-5001

terraform-v2/keycloak-dev/standard-clients/machine-learning-for-sdd-5002.tf
=> request: add client files for machine-learning-for-sdd-5002

terraform-v2/keycloak-dev/standard-clients/team-based-care-manager-4998.tf, terraform-v2/keycloak-test/standard-clients/team-based-care-manager-4998.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.tbcm.freshworks.club/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.tbcm.freshworks.club/</li>
</ul>
</details>
=> request: add client files for team-based-care-manager-4998

terraform-v2/keycloak-dev/standard-clients/tbs-management-5003.tf, terraform-v2/keycloak-test/standard-clients/tbs-management-5003.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://cdss.powerappsportals.com/signin-openid_1</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://cdss.powerappsportals.com/signin-openid_1</li>
</ul>
</details>
=> request: add client files for tbs-management-5003

terraform-v2/keycloak-dev/standard-clients/che-fs-local-5004.tf
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>http://localhost:8080</li><li>http://localhost:8081</li><li>http://localhost:8082</li>
</ul>
</details>
=> request: add client files for che-fs-local-5004

terraform-v2/keycloak-dev/standard-clients/tians-testing-9-13-post-release-testing-5006.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-9-13-post-release-testing-5006.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-9-13-post-release-testing-5006

terraform-v2/keycloak-dev/standard-clients/test-rs-5009.tf
=> request: add client files for test-rs-5009

terraform-v2/keycloak-dev/standard-clients/gdx-met-fider-5011.tf, terraform-v2/keycloak-prod/standard-clients/gdx-met-fider-5011.tf, terraform-v2/keycloak-test/standard-clients/gdx-met-fider-5011.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:8888/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://met-fider-test.apps.gold.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://met-fider.apps.gold.devops.gov.bc.ca/</li>
</ul>
</details>
=> request: add client files for gdx-met-fider-5011

terraform-v2/keycloak-dev/standard-clients/gdx-browserstack-5012.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://www.browserstack.com/</li>
</ul>
</details>
=> request: add client files for gdx-browserstack-5012

terraform-v2/keycloak-dev/standard-clients/tians-testing-9-26-5014.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-9-26-5014.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-9-26-5014

terraform-v2/keycloak-dev/standard-clients/conn-ccbc-portal-service-account-5015.tf, terraform-v2/keycloak-prod/standard-clients/conn-ccbc-portal-service-account-5015.tf, terraform-v2/keycloak-test/standard-clients/conn-ccbc-portal-service-account-5015.tf
=> request: add client files for conn-ccbc-portal-service-account-5015

terraform-v2/keycloak-dev/standard-clients/mcfd-ml-poc-4-icm-5050.tf
=> request: add client files for mcfd-ml-poc-4-icm-5050

terraform-v2/keycloak-dev/standard-clients/spd-licensing-portal-5051.tf, terraform-v2/keycloak-test/standard-clients/spd-licensing-portal-5051.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:4200/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://spd-licensing-portal-test.apps.emerald.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for spd-licensing-portal-5051

terraform-v2/keycloak-dev/standard-clients/rsbc-digital-forms-test-sso-5052.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev.jag.gov.bc.ca</li><li>https://dev.jag.gov.bc.ca/roadside-forms</li>
</ul>
</details>
=> request: add client files for rsbc-digital-forms-test-sso-5052

terraform-v2/keycloak-dev/standard-clients/bc-box-5054.tf
=> request: add client files for bc-box-5054

terraform-v2/keycloak-dev/standard-clients/gdx-modern-engagement-tools-5083.tf
=> request: add client files for gdx-modern-engagement-tools-5083

terraform-v2/keycloak-dev/standard-clients/url-shortener-5087.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://gdx-analytics-url-shortener-c6d33e-dev.apps.silver.devops.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for url-shortener-5087

terraform-v2/keycloak-dev/standard-clients/ecc-ecer-5116.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:5094/*</li>
</ul>
</details>
=> request: add client files for ecc-ecer-5116

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1618-5117.tf
=> request: add client files for service-account-for-team-1618-5117

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1618-5117.tf
=> request: delete client files for service-account-for-team-1618-5117

terraform-v2/keycloak-dev/standard-clients/psa-job-store-app-5123.tf, terraform-v2/keycloak-test/standard-clients/psa-job-store-app-5123.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://pjs-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://pjs-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for psa-job-store-app-5123

terraform-v2/keycloak-dev/standard-clients/psa-job-store-api-5124.tf, terraform-v2/keycloak-test/standard-clients/psa-job-store-api-5124.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://pjs-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://pjs-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for psa-job-store-api-5124

terraform-v2/keycloak-dev/standard-clients/nsrm-5131.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:3000/*</li>
</ul>
</details>
=> request: add client files for nsrm-5131

terraform-v2/keycloak-dev/standard-clients/saw-sx-5132.tf, terraform-v2/keycloak-prod/standard-clients/saw-sx-5132.tf, terraform-v2/keycloak-test/standard-clients/saw-sx-5132.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://10.0.0.41:3000/*</li><li>http://127.0.0.1:3000/*</li><li>http://localhost:3000/*</li><li>https://dev-awp.th.gov.bc.ca/*</li><li>https://dev-sawsx-hangfire.apps.silver.devops.gov.bc.ca/*</li><li>https://dev-sawsx-hangfire.apps.silver.devops.gov.bc.ca/*</li><li>https://dev-sawsx.apps.silver.devops.gov.bc.ca/*</li><li>https://localhost:44317/*</li><li>https://localhost:44374/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test-sawsx-hangfire.apps.silver.devops.gov.bc.ca/*</li><li>https://test-sawsx.apps.silver.devops.gov.bc.ca/*</li><li>https://tst-awp.th.gov.bc.ca/*</li><li>https://uat-awp.th.gov.bc.ca/*</li><li>https://uat-sawsx-hangfire.app …
=> request: add client files for saw-sx-5132

terraform-v2/keycloak-dev/standard-clients/mds-tools-5133.tf, terraform-v2/keycloak-test/standard-clients/mds-tools-5133.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://kibana-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://kibana-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for mds-tools-5133

terraform-v2/keycloak-dev/standard-clients/cvcom-5134.tf, terraform-v2/keycloak-prod/standard-clients/cvcom-5134.tf, terraform-v2/keycloak-test/standard-clients/cvcom-5134.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev-cvcom-proxied.th.gov.bc.ca/</li><li>https://dev-cvcom-proxied.th.gov.bc.ca/*</li><li>https://dev-cvcom.th.gov.bc.ca/</li><li>https://dev-cvcom.th.gov.bc.ca/*</li><li>https://localhost:44328/</li><li>https://localhost:44328/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://ect-cvcom.th.gov.bc.ca/</li><li>https://ect-cvcom.th.gov.bc.ca/*</li><li>https://localhost:44328/</li><li>https://localhost:44328/*</li><li>https://tst-cvcom.th.gov.bc.ca/</li><li>https://tst-cvcom.th.gov.bc.ca/*</li><li>https://uat-cvcom.th.gov.bc.ca/</li><li>https://uat-cvcom.th.gov.bc.ca/*</li>
</ul>
</details>
<details> …
=> request: add client files for cvcom-5134

terraform-v2/keycloak-dev/standard-clients/cvcom-dev-5135.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://dev-cvcom-proxied.th.gov.bc.ca/</li><li>https://dev-cvcom-proxied.th.gov.bc.ca/*</li><li>https://dev-cvcom.th.gov.bc.ca/</li><li>https://dev-cvcom.th.gov.bc.ca/*</li><li>https://localhost:44328/</li><li>https://localhost:44328/*</li><li>https://tst-cvcom-proxied.th.gov.bc.ca/</li><li>https://tst-cvcom-proxied.th.gov.bc.ca/*</li><li>https://tst-cvcom.th.gov.bc.ca/</li><li>https://tst-cvcom.th.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for cvcom-dev-5135

terraform-v2/keycloak-dev/standard-clients/nr-permitting-navigator-service-local-5136.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://127.0.0.1/oidc/callback</li><li>http://127.0.0.1/oidc/logout</li><li>http://127.0.0.1:5173/oidc/callback</li><li>http://127.0.0.1:5173/oidc/logout</li><li>http://127.0.0.1:8080/oidc/callback</li><li>http://127.0.0.1:8080/oidc/logout</li><li>http://127.0.0.1:8081/oidc/callback</li><li>http://127.0.0.1:8081/oidc/logout</li><li>http://localhost/oidc/callback</li><li>http://localhost/oidc/logout</li><li>http://localhost:5173/oidc/callback</li><li>http://localhost:5173/oidc/logout</li><li>http://localhost:8080/oidc/callback</li><li>http://localhost:8080/oidc/logout</li><li>http://localhost:8081/oidc/callback</li><li>http://localhost:8081/oidc/logout</li>
</ul>
</details>
=> request: add client files for nr-permitting-navigator-service-local-5136

terraform-v2/keycloak-dev/standard-clients/nr-permitting-navigator-service-local-5138.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://127.0.0.1/oidc/callback</li><li>http://127.0.0.1/oidc/logout</li><li>http://127.0.0.1:5173/oidc/callback</li><li>http://127.0.0.1:5173/oidc/logout</li><li>http://127.0.0.1:8080/oidc/callback</li><li>http://127.0.0.1:8080/oidc/logout</li><li>http://127.0.0.1:8081/oidc/callback</li><li>http://127.0.0.1:8081/oidc/logout</li><li>http://localhost/oidc/callback</li><li>http://localhost/oidc/logout</li><li>http://localhost:5173/oidc/callback</li><li>http://localhost:5173/oidc/logout</li><li>http://localhost:8080/oidc/callback</li><li>http://localhost:8080/oidc/logout</li><li>http://localhost:8081/oidc/callback</li><li>http://localhost:8081/oidc/logout</li>
</ul>
</details>
=> request: add client files for nr-permitting-navigator-service-local-5138

terraform-v2/keycloak-dev/standard-clients/nr-permitting-navigator-service-5139.tf, terraform-v2/keycloak-prod/standard-clients/nr-permitting-navigator-service-5139.tf, terraform-v2/keycloak-test/standard-clients/nr-permitting-navigator-service-5139.tf
=> request: add client files for nr-permitting-navigator-service-5139

terraform-v2/keycloak-dev/standard-clients/dss-mapping-services-5140.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://awstats-dlvr.apps.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for dss-mapping-services-5140

terraform-v2/keycloak-dev/standard-clients/azure-registries-idp-5141.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://*</li>
</ul>
</details>
=> request: add client files for azure-registries-idp-5141

terraform-v2/keycloak-dev/standard-clients/test-realm-app-nk-5142.tf
=> request: add client files for test-realm-app-nk-5142

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1621-5143.tf
=> request: add client files for service-account-for-team-1621-5143

terraform-v2/keycloak-dev/standard-clients/nr-data-access-5146.tf
=> request: add client files for nr-data-access-5146

terraform-v2/keycloak-dev/standard-clients/low-carbon-fuel-standard-5147.tf, terraform-v2/keycloak-test/standard-clients/low-carbon-fuel-standard-5147.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>https://lcfs-dev.apps.silver.devops.gov.bc.ca/*</li><li>https://logontest7.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://lcfs-test.apps.silver.devops.gov.bc.ca/*</li><li>https://logontest7.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for low-carbon-fuel-standard-5147

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1623-5148.tf
=> request: add client files for service-account-for-team-1623-5148

terraform-v2/keycloak-dev/standard-clients/test-project-5149.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:3000/*</li>
</ul>
</details>
=> request: add client files for test-project-5149

terraform-v2/keycloak-dev/standard-clients/ecc-ecer-registry-portal-5152.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:5121/*</li><li>https://dev-ecer-registry-portal.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for ecc-ecer-registry-portal-5152

terraform-v2/keycloak-dev/standard-clients/nert-5153.tf, terraform-v2/keycloak-test/standard-clients/nert-5153.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for nert-5153

terraform-v2/keycloak-dev/standard-clients/tians-testing-12-04-testing-5155.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-12-04-testing-5155.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-12-04-testing-5155.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-12-04-testing-5155

terraform-v2/keycloak-dev/standard-clients/tians-testing-12-05-post-release-5160.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-12-05-post-release-5160.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-12-05-post-release-5160.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
=> request: add client files for tians-testing-12-05-post-release-5160

terraform-v2/keycloak-dev/standard-clients/tians-testing-12-05-service-account-5161.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-12-05-service-account-5161.tf
=> request: add client files for tians-testing-12-05-service-account-5161

terraform-v2/keycloak-dev/standard-clients/bl-conf-idir-azure-nk-5164.tf, terraform-v2/keycloak-prod/standard-clients/bl-conf-idir-azure-nk-5164.tf, terraform-v2/keycloak-test/standard-clients/bl-conf-idir-azure-nk-5164.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://oidcdebuggger-c6af30-dev.apps.gold.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://oidcdebuggger-c6af30-dev.apps.gold.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://oidcdebuggger-c6af30-dev.apps.gold.devops.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for bl-conf-idir-azure-nk-5164

terraform-v2/keycloak-dev/standard-clients/test-marco-5165.tf
=> request: add client files for test-marco-5165

terraform-v2/keycloak-dev/standard-clients/chefs-testing-5183.tf
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>http://localhost:8080</li><li>http://localhost:8081</li><li>http://localhost:8082</li>
</ul>
</details>
=> request: add client files for chefs-testing-5183

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-265-5184.tf
=> request: add client files for service-account-for-team-265-5184

terraform-v2/keycloak-dev/standard-clients/digital-building-permit-5120.tf
=> request: add client files for digital-building-permit-5120

terraform-v2/keycloak-dev/standard-clients/one-bc-portal-5185.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://walletsignin.powerappsportals.com/signin-openid_1</li>
</ul>
</details>
=> request: add client files for one-bc-portal-5185

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1028-5186.tf
=> request: add client files for service-account-for-team-1028-5186

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1554-5187.tf
=> request: add client files for service-account-for-team-1554-5187

terraform-v2-custom/keycloak-dev/custom-realms/digitaltrust-nrm.tf, terraform-v2-custom/keycloak-prod/custom-realms/digitaltrust-nrm.tf, terraform-v2-custom/keycloak-test/custom-realms/digitaltrust-nrm.tf
disabled through request disabled at realm registry for a custom realm digitaltrust-nrm
=> feat: disable custom realm digitaltrust-nrm

terraform-v2/keycloak-dev/standard-clients/nr-permit-connect-navigator-service-5188.tf, terraform-v2/keycloak-prod/standard-clients/nr-permit-connect-navigator-service-5188.tf, terraform-v2/keycloak-test/standard-clients/nr-permit-connect-navigator-service-5188.tf
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://pcns-dev-master.apps.silver.devops.gov.bc.ca/oidc/callback</li><li>https://pcns-dev-master.apps.silver.devops.gov.bc.ca/oidc/logout</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://pcns-test-master.apps.silver.devops.gov.bc.ca/oidc/callback</li><li>https://pcns-test-master.apps.silver.devops.gov.bc.ca/oidc/logout</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://pcns-prod-master.apps.silver.devops.gov.bc.ca/oidc/callback</li><li>https://pcns-prod-master.apps.silver.devops.gov.bc.ca/oidc/logout</li>
</ul>
</details>
=> request: add client files for nr-permit-connect-navigator-service-5188

terraform-v2/keycloak-dev/standard-clients/property-inventory-management-system-5189.tf, terraform-v2/keycloak-prod/standard-clients/property-inventory-management-system-5189.tf, terraform-v2/keycloak-test/standard-clients/property-inventory-management-system-5189.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost*</li><li>https://pims-dev.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://pims-test.apps.silver.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://pims.gov.bc.ca/*</li>
</ul>
</details>
=> request: add client files for property-inventory-management-system-5189

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1620-5191.tf
=> request: add client files for service-account-for-team-1620-5191

terraform-v2/keycloak-dev/standard-clients/tians-testing-1-4-submitted-deleted-5192.tf
=> request: add client files for tians-testing-1-4-submitted-deleted-5192

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-764-5193.tf
=> request: add client files for service-account-for-team-764-5193

terraform-v2/keycloak-dev/standard-clients/mds-core-api-internal-5194.tf, terraform-v2/keycloak-prod/standard-clients/mds-core-api-internal-5194.tf, terraform-v2/keycloak-test/standard-clients/mds-core-api-internal-5194.tf
=> request: add client files for mds-core-api-internal-5194

terraform-v2/keycloak-dev/standard-clients/sdpr-amp-doolittle-5190.tf, terraform-v2/keycloak-prod/standard-clients/sdpr-amp-doolittle-5190.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://knowledge.social.gov.bc.ca</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://knowledge.social.gov.bc.ca</li>
</ul>
</details>
=> request: add client files for sdpr-amp-doolittle-5190

terraform-v2/keycloak-dev/standard-clients/ecc-ecer-automation-5215.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:5121/*</li>
</ul>
</details>
=> request: add client files for ecc-ecer-automation-5215

terraform-v2/keycloak-dev/standard-clients/ece-ecr-test-automation-5216.tf
=> request: add client files for ece-ecr-test-automation-5216

terraform-v2/keycloak-dev/standard-clients/annual-fisheries-production-schedule-5218.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://submit.digital.gov.bc.ca/app/form/submit?f=4b6caefe-298c-4da0-8925-99c15b8c3a7f</li>
</ul>
</details>
=> request: add client files for annual-fisheries-production-schedule-5218

terraform-v2-custom/keycloak-dev/custom-realms/tian-20240119-test.tf, terraform-v2-custom/keycloak-prod/custom-realms/tian-20240119-test.tf, terraform-v2-custom/keycloak-test/custom-realms/tian-20240119-test.tf
created through request created at realm registry for a custom realm tian-20240119-test
=> feat: create custom realm tian-20240119-test

terraform-v2-custom/keycloak-dev/custom-realms/childcare-applications.tf, terraform-v2-custom/keycloak-prod/custom-realms/childcare-applications.tf, terraform-v2-custom/keycloak-test/custom-realms/childcare-applications.tf
created through request created at realm registry for a custom realm childcare-applications
=> feat: create custom realm childcare-applications

terraform-v2/keycloak-dev/main.tf, terraform-v2/keycloak-prod/main.tf, terraform-v2/keycloak-test/main.tf
Change azure idir to idir - mfa in master realm
=> chore: update idir display name

terraform-v2-custom/keycloak-dev/custom-realms/strdss.tf, terraform-v2-custom/keycloak-prod/custom-realms/strdss.tf, terraform-v2-custom/keycloak-test/custom-realms/strdss.tf
created through request created at realm registry for a custom realm strdss
=> feat: create custom realm strdss

terraform-v2/keycloak-dev/main.tf, terraform-v2/keycloak-prod/main.tf, terraform-v2/keycloak-test/main.tf
update terraform for new dc setup
=> chore: dc setup

terraform-v2/keycloak-dev/main.tf, terraform-v2/keycloak-prod/main.tf, terraform-v2/keycloak-test/main.tf
=> fix: var reference

terraform-v2-custom/keycloak-dev/custom-realms/tian-20240119-test.tf, terraform-v2-custom/keycloak-prod/custom-realms/tian-20240119-test.tf, terraform-v2-custom/keycloak-test/custom-realms/tian-20240119-test.tf
disabled through request disabled at realm registry for a custom realm tian-20240119-test
=> feat: disable custom realm tian-20240119-test

.github/workflows/terraform-v2-apply.yml
add vars needed for apply, merge before May 29 application
=> chore: vars

terraform-v2-custom/keycloak-dev/custom-realms/mmi.tf, terraform-v2-custom/keycloak-prod/custom-realms/mmi.tf, terraform-v2-custom/keycloak-test/custom-realms/mmi.tf
created through request created at realm registry for a custom realm mmi
=> feat: create custom realm mmi

terraform-v2-custom/keycloak-dev/custom-realms/finance.tf, terraform-v2-custom/keycloak-prod/custom-realms/finance.tf, terraform-v2-custom/keycloak-test/custom-realms/finance.tf
created through request created at realm registry for a custom realm finance
=> feat: create custom realm finance

terraform-v2-custom/keycloak-dev/custom-realms/conservation.tf, terraform-v2-custom/keycloak-prod/custom-realms/conservation.tf, terraform-v2-custom/keycloak-test/custom-realms/conservation.tf
created through request created at realm registry for a custom realm conservation
=> feat: create custom realm conservation

terraform-modules/localdev/podman-compose.yaml, terraform-modules/localdev/variables.tf, terraform-modules/modules/base-realms/realm-standard/idp-azureidir.tf, terraform-modules/modules/base-realms/realm-standard/idp-verifiablecredential.tf
- remove tooltips from idir-mfa and digital credential
- Set default credentials for local development to match the podman-compose creds
=> chore: tooltips
