.github/workflows/e2e-test.yml, examples/next-app/.gitignore, examples/next-app/cypress.json, examples/next-app/cypress/integration/actions.spec.js, scripts/e2e-prep.js
- replace GitHub IDP with another Keycloak IDP
=> feat: use keycloak idp to test idp mapper

terraform/keycloak-dev/realms/onestopauth-basic/client-testclient-request1.tf, terraform/keycloak-prod/realms/onestopauth-basic/client-testclient-request1.tf
=> feat: add a test request client

terraform/keycloak-dev/realms/onestopauth/client-work-bc-teacher-resources.tf
- update redirect URL from
from http://teacher-resources-bdaa18-dev.apps.silver.devops.gov.bc.ca/
to http://teacher-resources-bdaa18-dev.apps.silver.devops.gov.bc.ca/openid-connect/keycloak
=> feat: update redirect url for client 'work-bc-teacher-resources'

terraform/keycloak-dev/realms/onestopauth-basic/client-dds-portfolio.tf
- add a new client for 'dds-portfolio' in dev environment
=> feat: add a new client for 'dds-portfolio' in dev environment

.github/workflows/request.yml, package.json, scripts/generate-clients.js, scripts/github-script.js, yarn.lock
- add a `workflow_dispatch` GitHub action to trigger request workflow in GitHub pipelines.
=> feat: add request ci pipeline

terraform/keycloak-dev/realms/onestopauth-business/client-hets.tf, terraform/keycloak-test/realms/onestopauth-business/client-hets.tf
- add `/*` at the end of the redirect URIs as @ychung-mot requested.
=> chore: add '/*' for redirect urls

.github/workflows/e2e-test.yml, .github/workflows/terraform.yml, package.json
update name and default branch to follow conventions
=> chore: update name

terraform/keycloak-dev/realms/onestopauth/client-sso-test-2-2.tf, terraform/keycloak-prod/realms/onestopauth/client-sso-test-2-2.tf, terraform/keycloak-test/realms/onestopauth/client-sso-test-2-2.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost</li></ul>```
</details>
=> request: add client files for sso-test-2-2

terraform/keycloak-dev/realms/onestopauth/client-taft-133.tf, terraform/keycloak-prod/realms/onestopauth/client-taft-133.tf, terraform/keycloak-test/realms/onestopauth/client-taft-133.tf
```<ul>✔️Valid Redirect Urls<li>https://idm-dev-taft.apps.silver.devops.gov.bc.ca/auth/realms/taft/broker/idir/endpoint</li>,<li>https://localhost:8080/auth/realms/taft/broker/idir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://idm-test-taft.apps.silver.devops.gov.bc.ca/auth/realms/taft/broker/idir/endpoint</li>,<li>https://localhost:8080/auth/realms/taft/broker/idir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://idm-prod-taft.apps.silver.devops.gov.bc.ca/auth/realms/taft/broker/idir/endpoint</li></ul>```
</details>
=> request: add client files for taft-133

terraform/keycloak-dev/realms/onestopauth/client-jon-test-1-67.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-1-67.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-1-67.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-1-67

terraform/keycloak-dev/realms/onestopauth/client-csb-secure-file-transfer-232.tf, terraform/keycloak-prod/realms/onestopauth/client-csb-secure-file-transfer-232.tf, terraform/keycloak-test/realms/onestopauth/client-csb-secure-file-transfer-232.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.jag.gov.bc.ca/csb-sft</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.jag.gov.bc.ca/csb-sft</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://jag.gov.bc.ca/csb-sft</li></ul>```
</details>
=> request: add client files for csb-secure-file-transfer-232

terraform/keycloak-dev/realms/onestopauth/client-csb-secure-file-transfer-232.tf, terraform/keycloak-prod/realms/onestopauth/client-csb-secure-file-transfer-232.tf, terraform/keycloak-test/realms/onestopauth/client-csb-secure-file-transfer-232.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.jag.gov.bc.ca/ocj-sft</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.jag.gov.bc.ca/ocj-sft</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://jag.gov.bc.ca/ocj-sft</li></ul>```
</details>
=> request: update client files for csb-secure-file-transfer-232

terraform/keycloak-dev/realms/onestopauth/client-trevor-test-397.tf, terraform/keycloak-prod/realms/onestopauth/client-trevor-test-397.tf, terraform/keycloak-test/realms/onestopauth/client-trevor-test-397.tf
```<ul>✔️Valid Redirect Urls<li>https://fmdbd.hlth.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://fmdbt.hlth.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://fmdb.hlth.gov.bc.ca</li></ul>```
</details>
=> request: add client files for trevor-test-397

terraform/keycloak-dev/realms/onestopauth/client-work-bc-teacher-resources-496.tf, terraform/keycloak-prod/realms/onestopauth/client-work-bc-teacher-resources-496.tf, terraform/keycloak-test/realms/onestopauth/client-work-bc-teacher-resources-496.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-admin-jobboard.workbc.ca/*</li>,<li>https://localhost:44364/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test-admin-jobboard.workbc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://admin-jobboard.workbc.ca/*</li></ul>```
</details>
=> request: add client files for work-bc-teacher-resources-496

terraform/keycloak-dev/realms/onestopauth/client-work-bc-job-board-496.tf, terraform/keycloak-prod/realms/onestopauth/client-work-bc-job-board-496.tf, terraform/keycloak-test/realms/onestopauth/client-work-bc-job-board-496.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-admin-jobboard.workbc.ca/*</li>,<li>https://localhost:44364/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test-admin-jobboard.workbc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://admin-jobboard.workbc.ca/*</li></ul>```
</details>
=> request: add client files for work-bc-job-board-496

terraform/keycloak-dev/realms/onestopauth-business/client-roadsafety-digital-forms.tf, terraform/keycloak-test/realms/onestopauth-business/client-roadsafety-digital-forms.tf
add client for road safety to onestopauth-business
=> feat: add client

terraform/keycloak-dev/realms/onestopauth-business/client-roadsafety-digital-forms.tf, terraform/keycloak-test/realms/onestopauth-business/client-roadsafety-digital-forms.tf
=> chore: update

.github/workflows/terraform-apply.yml
update action to match dev version
=> chore: update action

terraform/keycloak-dev/realms/onestopauth/client-sprint-demo-562.tf, terraform/keycloak-prod/realms/onestopauth/client-sprint-demo-562.tf, terraform/keycloak-test/realms/onestopauth/client-sprint-demo-562.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for sprint-demo-562

terraform/keycloak-dev/realms/onestopauth/client-sso-examples-confidential-563.tf, terraform/keycloak-prod/realms/onestopauth/client-sso-examples-confidential-563.tf, terraform/keycloak-test/realms/onestopauth/client-sso-examples-confidential-563.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li>,<li>http://localhost:3000/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for sso-examples-confidential-563

terraform/keycloak-prod/realms/onestopauth-business/client.hets.tf
=> chore: add prod

terraform/keycloak-dev/realms/onestopauth/client-clean-transportation-data-hub-595.tf, terraform/keycloak-prod/realms/onestopauth/client-clean-transportation-data-hub-595.tf, terraform/keycloak-test/realms/onestopauth/client-clean-transportation-data-hub-595.tf
```<ul>✔️Valid Redirect Urls<li>https://cthub-dev.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cthub-test.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cthub-prod.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for clean-transportation-data-hub-595

terraform/keycloak-dev/realms/onestopauth/client-front-counter-bc-fider-661.tf, terraform/keycloak-prod/realms/onestopauth/client-front-counter-bc-fider-661.tf, terraform/keycloak-test/realms/onestopauth/client-front-counter-bc-fider-661.tf
```<ul>✔️Valid Redirect Urls<li>https://fcbcfiderdev.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://fcbc-fider.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://fcbcfider.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: update client files for front-counter-bc-fider-661

terraform/keycloak-dev/realms/onestopauth/client-grad-793.tf, terraform/keycloak-prod/realms/onestopauth/client-grad-793.tf, terraform/keycloak-test/realms/onestopauth/client-grad-793.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for grad-793

terraform/keycloak-dev/realms/onestopauth/client-grad-826.tf, terraform/keycloak-prod/realms/onestopauth/client-grad-826.tf, terraform/keycloak-test/realms/onestopauth/client-grad-826.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for grad-826

terraform/keycloak-dev/realms/onestopauth/client-cloud-pathfinder-aws-zl-0-893.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:5000</li></ul>```
</details>
=> request: add client files for cloud-pathfinder-aws-zl-0-893

terraform/keycloak-dev/realms/onestopauth-basic/client-some-other-project-894.tf
```<ul>✔️Valid Redirect Urls<li>https://someotherproject.com</li></ul>```
</details>
=> request: add client files for some-other-project-894

terraform/keycloak-dev/realms/onestopauth-basic/client-some-other-project-894.tf
=> request: delete client files for some-other-project-894

terraform/keycloak-dev/realms/onestopauth/client-cloud-pathfinder-aws-zl-0-893.tf
=> request: delete client files for cloud-pathfinder-aws-zl-0-893

terraform/keycloak-dev/realms/onestopauth-both/client-ux-testing-session-2021-11-03-925.tf, terraform/keycloak-test/realms/onestopauth-both/client-ux-testing-session-2021-11-03-925.tf
```<ul>✔️Valid Redirect Urls<li>https://somefancycatpalace.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://manateedriveintheatre.gov.bc.ca</li></ul>```
</details>
=> request: add client files for ux-testing-session-2021-11-03-925

terraform/keycloak-dev/realms/onestopauth-both/client-ux-testing-session-2021-11-03-925.tf, terraform/keycloak-test/realms/onestopauth-both/client-ux-testing-session-2021-11-03-925.tf
```<ul>✔️Valid Redirect Urls<li>https://somefancycatpalace.gov.bc.ca</li>,<li>https://somefancycatpalace2.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://manateedriveintheatre.gov.bc.ca</li></ul>```
</details>
=> request: update client files for ux-testing-session-2021-11-03-925

terraform/keycloak-dev/realms/onestopauth/client-test-958.tf
```<ul>✔️Valid Redirect Urls<li>https://ww</li></ul>```
</details>
=> request: add client files for test-958

terraform/keycloak-dev/realms/onestopauth/client-test-958.tf
=> request: delete client files for test-958

terraform/keycloak-dev/realms/onestopauth-basic/client-jsb-csrs-991.tf, terraform/keycloak-test/realms/onestopauth-basic/client-jsb-csrs-991.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8080</li></ul>```
</details>
=> request: add client files for jsb-csrs-991

terraform/keycloak-dev/realms/onestopauth-basic/client-tti-poc-1025.tf
```<ul>✔️Valid Redirect Urls<li>https://civilresolutionbc--springdev.lightning.force.com/</li></ul>```
</details>
=> request: add client files for tti-poc-1025

terraform/keycloak-dev/realms/onestopauth-basic/client-jsb-csrs-991.tf, terraform/keycloak-test/realms/onestopauth-basic/client-jsb-csrs-991.tf
```<ul>✔️Valid Redirect Urls<li>https://jag-csrs-portal-public-f0b5b6-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://jag-csrs-portal-public-f0b5b6-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: update client files for jsb-csrs-991

terraform/keycloak-dev/realms/onestopauth-basic/client-tti-poc-1025.tf
```<ul>✔️Valid Redirect Urls<li>https://civilresolutionbc--springdev.lightning.force.com/</li>,<li>https://civilresolutionbc--springdev.lightning.force.com/services/authcallback/PathfinderSSO</li></ul>```
</details>
=> request: update client files for tti-poc-1025

terraform/keycloak-dev/realms/onestopauth-basic/client-tti-poc-public-1189.tf
```<ul>✔️Valid Redirect Urls<li>https://civilresolutionbc--springdev.my.salesforce.com/services/authcallback/PathfinderSSO</li></ul>```
</details>
=> request: add client files for tti-poc-public-1189

terraform/keycloak-dev/realms/onestopauth/client-confidential-demo-1222.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li>,<li>http://localhost:3000/*</li></ul>```
</details>
=> request: add client files for confidential-demo-1222

terraform/keycloak-dev/realms/onestopauth/client-dss-kirk-1288.tf, terraform/keycloak-prod/realms/onestopauth/client-dss-kirk-1288.tf, terraform/keycloak-test/realms/onestopauth/client-dss-kirk-1288.tf
```<ul>✔️Valid Redirect Urls<li>https://kirk-d.data.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://kirk-t.data.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://kirk.data.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for dss-kirk-1288

terraform/keycloak-dev/realms/onestopauth-business/client-test-bceid-zorin-1354.tf, terraform/keycloak-test/realms/onestopauth-business/client-test-bceid-zorin-1354.tf
```<ul>✔️Valid Redirect Urls<li>https://DEV</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://Test</li></ul>```
</details>
=> request: add client files for test-bceid-zorin-1354

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-test-1387.tf, terraform/keycloak-test/realms/onestopauth-basic/client-bceid-test-1387.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for bceid-test-1387

terraform/keycloak-dev/realms/onestopauth/client-grad-826.tf, terraform/keycloak-prod/realms/onestopauth/client-grad-826.tf, terraform/keycloak-test/realms/onestopauth/client-grad-826.tf
=> request: delete client files for grad-826

terraform/keycloak-dev/realms/onestopauth/client-tti-ams-1486.tf, terraform/keycloak-test/realms/onestopauth/client-tti-ams-1486.tf
```<ul>✔️Valid Redirect Urls<li>https://bchrt--qa.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://bcmoag--qa.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://bcrb--newqa.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://cabro--qa.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://civilresolutionbc--amsqa.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://lrb--qa.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://mhreviewboard--qa.my.salesforce.com/services/authcallback/PathfinderIdir</li></ul>```
```<ul>✔️Valid Redirect …
```
=> request: add client files for tti-ams-1486

terraform/keycloak-dev/realms/onestopauth/client-css-e-forms-1519.tf
```<ul>✔️Valid Redirect Urls<li>https://web-dev-7d3aa1-dev.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for css-e-forms-1519

terraform/keycloak-dev/realms/onestopauth/client-css-e-forms-poc-1585.tf
```<ul>✔️Valid Redirect Urls<li>https://keycloak-7d3aa1-dev.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
</details>
=> request: add client files for css-e-forms-poc-1585

.github/workflows/request.yml, .github/workflows/terraform-plan.yml
bump up the gh actions version to most recent
=> chore: bump actions

.github/workflows/request.yml, .github/workflows/terraform-plan.yml
=> chore: bump

terraform/keycloak-dev/realms/onestopauth/client-css-e-forms-poc-1585.tf
```<ul>✔️Valid Redirect Urls<li>https://web-dev-7d3aa1-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: update client files for css-e-forms-poc-1585

terraform/keycloak-dev/realms/onestopauth/client-wildlife-health-information-system-1618.tf, terraform/keycloak-prod/realms/onestopauth/client-wildlife-health-information-system-1618.tf, terraform/keycloak-test/realms/onestopauth/client-wildlife-health-information-system-1618.tf
```<ul>✔️Valid Redirect Urls<li>https://moe-whis-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://moe-whis-test.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://wildlifehealth.nrs.gov.bc.ca</li></ul>```
</details>
=> request: add client files for wildlife-health-information-system-1618

terraform/keycloak-dev/realms/onestopauth/client-dss-kirk-1750.tf, terraform/keycloak-prod/realms/onestopauth/client-dss-kirk-1750.tf, terraform/keycloak-test/realms/onestopauth/client-dss-kirk-1750.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8000/*</li>,<li>https://kirk-d.data.gov.bc.ca/*</li>,<li>https://kirk-rt-65d6a6-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://kirk-rt-65d6a6-test.apps.silver.devops.gov.bc.ca/*</li>,<li>https://kirk-t.data.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://kirk-rt-65d6a6-prod.apps.silver.devops.gov.bc.ca/*</li>,<li>https://kirk.data.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for dss-kirk-1750

terraform/keycloak-dev/realms/onestopauth/client-bcea-forecast-1816.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li>,<li>https://meteor-bcea-forecast-d9436d-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for bcea-forecast-1816

terraform/keycloak-dev/realms/onestopauth-business/client-invasives-bc-1849.tf, terraform/keycloak-test/realms/onestopauth-business/client-invasives-bc-1849.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li>,<li>https://dev-invasivesbci.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test-invasivesbci.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for invasives-bc-1849

terraform/keycloak-dev/realms/onestopauth-business/client-invasives-bc-1948.tf, terraform/keycloak-test/realms/onestopauth-business/client-invasives-bc-1948.tf
```<ul>✔️Valid Redirect Urls<li>http://127.0.0.1:3000/home/landing</li>,<li>https://dev-invasivesbci.apps.silver.devops.gov.bc.ca/home/landing</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://127.0.0.1:3000/home/landing</li>,<li>https://test-invasivesbci.apps.silver.devops.gov.bc.ca/home/landing</li></ul>```
</details>
=> request: add client files for invasives-bc-1948

terraform/keycloak-dev/realms/onestopauth/client-sso-requests.tf, terraform/keycloak-prod/realms/onestopauth/client-sso-requests.tf
update uris to allow redirection to sub-pages
=> chore: uris

terraform/keycloak-dev/realms/onestopauth-basic/client-digital-journeys-1981.tf, terraform/keycloak-test/realms/onestopauth-basic/client-digital-journeys-1981.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for digital-journeys-1981

terraform/keycloak-dev/realms/onestopauth-basic/client-connectivity-intake-2014.tf, terraform/keycloak-test/realms/onestopauth-basic/client-connectivity-intake-2014.tf
```<ul>✔️Valid Redirect Urls<li>https://example.com/not/configured/yet</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example.com/not/configured/yet</li></ul>```
</details>
=> request: add client files for connectivity-intake-2014

terraform/keycloak-dev/realms/onestopauth-business/client-awp-2146.tf, terraform/keycloak-test/realms/onestopauth-business/client-awp-2146.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-awp.th.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-awp.th.gov.bc.ca/</li>,<li>https://uat-awp.th.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for awp-2146

.github/workflows/request.yml, .github/workflows/terraform-plan.yml
bump actions version to latest
=> chore: actions

terraform/keycloak-dev/realms/onestopauth/client-bcea-forecast-confidential-2212.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
</details>
=> request: add client files for bcea-forecast-confidential-2212

terraform/keycloak-dev/realms/onestopauth/client-bcea-forecast-confidential-2212.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://meteor-bcea-forecast-d9436d-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: update client files for bcea-forecast-confidential-2212

terraform/keycloak-dev/realms/onestopauth/client-bcea-forecast-2410.tf, terraform/keycloak-prod/realms/onestopauth/client-bcea-forecast-2410.tf, terraform/keycloak-test/realms/onestopauth/client-bcea-forecast-2410.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://bcea-forecast-d9436d-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcea-forecast-d9436d-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li></ul>```
</details>
=> request: add client files for bcea-forecast-2410

terraform/keycloak-dev/realms/onestopauth-business/client-roadsafety-digital-forms-2443.tf
```<ul>✔️Valid Redirect Urls<li>https://rsbc-dh-prohibition-web-app-pr-104.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for roadsafety-digital-forms-2443

terraform/keycloak-dev/realms/onestopauth/client-isd-amp-mining-scan-2509.tf
```<ul>✔️Valid Redirect Urls<li>https://sso.apps-isd.sd.gov.bc.ca/auth/realms/mining/broker/keycloak-oidc/endpoint</li></ul>```
</details>
=> request: add client files for isd-amp-mining-scan-2509

terraform/keycloak-dev/realms/onestopauth/client-sso-gold-2542.tf
```<ul>✔️Valid Redirect Urls<li>https://sso-keycloak-c6af30-dev.apps.gold.devops.gov.bc.ca/auth/realms/onestopauth/broker/idir-silver/endpoint</li></ul>```
</details>
=> request: add client files for sso-gold-2542

terraform/keycloak-dev/realms/onestopauth-basic/client-connectivity-intake-2014.tf, terraform/keycloak-test/realms/onestopauth-basic/client-connectivity-intake-2014.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://connectivity-intake-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://connectivity-intake-test.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: update client files for connectivity-intake-2014

terraform/keycloak-dev/realms/onestopauth/client-psa-digital-journeys-2311.tf, terraform/keycloak-prod/realms/onestopauth/client-psa-digital-journeys-2311.tf, terraform/keycloak-test/realms/onestopauth/client-psa-digital-journeys-2311.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for psa-digital-journeys-2311

terraform/keycloak-dev/realms/onestopauth/client-tidd-trade-industry-development-2575.tf, terraform/keycloak-prod/realms/onestopauth/client-tidd-trade-industry-development-2575.tf, terraform/keycloak-test/realms/onestopauth/client-tidd-trade-industry-development-2575.tf
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc--meldev.my.salesforce.com/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc--test.my.salesforce.com/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc.my.salesforce.com/</li></ul>```
</details>
=> request: add client files for tidd-trade-industry-development-2575

terraform/keycloak-dev/realms/onestopauth/client-sso-gold-2542.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/silveridir/broker/silveridir/endpoint</li>,<li>https://sso-keycloak-c6af30-dev.apps.gold.devops.gov.bc.ca/auth/realms/onestopauth/broker/idir-silver/endpoint</li></ul>```
</details>
=> request: update client files for sso-gold-2542

terraform/keycloak-dev/realms/onestopauth-basic/client-itvr-2674.tf, terraform/keycloak-test/realms/onestopauth-basic/client-itvr-2674.tf
```<ul>✔️Valid Redirect Urls<li>https://itvr-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://itvr-test.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for itvr-2674

terraform/keycloak-dev/realms/onestopauth/client-tidd-salesforce-2707.tf, terraform/keycloak-prod/realms/onestopauth/client-tidd-salesforce-2707.tf, terraform/keycloak-test/realms/onestopauth/client-tidd-salesforce-2707.tf
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc--meldev.my.salesforce.com/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc--test.my.salesforce.com/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc.my.salesforce.com/</li></ul>```
</details>
=> request: add client files for tidd-salesforce-2707

terraform/keycloak-dev/realms/onestopauth-basic/client-psa-moodle-2773.tf, terraform/keycloak-test/realms/onestopauth-basic/client-psa-moodle-2773.tf
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-dev.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-test.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li></ul>```
</details>
=> request: add client files for psa-moodle-2773

terraform/keycloak-dev/realms/onestopauth-basic/client-psa-moodle-2773.tf, terraform/keycloak-test/realms/onestopauth-basic/client-psa-moodle-2773.tf
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-dev.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li>,<li>https://moodle.virtuallearn.ca/admin/oauth2callback.php</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-test.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li></ul>```
</details>
=> request: update client files for psa-moodle-2773

terraform/keycloak-dev/realms/onestopauth-both/client-coms-showcase-2806.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li>,<li>http://localhost:8081</li></ul>```
</details>
=> request: add client files for coms-showcase-2806

terraform/keycloak-dev/realms/onestopauth-both/client-coms-showcase-frontend-localhost-2872.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>http://localhost:8081/*</li></ul>```
</details>
=> request: add client files for coms-showcase-frontend-localhost-2872

terraform/keycloak-dev/realms/onestopauth/client-demo-feb-10-2905.tf, terraform/keycloak-test/realms/onestopauth/client-demo-feb-10-2905.tf
=> request: delete client files for demo-feb-10-2905

terraform/keycloak-dev/realms/onestopauth-both/client-coms-2839.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li>,<li>http://localhost:4000</li></ul>```
</details>
=> request: update client files for coms-2839

terraform/keycloak-dev/realms/onestopauth-both/client-coms-showcase-2806.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
</details>
=> request: update client files for coms-showcase-2806

terraform/keycloak-dev/realms/onestopauth-both/client-greenfield-template-2938.tf
```<ul>✔️Valid Redirect Urls<li>https://tbd</li></ul>```
</details>
=> request: add client files for greenfield-template-2938

terraform/keycloak-dev/realms/onestopauth/client-feb-4-22-2740.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for feb-4-22-2740

terraform/keycloak-dev/realms/onestopauth-both/client-greenfield-template-2938.tf
=> request: delete client files for greenfield-template-2938

terraform/keycloak-dev/realms/onestopauth/client-serve-legal-documents-3070.tf
```<ul>✔️Valid Redirect Urls<li>https://keycloak-a60371-dev.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
</details>
=> request: add client files for serve-legal-documents-3070

terraform/keycloak-dev/realms/onestopauth/client-office-of-the-superintendent-of-prof-governance-3071.tf, terraform/keycloak-prod/realms/onestopauth/client-office-of-the-superintendent-of-prof-governance-3071.tf, terraform/keycloak-test/realms/onestopauth/client-office-of-the-superintendent-of-prof-governance-3071.tf
```<ul>✔️Valid Redirect Urls<li>https://keycloak-e63731-dev.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://keycloak-e63731-test.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://keycloak-e63731-prod.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
</details>
=> request: add client files for office-of-the-superintendent-of-prof-governance-3071

terraform/keycloak-dev/realms/onestopauth-business/client-api-programme-services-3103.tf
```<ul>✔️Valid Redirect Urls<li>https://authz-apps-gov-bc-ca.dev.api.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for api-programme-services-3103

terraform/keycloak-dev/realms/onestopauth/client-court-nextcloud-project-232.tf, terraform/keycloak-prod/realms/onestopauth/client-court-nextcloud-project-232.tf, terraform/keycloak-test/realms/onestopauth/client-court-nextcloud-project-232.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.jag.gov.bc.ca/court-nextcloud/</li>,<li>https://dev.jag.gov.bc.ca/court-nextcloud/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.jag.gov.bc.ca/court-nextcloud/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://jag.gov.bc.ca/court-nextcloud/*</li></ul>```
</details>
=> request: add client files for court-nextcloud-project-232

terraform/keycloak-dev/realms/onestopauth/client-work-bc-career-compass-3136.tf, terraform/keycloak-prod/realms/onestopauth/client-work-bc-career-compass-3136.tf, terraform/keycloak-test/realms/onestopauth/client-work-bc-career-compass-3136.tf
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes-dev/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes-test/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes/openid-connect/keycloak</li></ul>```
</details>
=> request: add client files for work-bc-career-compass-3136

terraform/keycloak-dev/realms/onestopauth/client-tidd-salesforce-2707.tf, terraform/keycloak-prod/realms/onestopauth/client-tidd-salesforce-2707.tf, terraform/keycloak-test/realms/onestopauth/client-tidd-salesforce-2707.tf
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc--meldev.my.salesforce.com/services/authcallback/PathfinderIdir</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc--test.my.salesforce.com/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tradeandinvestbc.my.salesforce.com/</li></ul>```
</details>
=> request: update client files for tidd-salesforce-2707

terraform/keycloak-dev/realms/onestopauth/client-ticdi-3202.tf
```<ul>✔️Valid Redirect Urls<li>http://nr-ticdi-git-c57b8f-dev.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for ticdi-3202

terraform/keycloak-dev/realms/onestopauth-both/client-ceed-evolution-3334.tf, terraform/keycloak-test/realms/onestopauth-both/client-ceed-evolution-3334.tf
```<ul>✔️Valid Redirect Urls<li>https://ceed-dev.crm3.dynamics.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ceed-test.crm3.dynamics.com</li></ul>```
</details>
=> request: add client files for ceed-evolution-3334

terraform/keycloak-dev/realms/onestopauth-both/client-ceed-evolution-3334.tf, terraform/keycloak-test/realms/onestopauth-both/client-ceed-evolution-3334.tf
```<ul>✔️Valid Redirect Urls<li>https://ceed.microsoftcrmportals.com/signin-openid_1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ceed.microsoftcrmportals.com/signin-openid_1</li></ul>```
</details>
=> request: update client files for ceed-evolution-3334

terraform/keycloak-dev/realms/onestopauth/client-coco-experiment-3367.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8080/app</li></ul>```
</details>
=> request: add client files for coco-experiment-3367

terraform/keycloak-dev/realms/onestopauth/client-coco-experiment-3367.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/app</li>,<li>https://localhost:8080/app</li></ul>```
</details>
=> request: update client files for coco-experiment-3367

terraform/keycloak-dev/realms/onestopauth/client-coco-experiment-3368.tf, terraform/keycloak-test/realms/onestopauth/client-coco-experiment-3368.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8082/app/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8082/app/</li></ul>```
</details>
=> request: add client files for coco-experiment-3368

terraform/keycloak-dev/realms/onestopauth/client-coco-experiment-3368.tf, terraform/keycloak-test/realms/onestopauth/client-coco-experiment-3368.tf
```<ul>✔️Valid Redirect Urls<li>http://192.168.1.65:8082/app/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8082/app/</li></ul>```
</details>
=> request: update client files for coco-experiment-3368

terraform/keycloak-dev/realms/onestopauth/client-coco-experiment-2-3400.tf, terraform/keycloak-test/realms/onestopauth/client-coco-experiment-2-3400.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>http://localhost:8080/app</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>http://localhost:8080/app</li></ul>```
</details>
=> request: add client files for coco-experiment-2-3400

terraform/keycloak-dev/realms/onestopauth/client-work-bc-career-compass-3136.tf, terraform/keycloak-prod/realms/onestopauth/client-work-bc-career-compass-3136.tf, terraform/keycloak-test/realms/onestopauth/client-work-bc-career-compass-3136.tf
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes-dev/openid-connect/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes-test/openid-connect/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes/openid-connect/*</li></ul>```
</details>
=> request: update client files for work-bc-career-compass-3136

terraform/keycloak-dev/realms/onestopauth/client-greenfield-template-2971.tf
=> request: delete client files for greenfield-template-2971

terraform/keycloak-dev/realms/onestopauth/client-executive-support-system-3565.tf, terraform/keycloak-prod/realms/onestopauth/client-executive-support-system-3565.tf, terraform/keycloak-test/realms/onestopauth/client-executive-support-system-3565.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.cabops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.cabops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cabops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for executive-support-system-3565

terraform/keycloak-dev/realms/onestopauth-business/client-awp-dev-tst-uat-idir-b-ce-id-2146.tf, terraform/keycloak-prod/realms/onestopauth-business/client-awp-dev-tst-uat-idir-b-ce-id-2146.tf, terraform/keycloak-test/realms/onestopauth-business/client-awp-dev-tst-uat-idir-b-ce-id-2146.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-awp-cloak-proxied.th.gov.bc.ca/*</li>,<li>https://dev-awp-cloak.th.gov.bc.ca/*</li>,<li>https://dev-awp.th.gov.bc.ca/*</li>,<li>https://localhost:44317/*</li>,<li>https://localhost:44341/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-awp-cloak-proxied.th.gov.bc.ca/*</li>,<li>https://tst-awp.th.gov.bc.ca/*</li>,<li>https://uat-awp.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://awp.th.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for awp-dev-tst-uat-idir-b-ce-id-2146

terraform/keycloak-dev/realms/onestopauth/client-awp-prd-idir-only-3634.tf, terraform/keycloak-prod/realms/onestopauth/client-awp-prd-idir-only-3634.tf
```<ul>✔️Valid Redirect Urls<li>https://NOT-USED-awp.th.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://awp.th.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for awp-prd-idir-only-3634

terraform/keycloak-dev/realms/onestopauth/client-ti-gr-s-3467.tf, terraform/keycloak-prod/realms/onestopauth/client-ti-gr-s-3467.tf, terraform/keycloak-test/realms/onestopauth/client-ti-gr-s-3467.tf
```<ul>✔️Valid Redirect Urls<li>https://bcmot--dev2.my.salesforce.com/services/authcallback/BCGovSSO</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcmot--test.my.salesforce.com/services/authcallback/BCGovSSO</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcmot.my.salesforce.com/services/authcallback/BCGovSSO</li></ul>```
</details>
=> request: update client files for ti-gr-s-3467

terraform/keycloak-dev/realms/onestopauth/client-slam-3637.tf, terraform/keycloak-prod/realms/onestopauth/client-slam-3637.tf, terraform/keycloak-test/realms/onestopauth/client-slam-3637.tf
```<ul>✔️Valid Redirect Urls<li>https://citz-imb-slam-ca94a8-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://citz-imb-slam-ca94a8-test.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://citz-imb-slam-ca94a8.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for slam-3637

terraform-v2/keycloak-dev/standard-clients/junmin-gold-1-3638.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-gold-1-3638

terraform-v2/keycloak-dev/standard-clients/april-27-zorin-test-idir-only-3639.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:10004</li></ul>```
</details>
=> request: add client files for april-27-zorin-test-idir-only-3639

terraform-v2/keycloak-dev/standard-clients/april-27-test-training-3642.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for april-27-test-training-3642

terraform-v2/keycloak-dev/standard-clients/tians-gold-testing-4-28-3644.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for tians-gold-testing-4-28-3644

terraform-v2/keycloak-dev/standard-clients/test-project-3645.tf
```<ul>✔️Valid Redirect Urls<li>https://test-project</li></ul>```
</details>
=> request: add client files for test-project-3645

terraform/keycloak-dev/realms/onestopauth-basic/client-test-silver-b-ce-id-basic-only-dev-727.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for test-silver-b-ce-id-basic-only-dev-727

terraform/keycloak-test/realms/onestopauth-business/client-test-silver-b-ce-id-business-only-dev-1882.tf
<details><summary>Show Details for test</summary>
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for test-silver-b-ce-id-business-only-dev-1882

terraform/keycloak-dev/realms/onestopauth-both/client-test-silver-b-ce-id-both-dev-2179.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for test-silver-b-ce-id-both-dev-2179

terraform-v2/keycloak-dev/standard-clients/april-28-test-gold-b-ce-id-basic-3647.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for april-28-test-gold-b-ce-id-basic-3647

terraform-v2/keycloak-dev/standard-clients/april-28-test-gold-b-ce-id-business-3648.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for april-28-test-gold-b-ce-id-business-3648

terraform-v2/keycloak-dev/standard-clients/april-28-gold-test-b-ce-id-both-3649.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for april-28-gold-test-b-ce-id-both-3649

terraform/keycloak-dev/realms/onestopauth/client-awp-prd-idir-only-3634.tf, terraform/keycloak-prod/realms/onestopauth/client-awp-prd-idir-only-3634.tf
```<ul>✔️Valid Redirect Urls<li>https://NOT-USED-awp.th.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://awp.th.gov.bc.ca/*</li>,<li>https://dev-awp.th.gov.bc.ca/*</li></ul>```
</details>
=> request: update client files for awp-prd-idir-only-3634

terraform/keycloak-dev/realms/onestopauth/client-traffic-courts-online-3499.tf, terraform/keycloak-prod/realms/onestopauth/client-traffic-courts-online-3499.tf, terraform/keycloak-test/realms/onestopauth/client-traffic-courts-online-3499.tf
```<ul>✔️Valid Redirect Urls<li>https://staff-web-0198bb-dev.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://staff-web-0198bb-test.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://staff-web-0198bb-prod.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for traffic-courts-online-3499

terraform/keycloak-dev/realms/onestopauth/client-psa-moodle-3665.tf, terraform/keycloak-prod/realms/onestopauth/client-psa-moodle-3665.tf, terraform/keycloak-test/realms/onestopauth/client-psa-moodle-3665.tf
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-dev.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li>,<li>https://moodle.virtuallearn.ca/admin/oauth2callback.php</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-test.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-prod.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li></ul>```
</details>
=> request: add client files for psa-moodle-3665

terraform-v2/keycloak-dev/standard-clients/may-5-idir-and-b-ceid-basic-non-prod-3667.tf, terraform-v2/keycloak-test/standard-clients/may-5-idir-and-b-ceid-basic-non-prod-3667.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for may-5-idir-and-b-ceid-basic-non-prod-3667

terraform/keycloak-dev/realms/onestopauth/client-met-3668.tf
```<ul>✔️Valid Redirect Urls<li>https://keycloak-e903c2-dev.apps.gold.devops.gov.bc.ca/auth/realms/met/broker/IDIR/endpoint</li></ul>```
</details>
=> request: add client files for met-3668

terraform/keycloak-dev/realms/onestopauth/client-sdpr-research-portal-3669.tf, terraform/keycloak-prod/realms/onestopauth/client-sdpr-research-portal-3669.tf, terraform/keycloak-test/realms/onestopauth/client-sdpr-research-portal-3669.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li>,<li>https://research-portal-ba7244-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://research-portal-ba7244-test.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://research-portal-ba7244-prod.apps.silver.devops.gov.bc.ca/</li>,<li>https://research.sd.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for sdpr-research-portal-3669

terraform/keycloak-dev/realms/onestopauth/client-bc-public-service-agency-bi-3670.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:9595</li></ul>```
</details>
=> request: add client files for bc-public-service-agency-bi-3670

terraform/keycloak-dev/realms/onestopauth/client-met-3668.tf
```<ul>✔️Valid Redirect Urls<li>https://keycloak-e903c2-dev.apps.gold.devops.gov.bc.ca/auth/realms/met/broker/idir/endpoint</li></ul>```
</details>
=> request: update client files for met-3668

.github/workflows/terraform-v2-apply.yml, terraform-v2/keycloak-dev/main.tf, terraform-v2/keycloak-prod/main.tf, terraform-v2/keycloak-test/main.tf
- add viewer roles in master realms in Gold cluster
=> feat: add viewer role in master realms

terraform/keycloak-dev/realms/onestopauth-both/client-conn-ccbc-portal-3700.tf, terraform/keycloak-prod/realms/onestopauth-both/client-conn-ccbc-portal-3700.tf, terraform/keycloak-test/realms/onestopauth-both/client-conn-ccbc-portal-3700.tf
```<ul>✔️Valid Redirect Urls<li>https://ccbc-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ccbc-test.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ccbc.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for conn-ccbc-portal-3700

terraform/keycloak-dev/realms/onestopauth-basic/client-bceidplay-3701.tf, terraform/keycloak-test/realms/onestopauth-basic/client-bceidplay-3701.tf
```<ul>✔️Valid Redirect Urls<li>https://bceid-dev.solnspace.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bceid-test.solnspace.com</li></ul>```
</details>
=> request: add client files for bceidplay-3701

terraform/keycloak-dev/realms/onestopauth/client-fam-3702.tf
```<ul>✔️Valid Redirect Urls<li>https://oidcdebuggersecure-3d5c3f-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for fam-3702

terraform/keycloak-dev/realms/onestopauth/client-fam-3702.tf
```<ul>✔️Valid Redirect Urls<li>https://oidcdebuggersecure-3d5c3f-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: update client files for fam-3702

terraform/keycloak-dev/realms/onestopauth-both/client-conn-ccbc-portal-3700.tf, terraform/keycloak-prod/realms/onestopauth-both/client-conn-ccbc-portal-3700.tf, terraform/keycloak-test/realms/onestopauth-both/client-conn-ccbc-portal-3700.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/dashboard</li>,<li>https://ccbc-dev.apps.silver.devops.gov.bc.ca/dashboard</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ccbc-test.apps.silver.devops.gov.bc.ca/dashboard</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ccbc.apps.silver.devops.gov.bc.ca/dashboard</li></ul>```
</details>
=> request: update client files for conn-ccbc-portal-3700

terraform-v2/keycloak-dev/standard-clients/june-2-b-ce-id-all-idir-non-prod-3732.tf, terraform-v2/keycloak-test/standard-clients/june-2-b-ce-id-all-idir-non-prod-3732.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for june-2-b-ce-id-all-idir-non-prod-3732

terraform-v2/keycloak-dev/standard-clients/june-2-b-ce-id-both-azure-ad-non-prod-3733.tf, terraform-v2/keycloak-test/standard-clients/june-2-b-ce-id-both-azure-ad-non-prod-3733.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for june-2-b-ce-id-both-azure-ad-non-prod-3733

terraform-v2/keycloak-dev/standard-clients/june-2-zorin-test-domain-json-file-3734.tf, terraform-v2/keycloak-test/standard-clients/june-2-zorin-test-domain-json-file-3734.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for june-2-zorin-test-domain-json-file-3734

terraform-v2/keycloak-dev/standard-clients/bc-telemetry-warehouse-3766.tf, terraform-v2/keycloak-prod/standard-clients/bc-telemetry-warehouse-3766.tf, terraform-v2/keycloak-test/standard-clients/bc-telemetry-warehouse-3766.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1111/*</li>,<li>http://moe-bctw-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://moe-bctw-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://telemetry.nrs.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for bc-telemetry-warehouse-3766

terraform-v2/keycloak-dev/standard-clients/wildlife-health-information-system-3767.tf, terraform-v2/keycloak-prod/standard-clients/wildlife-health-information-system-3767.tf, terraform-v2/keycloak-test/standard-clients/wildlife-health-information-system-3767.tf
```<ul>✔️Valid Redirect Urls<li>https://whis-ui-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://whis-ui-test.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://whis-ui-prod.apps.silver.devops.gov.bc.ca/</li>,<li>https://wildlifehealth.nrs.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for wildlife-health-information-system-3767

terraform-v2/keycloak-dev/standard-clients/epicflow-3764.tf, terraform-v2/keycloak-test/standard-clients/epicflow-3764.tf
```<ul>✔️Valid Redirect Urls<li>https://web-dc383e-dev.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://web-dc383e-test.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for epicflow-3764

terraform-v2/keycloak-dev/standard-clients/tracks-3768.tf, terraform-v2/keycloak-prod/standard-clients/tracks-3768.tf, terraform-v2/keycloak-test/standard-clients/tracks-3768.tf
```<ul>✔️Valid Redirect Urls<li>https://moe-tracks-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://moe-tracks-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tracks.nrs.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for tracks-3768

terraform-v2/keycloak-dev/standard-clients/sdpr-research-portal-3770.tf, terraform-v2/keycloak-prod/standard-clients/sdpr-research-portal-3770.tf, terraform-v2/keycloak-test/standard-clients/sdpr-research-portal-3770.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://research-portal-ba7244-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://research-portal-ba7244-test.apps.silver.devops.gov.bc.ca</li>,<li>https://research-portal-ba7244-test.apps.silver.devops.gov.bc.ca/nfa/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://research-portal-ba7244-prod.apps.silver.devops.gov.bc.ca/*</li>,<li>https://research.sd.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for sdpr-research-portal-3770

terraform-v2/keycloak-dev/standard-clients/taft-gold-3771.tf, terraform-v2/keycloak-prod/standard-clients/taft-gold-3771.tf, terraform-v2/keycloak-test/standard-clients/taft-gold-3771.tf
```<ul>✔️Valid Redirect Urls<li>https://idm-dev-taft.apps.silver.devops.gov.bc.ca/auth/realms/taft/broker/idir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://idm-test-taft.apps.silver.devops.gov.bc.ca/auth/realms/taft/broker/idir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://idm.taft.fin.gov.bc.ca/auth/realms/taft/broker/idir/endpoint</li></ul>```
</details>
=> request: add client files for taft-gold-3771

terraform-v2/keycloak-dev/standard-clients/foi-report-download-3796.tf, terraform-v2/keycloak-prod/standard-clients/foi-report-download-3796.tf, terraform-v2/keycloak-test/standard-clients/foi-report-download-3796.tf
```<ul>✔️Valid Redirect Urls<li>https://foi-report-download-556e1b-dev.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://foi-report-download-556e1b-test.apps.silver.devops.gov.bc.ca</li>,<li>https://test.foireport.analytics.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://foi-report-download-556e1b-prod.apps.silver.devops.gov.bc.ca</li>,<li>https://foireport.analytics.gov.bc.ca</li></ul>```
</details>
=> request: add client files for foi-report-download-3796

terraform-v2/keycloak-dev/standard-clients/awp-3798.tf, terraform-v2/keycloak-prod/standard-clients/awp-3798.tf, terraform-v2/keycloak-test/standard-clients/awp-3798.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-awp.th.gov.bc.ca/*</li>,<li>https://localhost:44317/*</li>,<li>https://localhost:44341/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://rft-awp.th.gov.bc.ca/*</li>,<li>https://tst-awp.th.gov.bc.ca/*</li>,<li>https://uat-awp.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://awp.th.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for awp-3798

terraform-v2/keycloak-dev/standard-clients/bcea-forecast-3797.tf, terraform-v2/keycloak-prod/standard-clients/bcea-forecast-3797.tf, terraform-v2/keycloak-test/standard-clients/bcea-forecast-3797.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://bcea-forecast-d9436d-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcea-forecast-d9436d-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcea-forecast-d9436d-prod.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for bcea-forecast-3797

terraform-v2/keycloak-dev/standard-clients/executive-support-system-3799.tf, terraform-v2/keycloak-prod/standard-clients/executive-support-system-3799.tf, terraform-v2/keycloak-test/standard-clients/executive-support-system-3799.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.cabops.gov.bc.ca/</li>,<li>https://dev.cabops.gov.bc.ca/*</li>,<li>https://dev.cabops.gov.bc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.cabops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cabops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for executive-support-system-3799

terraform-v2/keycloak-dev/standard-clients/chefs-data-ingestion-ministry-of-health-3800.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>http://localhost:8081/*</li>,<li>http://localhost:8082/*</li></ul>```
</details>
=> request: add client files for chefs-data-ingestion-ministry-of-health-3800

terraform-v2/keycloak-dev/standard-clients/chefs-data-ingestion-ministry-of-health-3802.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>http://localhost:8081/*</li>,<li>http://localhost:8082/*</li></ul>```
</details>
=> request: add client files for chefs-data-ingestion-ministry-of-health-3802

terraform-v2/keycloak-dev/standard-clients/ministry-of-finance-intranet-3804.tf, terraform-v2/keycloak-prod/standard-clients/ministry-of-finance-intranet-3804.tf, terraform-v2/keycloak-test/standard-clients/ministry-of-finance-intranet-3804.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.intranet.fin.gov.bc.ca/</li>,<li>https://dev.intranet.fin.gov.bc.ca/*</li>,<li>https://dev.intranet.fin.gov.bc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.intranet.fin.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://intranet.fin.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for ministry-of-finance-intranet-3804

terraform-v2/keycloak-dev/standard-clients/dip-3830.tf, terraform-v2/keycloak-prod/standard-clients/dip-3830.tf, terraform-v2/keycloak-test/standard-clients/dip-3830.tf
```<ul>✔️Valid Redirect Urls<li>https://dip-authz.apps.gov.bc.ca/auth/realms/dev/broker/gov/endpoint</li>,<li>https://dip-authz.apps.gov.bc.ca/auth/realms/test/broker/oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dip-authz.apps.gov.bc.ca/auth/realms/dev/broker/gov/endpoint</li>,<li>https://dip-authz.apps.gov.bc.ca/auth/realms/test/broker/oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dip-authz.apps.gov.bc.ca/auth/realms/prod/broker/gov/endpoint</li></ul>```
</details>
=> request: add client files for dip-3830

terraform-v2/keycloak-dev/standard-clients/mod-chefs-local-3831.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li>,<li>http://localhost:8081</li>,<li>http://localhost:8082</li></ul>```
</details>
=> request: add client files for mod-chefs-local-3831

terraform-v2/keycloak-dev/standard-clients/gdx-agreements-tracker-3833.tf, terraform-v2/keycloak-prod/standard-clients/gdx-agreements-tracker-3833.tf, terraform-v2/keycloak-test/standard-clients/gdx-agreements-tracker-3833.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://gdx-agreements-tracker-dev.apps.silver.devops.gov.bc.ca/login?redirect=/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://gdx-agreements-tracker.apps.silver.devops.gov.bc.ca/login?redirect=/</li></ul>```
</details>
=> request: add client files for gdx-agreements-tracker-3833

terraform-v2/keycloak-dev/standard-clients/keycloak-test-3834.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li></ul>```
</details>
=> request: add client files for keycloak-test-3834

terraform-v2/keycloak-dev/standard-clients/hwp-3862.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
=> request: add client files for hwp-3862

terraform/keycloak-dev/realms/onestopauth-basic/client-community-corrections-case-management-3650.tf, terraform/keycloak-prod/realms/onestopauth-basic/client-community-corrections-case-management-3650.tf, terraform/keycloak-test/realms/onestopauth-basic/client-community-corrections-case-management-3650.tf
```<ul>✔️Valid Redirect Urls<li>https://cccm-keycloak-abb712-dev.apps.gold.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cccm-keycloak-abb712-test.apps.gold.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cccm-keycloak-abb712-prod.apps.gold.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for community-corrections-case-management-3650

terraform-v2/keycloak-dev/standard-clients/aps-po-c-roles-3864.tf
```<ul>✔️Valid Redirect Urls<li>https://aps-roles-poc-apps-gov-bc-ca.dev.api.gov.bc.ca</li></ul>```
</details>
=> request: add client files for aps-po-c-roles-3864

terraform-v2/keycloak-dev/standard-clients/bc-data-catalogue-3863.tf, terraform-v2/keycloak-prod/standard-clients/bc-data-catalogue-3863.tf, terraform-v2/keycloak-test/standard-clients/bc-data-catalogue-3863.tf
```<ul>✔️Valid Redirect Urls<li>https://dwelf.data.gov.bc.ca/client-api/callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://toyger.data.gov.bc.ca/client-api/callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://catalogue.data.gov.bc.ca/client-api/callback</li></ul>```
</details>
=> request: add client files for bc-data-catalogue-3863

terraform-v2/keycloak-dev/standard-clients/gdx-public-client-3865.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost</li></ul>```
</details>
=> request: add client files for gdx-public-client-3865

terraform-v2/keycloak-dev/standard-clients/wodpress-sso-idir-3895.tf, terraform-v2/keycloak-test/standard-clients/wodpress-sso-idir-3895.tf
```<ul>✔️Valid Redirect Urls<li>https://cloud-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cloud-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for wodpress-sso-idir-3895

terraform-v2/keycloak-dev/standard-clients/dss-dps-kirk-3928.tf, terraform-v2/keycloak-prod/standard-clients/dss-dps-kirk-3928.tf, terraform-v2/keycloak-test/standard-clients/dss-dps-kirk-3928.tf
```<ul>✔️Valid Redirect Urls<li>https://dps-ops-portal.apps.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dps-ops-portal.apps.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dps-ops-portal.apps.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for dss-dps-kirk-3928

terraform-v2/keycloak-dev/standard-clients/geocoder-3929.tf, terraform-v2/keycloak-prod/standard-clients/geocoder-3929.tf, terraform-v2/keycloak-test/standard-clients/geocoder-3929.tf
```<ul>✔️Valid Redirect Urls<li>https://geocoder-config-admin-dev.apps.gov.bc.ca/int/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://geocoder-config-admin-test.apps.gov.bc.ca/int/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://data-integration-geocoder-config-admin.apps.gov.bc.ca/int/</li>,<li>https://geocoder-config-admin-prod.apps.gov.bc.ca/int/</li></ul>```
</details>
=> request: add client files for geocoder-3929

terraform-v2/keycloak-dev/standard-clients/geocoder-admin-3930.tf
```<ul>✔️Valid Redirect Urls<li>https://data-integration-geocoder-config-admin.apps.gov.bc.ca/int/</li>,<li>https://geocoder-config-admin-dev.apps.gov.bc.ca/int/</li>,<li>https://geocoder-config-admin-prod.apps.gov.bc.ca/int/</li>,<li>https://geocoder-config-admin-test.apps.gov.bc.ca/int/</li></ul>```
</details>
=> request: add client files for geocoder-admin-3930

terraform-v2/keycloak-dev/standard-clients/july-5-test-3765.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for july-5-test-3765

terraform-v2/keycloak-dev/standard-clients/aqss-3932.tf, terraform-v2/keycloak-prod/standard-clients/aqss-3932.tf, terraform-v2/keycloak-test/standard-clients/aqss-3932.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li>,<li>https://notify-bc-ef3999-dev.apps.gold.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://notify-bc-ef3999-test.apps.gold.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://notify-bc-ef3999-prod.apps.gold.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for aqss-3932

terraform-v2/keycloak-dev/standard-clients/geocoder-3933.tf, terraform-v2/keycloak-prod/standard-clients/geocoder-3933.tf, terraform-v2/keycloak-test/standard-clients/geocoder-3933.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for geocoder-3933

terraform-v2/keycloak-dev/standard-clients/pecsf-greenfield-3936.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8000/keycloak/callback</li></ul>```
</details>
=> request: add client files for pecsf-greenfield-3936

terraform-v2/keycloak-dev/standard-clients/tians-gold-testing-confidential-client-3938.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for tians-gold-testing-confidential-client-3938

terraform/keycloak-dev/realms/onestopauth/client-dss-kirk-1288.tf, terraform/keycloak-prod/realms/onestopauth/client-dss-kirk-1288.tf, terraform/keycloak-test/realms/onestopauth/client-dss-kirk-1288.tf
```<ul>✔️Valid Redirect Urls<li>https://kirk-d.data.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://kirk-t.data.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://kirk.data.gov.bc.ca/</li></ul>```
</details>
=> request: update client files for dss-kirk-1288

terraform-v2/keycloak-dev/standard-clients/jon-confidential-examp-3941.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/oauth/cognito</li></ul>```
</details>
=> request: add client files for jon-confidential-examp-3941

terraform-v2/keycloak-dev/standard-clients/performance-application-system-3942.tf, terraform-v2/keycloak-prod/standard-clients/performance-application-system-3942.tf, terraform-v2/keycloak-test/standard-clients/performance-application-system-3942.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8000</li>,<li>https://performance-332842-dev.apps.silver.devops.gov.bc.ca/login/keycloak/callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://performance-332842-test.apps.silver.devops.gov.bc.ca/login/keycloak/callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://performance.gov.bc.ca/login/keycloak/callback</li></ul>```
</details>
=> request: add client files for performance-application-system-3942

terraform/keycloak-dev/realms/onestopauth/client-slam-3637.tf, terraform/keycloak-prod/realms/onestopauth/client-slam-3637.tf, terraform/keycloak-test/realms/onestopauth/client-slam-3637.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.slam.im.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.slam.im.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://slam.im.gov.bc.ca</li></ul>```
</details>
=> request: update client files for slam-3637

terraform-v2/keycloak-dev/standard-clients/slam-3943.tf, terraform-v2/keycloak-prod/standard-clients/slam-3943.tf, terraform-v2/keycloak-test/standard-clients/slam-3943.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.slam.im.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.slam.im.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://slam.im.gov.bc.ca</li></ul>```
</details>
=> request: add client files for slam-3943

terraform-v2/keycloak-dev/standard-clients/alcs-3944.tf, terraform-v2/keycloak-prod/standard-clients/alcs-3944.tf, terraform-v2/keycloak-test/standard-clients/alcs-3944.tf
```<ul>✔️Valid Redirect Urls<li>https://alcs-dev.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://alcs-test.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://alcs.nrs.gov.bc.ca</li></ul>```
</details>
=> request: add client files for alcs-3944

terraform-v2/keycloak-dev/standard-clients/wordpress-sso-idir-3946.tf, terraform-v2/keycloak-prod/standard-clients/wordpress-sso-idir-3946.tf, terraform-v2/keycloak-test/standard-clients/wordpress-sso-idir-3946.tf
```<ul>✔️Valid Redirect Urls<li>https://cloud-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cloud-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cloud.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for wordpress-sso-idir-3946

terraform-v2/keycloak-dev/standard-clients/wordpress-sso-idir-bceid-3947.tf, terraform-v2/keycloak-prod/standard-clients/wordpress-sso-idir-bceid-3947.tf, terraform-v2/keycloak-test/standard-clients/wordpress-sso-idir-bceid-3947.tf
```<ul>✔️Valid Redirect Urls<li>https://bcfd-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcfd-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://feedbcdirectory.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for wordpress-sso-idir-bceid-3947

terraform-v2/keycloak-dev/standard-clients/work-bc-career-education-resources-3948.tf, terraform-v2/keycloak-prod/standard-clients/work-bc-career-education-resources-3948.tf, terraform-v2/keycloak-test/standard-clients/work-bc-career-education-resources-3948.tf
```<ul>✔️Valid Redirect Urls<li>https://careereducation-dev.workbc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careereducation-test.workbc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careereducation.workbc.ca/openid-connect/keycloak</li></ul>```
</details>
=> request: add client files for work-bc-career-education-resources-3948

terraform-v2/keycloak-dev/standard-clients/router-3949.tf, terraform-v2/keycloak-prod/standard-clients/router-3949.tf, terraform-v2/keycloak-test/standard-clients/router-3949.tf
```<ul>✔️Valid Redirect Urls<li>https://*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://*</li></ul>```
</details>
=> request: add client files for router-3949

terraform-v2/keycloak-dev/standard-clients/work-bc-career-discovery-quizzes-3962.tf, terraform-v2/keycloak-prod/standard-clients/work-bc-career-discovery-quizzes-3962.tf, terraform-v2/keycloak-test/standard-clients/work-bc-career-discovery-quizzes-3962.tf
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes-dev.workbc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes-test.workbc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes.workbc.ca/openid-connect/keycloak</li></ul>```
</details>
=> request: add client files for work-bc-career-discovery-quizzes-3962

terraform-v2/keycloak-dev/standard-clients/acrfd-3963.tf, terraform-v2/keycloak-prod/standard-clients/acrfd-3963.tf, terraform-v2/keycloak-test/standard-clients/acrfd-3963.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for acrfd-3963

terraform-v2/keycloak-dev/standard-clients/coms-3964.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for coms-3964

terraform-v2/keycloak-dev/standard-clients/awp-idir-prd-gold-3965.tf, terraform-v2/keycloak-prod/standard-clients/awp-idir-prd-gold-3965.tf
```<ul>✔️Valid Redirect Urls<li>https://awp.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://awp.th.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for awp-idir-prd-gold-3965

terraform-v2/keycloak-dev/standard-clients/coms-showcase-frontend-local-3966.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8081/*</li></ul>```
</details>
=> request: add client files for coms-showcase-frontend-local-3966

terraform-v2/keycloak-dev/standard-clients/kuro-testing-example-app-3832.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-example-app-3832

terraform-v2/keycloak-dev/standard-clients/july-28-b-ce-id-b-usiness-dev-3940.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for july-28-b-ce-id-b-usiness-dev-3940

terraform-v2/keycloak-dev/standard-clients/work-bc-3968.tf, terraform-v2/keycloak-prod/standard-clients/work-bc-3968.tf, terraform-v2/keycloak-test/standard-clients/work-bc-3968.tf
```<ul>✔️Valid Redirect Urls<li>https://aws-dev.workbc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://aws-test.workbc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www2.workbc.ca/openid-connect/keycloak</li></ul>```
</details>
=> request: add client files for work-bc-3968

terraform-v2/keycloak-dev/standard-clients/conn-ccbc-portal-3934.tf, terraform-v2/keycloak-prod/standard-clients/conn-ccbc-portal-3934.tf, terraform-v2/keycloak-test/standard-clients/conn-ccbc-portal-3934.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/auth-callback</li>,<li>https://ccbc-dev.apps.silver.devops.gov.bc.ca/auth-callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ccbc-test.apps.silver.devops.gov.bc.ca/auth-callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ccbc.apps.silver.devops.gov.bc.ca/auth-callback</li></ul>```
</details>
=> request: add client files for conn-ccbc-portal-3934

terraform-v2/keycloak-dev/standard-clients/psa-moodle-3969.tf, terraform-v2/keycloak-prod/standard-clients/psa-moodle-3969.tf, terraform-v2/keycloak-test/standard-clients/psa-moodle-3969.tf
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-dev.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li>,<li>https://moodle.virtuallearn.ca/admin/oauth2callback.php</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-test.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://moodle-950003-prod.apps.silver.devops.gov.bc.ca/admin/oauth2callback.php</li></ul>```
</details>
=> request: add client files for psa-moodle-3969

terraform/keycloak-dev/realms/onestopauth/client-aug-4-silver-deletion-test-3651.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for aug-4-silver-deletion-test-3651

terraform-v2/keycloak-dev/standard-clients/itvr-on-gold-cluster-3972.tf, terraform-v2/keycloak-test/standard-clients/itvr-on-gold-cluster-3972.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://itvr-dev-244.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://itvr-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for itvr-on-gold-cluster-3972

terraform-v2/keycloak-dev/standard-clients/tians-testing-delete-client-3973.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-delete-client-3973

terraform-v2/keycloak-dev/standard-clients/cthub-on-gold-cluster-3974.tf, terraform-v2/keycloak-test/standard-clients/cthub-on-gold-cluster-3974.tf
```<ul>✔️Valid Redirect Urls<li>https://cthub-dev-73.apps.silver.devops.gov.bc.ca/</li>,<li>https://cthub-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cthub-test.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for cthub-on-gold-cluster-3974

terraform-v2/keycloak-dev/standard-clients/media-monitoring-mmia-3671.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for media-monitoring-mmia-3671

terraform-v2/keycloak-dev/standard-clients/trans-action-3977.tf, terraform-v2/keycloak-prod/standard-clients/trans-action-3977.tf, terraform-v2/keycloak-test/standard-clients/trans-action-3977.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-transaction.th.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-transaction.th.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://transaction.th.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for trans-action-3977

terraform-v2/keycloak-dev/standard-clients/trans-action-3979.tf, terraform-v2/keycloak-prod/standard-clients/trans-action-3979.tf, terraform-v2/keycloak-test/standard-clients/trans-action-3979.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-transaction.th.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-transaction.th.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://transaction.th.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for trans-action-3979

terraform-v2/keycloak-dev/standard-clients/chefs-data-ingestion-ministry-of-health-3975.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>http://localhost:8081/*</li>,<li>http://localhost:8082/*</li>,<li>http://localhost:8083/*</li></ul>```
</details>
=> request: add client files for chefs-data-ingestion-ministry-of-health-3975

terraform-v2/keycloak-dev/standard-clients/wps-3981.tf, terraform-v2/keycloak-prod/standard-clients/wps-3981.tf, terraform-v2/keycloak-test/standard-clients/wps-3981.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for wps-3981

terraform-v2/keycloak-dev/standard-clients/august-9-b-ce-id-business-only-3970.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for august-9-b-ce-id-business-only-3970

terraform-v2/keycloak-dev/standard-clients/august-9-dev-b-ce-id-both-3982.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for august-9-dev-b-ce-id-both-3982

terraform-v2/keycloak-dev/standard-clients/fms-3983.tf, terraform-v2/keycloak-prod/standard-clients/fms-3983.tf, terraform-v2/keycloak-test/standard-clients/fms-3983.tf
```<ul>✔️Valid Redirect Urls<li>https://online.silvacom.com/fmsmof_bcUAT/HarvestPlanner.html</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://online.silvacom.com/fmsmof_bcUAT/HarvestPlanner.html</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://online.silvacom.com/fmsmof_bc/HarvestPlanner.html</li></ul>```
</details>
=> request: add client files for fms-3983

terraform-v2/keycloak-dev/standard-clients/test-nk-idir-bceid-basic-3984.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
=> request: add client files for test-nk-idir-bceid-basic-3984

terraform-v2/keycloak-dev/standard-clients/test-nk-idir-bceid-both-3985.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
=> request: add client files for test-nk-idir-bceid-both-3985

terraform-v2/keycloak-dev/standard-clients/test-nk-idir-bceid-business-3986.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
=> request: add client files for test-nk-idir-bceid-business-3986

terraform-v2/keycloak-dev/standard-clients/isd-amp-mining-scan-3988.tf, terraform-v2/keycloak-prod/standard-clients/isd-amp-mining-scan-3988.tf, terraform-v2/keycloak-test/standard-clients/isd-amp-mining-scan-3988.tf
```<ul>✔️Valid Redirect Urls<li>https://sso.apps-isd.sd.gov.bc.ca/auth/realms/mining-dev/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://sso.apps-isd.sd.gov.bc.ca/auth/realms/mining-test/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://sso.apps-isd.sd.gov.bc.ca/auth/realms/mining/broker/keycloak-oidc/endpoint</li></ul>```
</details>
=> request: add client files for isd-amp-mining-scan-3988

terraform-v2/keycloak-dev/standard-clients/secure-image-3950.tf
```<ul>✔️Valid Redirect Urls<li>secure-image://client</li></ul>```
</details>
=> request: add client files for secure-image-3950

terraform-v2/keycloak-dev/standard-clients/trans-action-api-3990.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/api/*</li>,<li>https://localhost:44366</li>,<li>https://localhost:44366/*</li></ul>```
</details>
=> request: add client files for trans-action-api-3990

terraform-v2/keycloak-dev/standard-clients/digital-privacy-impact-assessment-modernization-3937.tf, terraform-v2/keycloak-prod/standard-clients/digital-privacy-impact-assessment-modernization-3937.tf, terraform-v2/keycloak-test/standard-clients/digital-privacy-impact-assessment-modernization-3937.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dpia-webapp-test.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dpia-webapp.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for digital-privacy-impact-assessment-modernization-3937

terraform-v2/keycloak-dev/standard-clients/abcd-1-test-3992.tf, terraform-v2/keycloak-test/standard-clients/abcd-1-test-3992.tf
```<ul>✔️Valid Redirect Urls<li>https://abcdevtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>htttps://abctest.com</li></ul>```
</details>
=> request: add client files for abcd-1-test-3992

terraform-v2/keycloak-dev/standard-clients/mmia-3993.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:40080</li></ul>```
</details>
=> request: add client files for mmia-3993

terraform-v2/keycloak-dev/standard-clients/hmcr-3967.tf, terraform-v2/keycloak-prod/standard-clients/hmcr-3967.tf, terraform-v2/keycloak-test/standard-clients/hmcr-3967.tf
```<ul>✔️Valid Redirect Urls<li>http://192.168.0.113:3000/*</li>,<li>http://localhost:27238/*</li>,<li>http://localhost:3000/*</li>,<li>http://localhost:5767/*</li>,<li>https://dev-hmcr.th.gov.bc.ca/*</li>,<li>https://hmcr-0-d3d940-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://hmcr-0-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://hmcr-504-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://hmcr-628-d3d940-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://hmcr-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://pims-app-3cd915-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-hmcr.th.gov.bc.ca</li></ul>``` …
=> request: add client files for hmcr-3967

terraform-v2/keycloak-dev/standard-clients/secure-image-api-3995.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-secure-image.apps.silver.devops.gov.bc.ca/v1/auth/callback</li></ul>```
</details>
=> request: add client files for secure-image-api-3995

terraform-v2/keycloak-dev/standard-clients/coms-showcase-frontend-3996.tf
```<ul>✔️Valid Redirect Urls<li>https://coms-dev-master.apps.silver.devops.gov.bc.ca:8081/*</li></ul>```
</details>
=> request: add client files for coms-showcase-frontend-3996

terraform-v2/keycloak-dev/standard-clients/hmcr-3998.tf, terraform-v2/keycloak-prod/standard-clients/hmcr-3998.tf, terraform-v2/keycloak-test/standard-clients/hmcr-3998.tf
```<ul>✔️Valid Redirect Urls<li>http://192.168.0.113:3000/*</li>,<li>http://localhost:27238/*</li>,<li>http://localhost:3000/*</li>,<li>http://localhost:5767/*</li>,<li>https://dev-hmcr.th.gov.bc.ca</li>,<li>https://hmcr-0-d3d940-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://hmcr-0-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://hmcr-504-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://hmcr-628-d3d940-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://hmcr-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://pims-app-3cd915-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-hmcr.th.gov.bc.ca</li></ul>``` …
=> request: add client files for hmcr-3998

terraform-v2/keycloak-dev/standard-clients/coms-3999.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for coms-3999

terraform-v2/keycloak-dev/standard-clients/land-use-planning-4000.tf, terraform-v2/keycloak-prod/standard-clients/land-use-planning-4000.tf, terraform-v2/keycloak-test/standard-clients/land-use-planning-4000.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:4200/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://landuseplanning-dev.apps.silver.devops.gov.bc.ca/admin/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://landuseplanning.gov.bc.ca/admin/</li></ul>```
</details>
=> request: add client files for land-use-planning-4000

terraform-v2/keycloak-dev/standard-clients/isd-forms-builder-4001.tf
```<ul>✔️Valid Redirect Urls<li>https://obdev.apps.silver.devops.gov.bc.ca/oauth2/callback</li></ul>```
</details>
=> request: add client files for isd-forms-builder-4001

terraform-v2/keycloak-dev/standard-clients/kuro-public-example-app-inte-4002.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-public-example-app-inte-4002

terraform-v2/keycloak-dev/standard-clients/hmcr-4028.tf, terraform-v2/keycloak-prod/standard-clients/hmcr-4028.tf, terraform-v2/keycloak-test/standard-clients/hmcr-4028.tf
```<ul>✔️Valid Redirect Urls<li>http://192.168.0.113:3000/*</li>,<li>http://localhost:27238/*</li>,<li>http://localhost:3000/*</li>,<li>http://localhost:5767/*</li>,<li>https://dev-hmcr.th.gov.bc.ca</li>,<li>https://hmcr-0-d3d940-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://hmcr-0-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://hmcr-504-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://hmcr-628-d3d940-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://hmcr-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://pims-app-3cd915-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-hmcr.th.gov.bc.ca</li></ul>``` …
=> request: add client files for hmcr-4028

terraform-v2/keycloak-dev/standard-clients/hmcr-4029.tf, terraform-v2/keycloak-prod/standard-clients/hmcr-4029.tf, terraform-v2/keycloak-test/standard-clients/hmcr-4029.tf
```<ul>✔️Valid Redirect Urls<li>http://192.168.0.113:3000/*</li>,<li>http://localhost:27238/*</li>,<li>http://localhost:3000/*</li>,<li>http://localhost:5767/*</li>,<li>https://dev-hmcr.th.gov.bc.ca</li>,<li>https://hmcr-0-d3d940-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://hmcr-0-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://hmcr-504-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://hmcr-628-d3d940-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://hmcr-txkggj-dev.pathfinder.gov.bc.ca/*</li>,<li>https://pims-app-3cd915-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-hmcr.th.gov.bc.ca</li></ul>``` …
=> request: add client files for hmcr-4029

terraform-v2/keycloak-dev/standard-clients/land-use-planning-4060.tf, terraform-v2/keycloak-prod/standard-clients/land-use-planning-4060.tf, terraform-v2/keycloak-test/standard-clients/land-use-planning-4060.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:4200/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://landuseplanning-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://landuseplanning.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for land-use-planning-4060

terraform-v2/keycloak-dev/standard-clients/pnp-provincial-nominee-program-4062.tf, terraform-v2/keycloak-prod/standard-clients/pnp-provincial-nominee-program-4062.tf, terraform-v2/keycloak-test/standard-clients/pnp-provincial-nominee-program-4062.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost</li>,<li>http://localhost:3000/</li>,<li>http://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8000/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8000/</li></ul>```
</details>
=> request: add client files for pnp-provincial-nominee-program-4062

terraform-v2/keycloak-dev/standard-clients/crt-4064.tf, terraform-v2/keycloak-prod/standard-clients/crt-4064.tf, terraform-v2/keycloak-test/standard-clients/crt-4064.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://dev-crt.th.gov.bc.ca/</li>,<li>https://dev-crt.th.gov.bc.ca/*</li>,<li>https://localhost:44349/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-crt.th.gov.bc.ca/</li>,<li>https://tst-crt.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://crt.th.gov.bc.ca/</li>,<li>https://crt.th.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for crt-4064

terraform-v2/keycloak-dev/standard-clients/psa-digital-journeys-3961.tf, terraform-v2/keycloak-prod/standard-clients/psa-digital-journeys-3961.tf, terraform-v2/keycloak-test/standard-clients/psa-digital-journeys-3961.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li>,<li>https://digital-journeys-keycloak-dev.apps.silver.devops.gov.bc.ca/auth/realms/psa-digital-journey-dev/broker/ocio/endpoint</li>,<li>https://keycloak.freshworks.club/auth/realms/psa-digital-journey-local/broker/ocio/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://digital-journeys-keycloak-test.apps.silver.devops.gov.bc.ca/auth/realms/psa-digital-journey-test/*</li>,<li>https://digital-journeys-keycloak-test.apps.silver.devops.gov.bc.ca/auth/realms/psa-digital-journey-test/broker/ocio/endpoint</li></ul>```
```<ul>✔️Valid Redirect …
```
=> request: add client files for psa-digital-journeys-3961

terraform-v2/keycloak-dev/standard-clients/tians-testing-8-24-4066.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-8-24-4066.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-8-24-4066

terraform-v2/keycloak-dev/standard-clients/public-example-app-4067.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for public-example-app-4067

terraform-v2/keycloak-dev/standard-clients/gladis-4068.tf, terraform-v2/keycloak-prod/standard-clients/gladis-4068.tf, terraform-v2/keycloak-test/standard-clients/gladis-4068.tf
```<ul>✔️Valid Redirect Urls<li>https://home.urbanlogiq.ca</li>,<li>https://urbanlogiqcanada.b2clogin.com/urbanlogiqcanada.onmicrosoft.com/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://home.urbanlogiq.ca</li>,<li>https://urbanlogiqcanada.b2clogin.com/urbanlogiqcanada.onmicrosoft.com/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://gladis.bcgov.urbanlogiq.ca</li>,<li>https://home.urbanlogiq.ca</li>,<li>https://urbanlogiqcanada.b2clogin.com/urbanlogiqcanada.onmicrosoft.com/*</li></ul>```
</details>
=> request: add client files for gladis-4068

terraform-v2/keycloak-dev/standard-clients/forest-client-4070.tf, terraform-v2/keycloak-test/standard-clients/forest-client-4070.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://nrfc-test-frontend.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for forest-client-4070

terraform-v2/keycloak-dev/standard-clients/payment-common-component-4071.tf, terraform-v2/keycloak-prod/standard-clients/payment-common-component-4071.tf, terraform-v2/keycloak-test/standard-clients/payment-common-component-4071.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for payment-common-component-4071

terraform-v2/keycloak-dev/standard-clients/new-job-survey-admin-4074.tf, terraform-v2/keycloak-prod/standard-clients/new-job-survey-admin-4074.tf, terraform-v2/keycloak-test/standard-clients/new-job-survey-admin-4074.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000/*</li>,<li>https://localhost:5051/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000/*</li>,<li>https://localhost:5051/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000/*</li>,<li>https://localhost:5051/*</li></ul>```
</details>
=> request: add client files for new-job-survey-admin-4074

terraform-v2/keycloak-dev/standard-clients/gdx-agreements-tracker-4075.tf, terraform-v2/keycloak-prod/standard-clients/gdx-agreements-tracker-4075.tf, terraform-v2/keycloak-test/standard-clients/gdx-agreements-tracker-4075.tf
```<ul>✔️Valid Redirect Urls<li>https://gdx-agreements-tracker-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://localhost:3000/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://gdx-agreements-tracker-test.apps.silver.devops.gov.bc.ca/*</li>,<li>https://localhost:3000/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://gdx-agreements-tracker-prod.apps.silver.devops.gov.bc.ca/*</li>,<li>https://localhost:3000/*</li></ul>```
</details>
=> request: add client files for gdx-agreements-tracker-4075

terraform-v2/keycloak-dev/standard-clients/work-bc-job-board-4078.tf, terraform-v2/keycloak-prod/standard-clients/work-bc-job-board-4078.tf, terraform-v2/keycloak-test/standard-clients/work-bc-job-board-4078.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-admin-jobboard.workbc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test-admin-jobboard.workbc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://admin-jobboard.workbc.ca/*</li></ul>```
</details>
=> request: add client files for work-bc-job-board-4078

terraform-v2/keycloak-dev/standard-clients/software-as-a-service-saa-s-website-4079.tf, terraform-v2/keycloak-prod/standard-clients/software-as-a-service-saa-s-website-4079.tf
```<ul>✔️Valid Redirect Urls<li>https://cloud.gov.bc.ca/saas/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cloud.gov.bc.ca/saas/</li></ul>```
</details>
=> request: add client files for software-as-a-service-saa-s-website-4079

terraform-v2/keycloak-dev/standard-clients/education-common-4080.tf, terraform-v2/keycloak-prod/standard-clients/education-common-4080.tf, terraform-v2/keycloak-test/standard-clients/education-common-4080.tf
```<ul>✔️Valid Redirect Urls<li>https://soam-dev.apps.silver.devops.gov.bc.ca/auth/realms/master/broker/gold-basic-bceid/endpoint</li>,<li>https://soam-dev.apps.silver.devops.gov.bc.ca/auth/realms/master/broker/gold-idir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://soam-test.apps.silver.devops.gov.bc.ca/auth/realms/master/broker/gold-basic-bceid/endpoint</li>,<li>https://soam-test.apps.silver.devops.gov.bc.ca/auth/realms/master/broker/gold-idir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://soam-prod.apps.silver.devops.gov.bc.ca/auth/realms/master/broker/gold-basic-bceid/endpoint</li>,<li>h …
```
=> request: add client files for education-common-4080

terraform-v2/keycloak-dev/standard-clients/tians-testing-9-1-4081.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-9-1-4081.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-9-1-4081

terraform-v2/keycloak-dev/standard-clients/tians-testing-9-2-4082.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-9-2-4082.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-9-2-4082.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for tians-testing-9-2-4082

terraform-v2/keycloak-dev/standard-clients/junmin-awesome-saml-4084.tf, terraform-v2/keycloak-test/standard-clients/junmin-awesome-saml-4084.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-awesome-saml-4084

terraform-v2/keycloak-dev/standard-clients/tians-testing-saml-4085.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-saml-4085.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-saml-4085

terraform-v2/keycloak-dev/standard-clients/formsflow-demo-4086.tf
```<ul>✔️Valid Redirect Urls<li>https://forms-flow-idm-d7202f-test.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for formsflow-demo-4086

terraform-v2/keycloak-dev/standard-clients/sbc-demo-formsflow-web-4087.tf
```<ul>✔️Valid Redirect Urls<li>https://forms-flow-web-d7202f-test.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
=> request: add client files for sbc-demo-formsflow-web-4087

terraform-v2/keycloak-dev/standard-clients/fsa-cognito-idir-dev-4088.tf, terraform-v2/keycloak-prod/standard-clients/fsa-cognito-idir-dev-4088.tf, terraform-v2/keycloak-test/standard-clients/fsa-cognito-idir-dev-4088.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
=> request: add client files for fsa-cognito-idir-dev-4088

terraform-v2/keycloak-dev/standard-clients/fsa-cognito-idir-prod-4089.tf, terraform-v2/keycloak-test/standard-clients/fsa-cognito-idir-prod-4089.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
=> request: add client files for fsa-cognito-idir-prod-4089

terraform-v2/keycloak-dev/standard-clients/fsa-cognito-b-ce-id-business-dev-4090.tf, terraform-v2/keycloak-test/standard-clients/fsa-cognito-b-ce-id-business-dev-4090.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
=> request: add client files for fsa-cognito-b-ce-id-business-dev-4090

terraform-v2/keycloak-dev/standard-clients/fsa-cognito-b-ce-id-business-prod-4091.tf, terraform-v2/keycloak-test/standard-clients/fsa-cognito-b-ce-id-business-prod-4091.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
=> request: add client files for fsa-cognito-b-ce-id-business-prod-4091

terraform-v2/keycloak-dev/standard-clients/documize-4092.tf, terraform-v2/keycloak-prod/standard-clients/documize-4092.tf, terraform-v2/keycloak-test/standard-clients/documize-4092.tf
```<ul>✔️Valid Redirect Urls<li>https://sso.apps-isd.sd.gov.bc.ca/auth/realms/documize-dev/broker/gold/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://sso.apps-isd.sd.gov.bc.ca/auth/realms/documize-test/broker/gold/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://sso.apps-isd.sd.gov.bc.ca/auth/realms/documize/broker/gold/endpoint</li></ul>```
</details>
=> request: add client files for documize-4092

terraform/keycloak-dev/realms/onestopauth/client-isd-amp-mining-scan-2509.tf
```<ul>✔️Valid Redirect Urls<li>https://sso.apps-isd.sd.gov.bc.ca/auth/realms/mining/broker/keycloak-oidc/endpoint</li></ul>```
</details>
=> request: delete client files for isd-amp-mining-scan-2509

terraform-v2/keycloak-dev/standard-clients/cdogs-showcase-4094.tf, terraform-v2/keycloak-prod/standard-clients/cdogs-showcase-4094.tf, terraform-v2/keycloak-test/standard-clients/cdogs-showcase-4094.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>https://dgrsc-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dgrsc-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dgrsc.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for cdogs-showcase-4094

terraform-v2/keycloak-dev/standard-clients/coms-showcase-4096.tf, terraform-v2/keycloak-prod/standard-clients/coms-showcase-4096.tf, terraform-v2/keycloak-test/standard-clients/coms-showcase-4096.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for coms-showcase-4096

terraform-v2/keycloak-dev/standard-clients/cdogs-showcase-frontend-4097.tf, terraform-v2/keycloak-prod/standard-clients/cdogs-showcase-frontend-4097.tf, terraform-v2/keycloak-test/standard-clients/cdogs-showcase-frontend-4097.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>https://dgrsc-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dgrsc-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dgrsc.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for cdogs-showcase-frontend-4097

terraform-v2/keycloak-dev/standard-clients/sabc-applications-vss-4098.tf
```<ul>✔️Valid Redirect Urls<li>https://tbtb-vss-06cb9b-dev.apps.silver.devops.gov.bc.ca/sso-login</li></ul>```
</details>
=> request: add client files for sabc-applications-vss-4098

terraform-v2/keycloak-dev/standard-clients/sabc-applications-vss-4099.tf
```<ul>✔️Valid Redirect Urls<li>https://tbtb-vss-06cb9b-dev.apps.silver.devops.gov.bc.ca/sso-login</li></ul>```
</details>
=> request: add client files for sabc-applications-vss-4099

terraform-v2/keycloak-dev/standard-clients/sabc-applications-vss-4100.tf
```<ul>✔️Valid Redirect Urls<li>https://tbtb-vss-06cb9b-dev.apps.silver.devops.gov.bc.ca/sso-login</li></ul>```
</details>
=> request: add client files for sabc-applications-vss-4100

terraform-v2/keycloak-dev/standard-clients/sabc-applications-vss-4101.tf
```<ul>✔️Valid Redirect Urls<li>https://tbtb-vss-06cb9b-dev.apps.silver.devops.gov.bc.ca/sso-login</li></ul>```
</details>
=> request: add client files for sabc-applications-vss-4101

terraform-v2/keycloak-dev/standard-clients/cdogs-showcase-4103.tf, terraform-v2/keycloak-prod/standard-clients/cdogs-showcase-4103.tf, terraform-v2/keycloak-test/standard-clients/cdogs-showcase-4103.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for cdogs-showcase-4103

terraform-v2/keycloak-dev/standard-clients/ches-showcase-4104.tf, terraform-v2/keycloak-prod/standard-clients/ches-showcase-4104.tf, terraform-v2/keycloak-test/standard-clients/ches-showcase-4104.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for ches-showcase-4104

terraform-v2/keycloak-dev/standard-clients/ches-showcase-frontend-4105.tf, terraform-v2/keycloak-prod/standard-clients/ches-showcase-frontend-4105.tf, terraform-v2/keycloak-test/standard-clients/ches-showcase-frontend-4105.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost/*</li>,<li>https://chess-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://chess-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://chess.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for ches-showcase-frontend-4105

terraform-v2/keycloak-dev/standard-clients/tians-testing-wildcard-4102.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-wildcard-4102.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-wildcard-4102.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-wildcard-4102

terraform-v2/keycloak-dev/standard-clients/saml-integration-4093.tf, terraform-v2/keycloak-prod/standard-clients/saml-integration-4093.tf, terraform-v2/keycloak-test/standard-clients/saml-integration-4093.tf
```<ul>✔️Valid Redirect Urls<li>*</li>,<li>https://example.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for saml-integration-4093

terraform-v2/keycloak-dev/standard-clients/resume-bundler-4106.tf, terraform-v2/keycloak-prod/standard-clients/resume-bundler-4106.tf, terraform-v2/keycloak-test/standard-clients/resume-bundler-4106.tf
```<ul>✔️Valid Redirect Urls<li>https://resume-bundler-dev.es.workbc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://resume-bundler-test.es.workbc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://resume-bundler.es.workbc.ca/*</li></ul>```
</details>
=> request: add client files for resume-bundler-4106

terraform-v2/keycloak-dev/standard-clients/fsa-cognito-idir-sm-dev-4107.tf, terraform-v2/keycloak-prod/standard-clients/fsa-cognito-idir-sm-dev-4107.tf, terraform-v2/keycloak-test/standard-clients/fsa-cognito-idir-sm-dev-4107.tf
```<ul>✔️Valid Redirect Urls<li>http://oidcdebugger-3d5c3f-dev.apps.silver.devops.gov.bc.ca/</li>,<li>https://bcgov.github.io/keycloak-example-apps/</li>,<li>https://oidcdebuggersecure-3d5c3f-dev.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/</li></ul>```
</details>
=> request: add client files for fsa-cognito-idir-sm-dev-4107

terraform-v2/keycloak-dev/standard-clients/local-chefs-4108.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8081/*</li></ul>```
</details>
=> request: add client files for local-chefs-4108

terraform-v2/keycloak-dev/standard-clients/local-chefs-4109.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li>,<li>http://localhost:8081</li>,<li>http://localhost:8082</li></ul>```
</details>
=> request: add client files for local-chefs-4109

terraform-v2/keycloak-dev/standard-clients/sept-14-idir-first-then-b-ceid-4110.tf, terraform-v2/keycloak-prod/standard-clients/sept-14-idir-first-then-b-ceid-4110.tf, terraform-v2/keycloak-test/standard-clients/sept-14-idir-first-then-b-ceid-4110.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for sept-14-idir-first-then-b-ceid-4110

terraform-v2/keycloak-dev/standard-clients/ggircs-4112.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3004/*</li></ul>```
</details>
=> request: add client files for ggircs-4112

terraform-v2/keycloak-dev/standard-clients/sabc-applications-yeaf-4114.tf, terraform-v2/keycloak-prod/standard-clients/sabc-applications-yeaf-4114.tf
```<ul>✔️Valid Redirect Urls<li>http://10.0.0.51:8017/app-login</li>,<li>https://tbtb-yeaf-06cb9b-dev.apps.silver.devops.gov.bc.ca/app-login</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://10.0.0.51:8017/app-login</li>,<li>https://tbtb-yeaf-06cb9b-prod.apps.silver.devops.gov.bc.ca/app-login</li></ul>```
</details>
=> request: add client files for sabc-applications-yeaf-4114

terraform/keycloak-dev/realms/onestopauth-basic/client-bceidplay-3701.tf, terraform/keycloak-test/realms/onestopauth-basic/client-bceidplay-3701.tf
```<ul>✔️Valid Redirect Urls<li>https://bceid-dev.solnspace.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bceid-test.solnspace.com</li></ul>```
</details>
=> request: delete client files for bceidplay-3701

terraform-v2/keycloak-dev/standard-clients/ccof-4115.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost*</li></ul>```
</details>
=> request: add client files for ccof-4115

terraform-v2/keycloak-dev/standard-clients/local-development-4117.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li>,<li>http://localhost:8081</li>,<li>http://localhost:8082</li></ul>```
</details>
=> request: add client files for local-development-4117

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1094-4118.tf
=> request: add client files for service-account-team-1094-4118

terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-4119.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-git-hub-4119.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-4119.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-git-hub-4119

terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-4120.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-b-ce-id-4120.tf
```<ul>✔️Valid Redirect Urls<li>*</li>,<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-4120

terraform-v2/keycloak-dev/standard-clients/gwells-4121.tf, terraform-v2/keycloak-test/standard-clients/gwells-4121.tf
```<ul>✔️Valid Redirect Urls<li>https://gwells-dev-pr-1777.apps.silver.devops.gov.bc.ca/gwells</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://gwells-staging.apps.silver.devops.gov.bc.ca/gwells</li></ul>```
</details>
=> request: add client files for gwells-4121

terraform-v2/keycloak-dev/standard-clients/elmsd-front-end-dev-4124.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
</details>
=> request: add client files for elmsd-front-end-dev-4124

terraform-v2/keycloak-dev/standard-clients/elmsd-back-end-dev-4125.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for elmsd-back-end-dev-4125

terraform-v2/keycloak-dev/standard-clients/jsb-csrs-4126.tf, terraform-v2/keycloak-prod/standard-clients/jsb-csrs-4126.tf, terraform-v2/keycloak-test/standard-clients/jsb-csrs-4126.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>https://dev.childsupportrecalc.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>https://test.childsupportrecalc.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://childsupportrecalc.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for jsb-csrs-4126

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-795-4127.tf
=> request: add client files for service-account-team-795-4127

terraform-v2/keycloak-dev/standard-clients/css-app-in-gold-4128.tf, terraform-v2/keycloak-prod/standard-clients/css-app-in-gold-4128.tf, terraform-v2/keycloak-test/standard-clients/css-app-in-gold-4128.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost</li></ul>```
</details>
=> request: add client files for css-app-in-gold-4128

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-894-4129.tf
=> request: add client files for service-account-team-894-4129

terraform-v2/keycloak-dev/standard-clients/coms-client-4130.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost/*</li>,<li>http://localhost:8080/*</li>,<li>http://localhost:8081/*</li></ul>```
</details>
=> request: add client files for coms-client-4130

terraform-v2/keycloak-dev/standard-clients/ticdi-4133.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for ticdi-4133

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-133-4134.tf
=> request: add client files for service-account-team-133-4134

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1095-4136.tf
=> request: add client files for service-account-team-1095-4136

terraform-v2/keycloak-dev/standard-clients/aps-portal-4138.tf, terraform-v2/keycloak-test/standard-clients/aps-portal-4138.tf
```<ul>✔️Valid Redirect Urls<li>https://api-gov-bc-ca.dev.api.gov.bc.ca/oauth2/callback</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://api-gov-bc-ca.test.api.gov.bc.ca/oauth2/callback</li></ul>```
</details>
=> request: add client files for aps-portal-4138

terraform-v2/keycloak-dev/standard-clients/nr-fsa-service-api-4139.tf, terraform-v2/keycloak-test/standard-clients/nr-fsa-service-api-4139.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for nr-fsa-service-api-4139

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-763-4140.tf
=> request: add client files for service-account-team-763-4140

terraform-v2/keycloak-dev/standard-clients/myccs-idir-4141.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost*</li></ul>```
</details>
=> request: add client files for myccs-idir-4141

terraform-v2/keycloak-dev/standard-clients/myccs-idir-4142.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost*</li></ul>```
</details>
=> request: add client files for myccs-idir-4142

terraform-v2/keycloak-dev/standard-clients/hets-4143.tf, terraform-v2/keycloak-prod/standard-clients/hets-4143.tf, terraform-v2/keycloak-test/standard-clients/hets-4143.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li>,<li>http://localhost:3000/*</li>,<li>https://dev-hets.th.gov.bc.ca/</li>,<li>https://dev-hets.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-hets.th.gov.bc.ca/</li>,<li>https://tst-hets.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://hets.th.gov.bc.ca/</li>,<li>https://hets.th.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for hets-4143

terraform-v2/keycloak-dev/standard-clients/abc-4145.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for abc-4145

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1100-4146.tf
=> request: add client files for service-account-team-1100-4146

terraform-v2/keycloak-dev/standard-clients/fom-4147.tf, terraform-v2/keycloak-prod/standard-clients/fom-4147.tf
```<ul>✔️Valid Redirect Urls<li>https://fom-dev.nrs.gov.bc.ca/*</li>,<li>https://fom-nrs-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://fom-nrs-prd.apps.silver.devops.gov.bc.ca/*</li>,<li>https://fom-prod.nrs.gov.bc.ca/*</li>,<li>https://fom.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for fom-4147

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1063-4160.tf
=> request: add client files for service-account-team-1063-4160

terraform-v2/keycloak-dev/standard-clients/knox-4161.tf, terraform-v2/keycloak-prod/standard-clients/knox-4161.tf, terraform-v2/keycloak-test/standard-clients/knox-4161.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8250/oidc/callback</li>,<li>https://vault-iit-dev.apps.silver.devops.gov.bc.ca/ui/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8250/oidc/callback</li>,<li>https://vault-iit-test.apps.silver.devops.gov.bc.ca/ui/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8250/oidc/callback</li>,<li>http://localhost:9595/callback/*</li>,<li>https://knox.io.nrs.gov.bc.ca/ui/*</li>,<li>https://vault-iit.apps.silver.devops.gov.bc.ca/ui/*</li></ul>```
</details>
=> request: add client files for knox-4161

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-827-4163.tf
=> request: add client files for service-account-team-827-4163

README.md, terraform-v2-custom/keycloak-dev/custom-realms/jon-new-realm.tf
Create a custom realm and add a line of documentation
=> chore: customRealm

terraform-v2/keycloak-dev/standard-clients/create-custom-realm-4167.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for create-custom-realm-4167

terraform-v2-custom/keycloak-dev/custom-realms/kuro-new-realm.tf
=> chore: create custom realm

terraform-v2/keycloak-dev/standard-clients/tians-testing-4171.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-4171.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-4171.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-4171

terraform-v2/keycloak-dev/standard-clients/digital-feedback-4170.tf, terraform-v2/keycloak-prod/standard-clients/digital-feedback-4170.tf, terraform-v2/keycloak-test/standard-clients/digital-feedback-4170.tf
```<ul>✔️Valid Redirect Urls<li>https://digital-feedback-dev.apps.silver.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://digital-feedback-test.apps.silver.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://digital-feedback.apps.silver.gov.bc.ca</li></ul>```
</details>
=> request: add client files for digital-feedback-4170

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1124-4172.tf
=> request: add client files for service-account-team-1124-4172

terraform-v2/keycloak-dev/standard-clients/rrs-4173.tf, terraform-v2/keycloak-prod/standard-clients/rrs-4173.tf, terraform-v2/keycloak-test/standard-clients/rrs-4173.tf
```<ul>✔️Valid Redirect Urls<li>https://dlvrapps.nrs.gov.bc.ca/int/rrs-web/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://testapps.nrs.gov.bc.ca/int/rrs-web/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://apps.nrs.gov.bc.ca/int/rrs-web/</li></ul>```
</details>
=> request: add client files for rrs-4173

terraform-v2/keycloak-dev/standard-clients/oct-10-test-idir-dev-4132.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/sso-r</li></ul>```
</details>
=> request: add client files for oct-10-test-idir-dev-4132

terraform-v2/keycloak-dev/standard-clients/acrfd-4192.tf
```<ul>✔️Valid Redirect Urls<li>https://acrfd-admin-86cabb-dev.apps.silver.devops.gov.bc.ca/admin/</li></ul>```
</details>
=> request: add client files for acrfd-4192

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-299-4195.tf
=> request: add client files for service-account-team-299-4195

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1159-4197.tf
=> request: add client files for service-account-team-1159-4197

terraform-v2/keycloak-dev/standard-clients/bio-hub-4199.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for bio-hub-4199

terraform-v2/keycloak-dev/standard-clients/ed-9154-dev-4226.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost</li></ul>```
</details>
=> request: add client files for ed-9154-dev-4226

terraform-v2/keycloak-dev/standard-clients/sims-4228.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for sims-4228

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1190-4229.tf
=> request: add client files for service-account-team-1190-4229

terraform-v2/keycloak-dev/standard-clients/bio-hub-browser-4230.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for bio-hub-browser-4230

terraform-v2/keycloak-dev/standard-clients/nr-broker-4231.tf, terraform-v2/keycloak-prod/standard-clients/nr-broker-4231.tf, terraform-v2/keycloak-test/standard-clients/nr-broker-4231.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for nr-broker-4231

terraform-v2/keycloak-dev/standard-clients/health-gateway-4260.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/health-gateway-gold/broker/idir/endpoint</li></ul>```
</details>
=> request: add client files for health-gateway-4260

terraform-v2/keycloak-dev/standard-clients/platform-services-4261.tf, terraform-v2/keycloak-prod/standard-clients/platform-services-4261.tf, terraform-v2/keycloak-test/standard-clients/platform-services-4261.tf
```<ul>✔️Valid Redirect Urls<li>https://argocd.apps.klab.devops.gov.bc.ca/</li>,<li>https://registry.developer.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://argocd.apps.klab.devops.gov.bc.ca/</li>,<li>https://registry.developer.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://argocd.apps.silver.devops.gov.bc.ca/</li>,<li>https://registry.developer.gov.bc.ca</li></ul>```
</details>
=> request: add client files for platform-services-4261

terraform-v2/keycloak-dev/standard-clients/health-gateway-4263.tf, terraform-v2/keycloak-prod/standard-clients/health-gateway-4263.tf, terraform-v2/keycloak-test/standard-clients/health-gateway-4263.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/health-gateway-gold/broker/azureidir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/health-gateway-gold/broker/azureidir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/health-gateway-gold/broker/azureidir/endpoint</li></ul>```
</details>
=> request: add client files for health-gateway-4263

terraform-v2/keycloak-dev/standard-clients/nr-fsa-web-app-4266.tf, terraform-v2/keycloak-test/standard-clients/nr-fsa-web-app-4266.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://nrfesampleapp-test-app.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for nr-fsa-web-app-4266

terraform-v2/keycloak-dev/standard-clients/work-bc-es-4268.tf, terraform-v2/keycloak-prod/standard-clients/work-bc-es-4268.tf, terraform-v2/keycloak-test/standard-clients/work-bc-es-4268.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/workbces/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/workbces/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/workbces/*</li></ul>```
</details>
=> request: add client files for work-bc-es-4268

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1090-4269.tf
=> request: add client files for service-account-team-1090-4269

terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-4271.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-4271.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-git-hub-4271

terraform-v2/keycloak-dev/standard-clients/tians-testing-saml-demo-4272.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-saml-demo-4272.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-saml-demo-4272

terraform-v2/keycloak-dev/standard-clients/registries-4291.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcregistry/*</li></ul>```
</details>
=> request: add client files for registries-4291

terraform-v2/keycloak-dev/standard-clients/pims-local-test-4292.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
</details>
=> request: add client files for pims-local-test-4292

terraform-v2/keycloak-dev/standard-clients/devit-4295.tf
```<ul>✔️Valid Redirect Urls<li>https://devit.gaming.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for devit-4295

terraform-v2/keycloak-dev/standard-clients/seed-planning-test-4296.tf, terraform-v2/keycloak-test/standard-clients/seed-planning-test-4296.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for seed-planning-test-4296

terraform-v2/keycloak-dev/standard-clients/serve-legal-documents-4299.tf, terraform-v2/keycloak-prod/standard-clients/serve-legal-documents-4299.tf, terraform-v2/keycloak-test/standard-clients/serve-legal-documents-4299.tf
```<ul>✔️Valid Redirect Urls<li>https://keycloak-a60371-dev.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://keycloak-a60371-test.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://keycloak-a60371-prod.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/broker/keycloak-oidc/endpoint</li></ul>```
</details>
=> request: add client files for serve-legal-documents-4299

terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-public-4301.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-public-4301.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for tians-testing-git-hub-public-4301

terraform-v2/keycloak-dev/standard-clients/coco-chefs-bceid-4300.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>http://localhost:8081/*</li>,<li>http://localhost:8082/*</li></ul>```
</details>
=> request: add client files for coco-chefs-bceid-4300

terraform-v2/keycloak-dev/standard-clients/tians-testing-tab-4305.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-tab-4305

terraform-v2/keycloak-dev/standard-clients/tfrs-on-gold-4308.tf, terraform-v2/keycloak-prod/standard-clients/tfrs-on-gold-4308.tf, terraform-v2/keycloak-test/standard-clients/tfrs-on-gold-4308.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://tfrs-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tfrs-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://lowcarbonfuels.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for tfrs-on-gold-4308

terraform-v2/keycloak-dev/standard-clients/auth-type-test-4309.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for auth-type-test-4309

terraform-v2/keycloak-dev/standard-clients/documize-4310.tf, terraform-v2/keycloak-prod/standard-clients/documize-4310.tf, terraform-v2/keycloak-test/standard-clients/documize-4310.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-documize.data.gov.bc.ca/*</li>,<li>https://documize.data.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dev-documize.data.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dev-documize.data.gov.bc.ca/</li>,<li>https://documize.data.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for documize-4310

terraform-v2/keycloak-dev/standard-clients/cif-4311.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3004/*</li></ul>```
</details>
=> request: add client files for cif-4311

terraform/keycloak-dev/realms/onestopauth/client-work-bc-career-compass-3136.tf, terraform/keycloak-prod/realms/onestopauth/client-work-bc-career-compass-3136.tf, terraform/keycloak-test/realms/onestopauth/client-work-bc-career-compass-3136.tf
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes-dev.workbc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes-test.workbc.ca/openid-connect/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://careerdiscoveryquizzes.workbc.ca/openid-connect/keycloak</li></ul>```
</details>
=> request: delete client files for work-bc-career-compass-3136

terraform-v2/keycloak-dev/standard-clients/cisoss-4313.tf
```<ul>✔️Valid Redirect Urls<li>https://cis.data.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for cisoss-4313

terraform-v2/keycloak-dev/standard-clients/gogs-4314.tf
```<ul>✔️Valid Redirect Urls<li>https://gogs.data.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for gogs-4314

terraform-v2/keycloak-dev/standard-clients/tti-ams-gold-4259.tf, terraform-v2/keycloak-prod/standard-clients/tti-ams-gold-4259.tf, terraform-v2/keycloak-test/standard-clients/tti-ams-gold-4259.tf
```<ul>✔️Valid Redirect Urls<li>https://bchrt--qa.sandbox.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://bcmoag--qa.sandbox.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://bcrb--qa.sandbox.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://cabro--qa.sandbox.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://civilresolutionbc--amsqa.sandbox.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://employmentstandardsboard--qa04.sandbox.my.salesforce.com/services/authcallback/PathfinderIdir</li>,<li>https://employmentstandardstribunal--qa.sandbox.lightning.force.com/services/authcallback/PathfinderIdir</li>,<li>https://lrb--qa.sandbox.my.sa …
```
=> request: add client files for tti-ams-gold-4259

terraform-v2/keycloak-dev/standard-clients/testing-marco-4315.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost*</li></ul>```
</details>
=> request: add client files for testing-marco-4315

terraform-v2/keycloak-dev/standard-clients/platform-services-azure-4316.tf, terraform-v2/keycloak-prod/standard-clients/platform-services-azure-4316.tf, terraform-v2/keycloak-test/standard-clients/platform-services-azure-4316.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/platform-services/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/platform-services/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/platform-services/*</li></ul>```
</details>
=> request: add client files for platform-services-azure-4316

terraform-v2/keycloak-dev/standard-clients/my-css-ccof-idir-4324.tf, terraform-v2/keycloak-test/standard-clients/my-css-ccof-idir-4324.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost*</li>,<li>https://dev.mychildcareservices.gov.bc.ca/api/auth/callback</li>,<li>https://dev.mychildcareservices.gov.bc.ca/api/auth/callback_bceid</li>,<li>https://dev.mychildcareservices.gov.bc.ca/api/auth/callback_idir</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.mychildcareservices.gov.bc.ca/api/auth/callback</li>,<li>https://test.mychildcareservices.gov.bc.ca/api/auth/callback_bceid</li>,<li>https://test.mychildcareservices.gov.bc.ca/api/auth/callback_idir</li></ul>```
</details>
=> request: add client files for my-css-ccof-idir-4324

terraform-v2/keycloak-dev/standard-clients/cep-project-holder-4325.tf, terraform-v2/keycloak-test/standard-clients/cep-project-holder-4325.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for cep-project-holder-4325

terraform-v2/keycloak-dev/standard-clients/bc-parks-4326.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcparks-service-transformation/*</li></ul>```
</details>
=> request: add client files for bc-parks-4326

terraform-v2/keycloak-dev/standard-clients/bc-parks-4327.tf, terraform-v2/keycloak-test/standard-clients/bc-parks-4327.tf
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/bcparks-service-transformation/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/bcparks-service-transformation/*</li></ul>```
</details>
=> request: add client files for bc-parks-4327

terraform-v2/keycloak-dev/standard-clients/bc-parks-4328.tf, terraform-v2/keycloak-prod/standard-clients/bc-parks-4328.tf, terraform-v2/keycloak-test/standard-clients/bc-parks-4328.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcparks-service-transformation/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/bcparks-service-transformation/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/bcparks-service-transformation/*</li></ul>```
</details>
=> request: add client files for bc-parks-4328

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-430-4329.tf
=> request: add client files for service-account-team-430-4329

terraform-v2/keycloak-dev/standard-clients/comsvcauth-4330.tf, terraform-v2/keycloak-prod/standard-clients/comsvcauth-4330.tf, terraform-v2/keycloak-test/standard-clients/comsvcauth-4330.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/comsvcauth/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/comsvcauth/*</li></ul>```
</details>
=> request: add client files for comsvcauth-4330

terraform-v2/keycloak-dev/standard-clients/idir-kc-4332.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.oidc.gov.bc.ca/auth/realms/fcf0kpqr/*</li></ul>```
</details>
=> request: add client files for idir-kc-4332

terraform-v2/keycloak-dev/standard-clients/energy-and-mines-digital-trust-4333.tf, terraform-v2/keycloak-prod/standard-clients/energy-and-mines-digital-trust-4333.tf, terraform-v2/keycloak-test/standard-clients/energy-and-mines-digital-trust-4333.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/digitaltrust-nrm/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/digitaltrust-nrm/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/digitaltrust-nrm/*</li></ul>```
</details>
=> request: add client files for energy-and-mines-digital-trust-4333

terraform-v2/keycloak-dev/standard-clients/epd-digital-services-4304.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for epd-digital-services-4304

terraform-v2/keycloak-dev/standard-clients/digital-marketplace-4144.tf, terraform-v2/keycloak-prod/standard-clients/digital-marketplace-4144.tf, terraform-v2/keycloak-test/standard-clients/digital-marketplace-4144.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://app-digmkt-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://app-digmkt-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://marketplace.digital.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for digital-marketplace-4144

terraform-v2/keycloak-dev/standard-clients/mines-digital-services-mds-4334.tf, terraform-v2/keycloak-prod/standard-clients/mines-digital-services-mds-4334.tf, terraform-v2/keycloak-test/standard-clients/mines-digital-services-mds-4334.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for mines-digital-services-mds-4334

terraform-v2/keycloak-dev/standard-clients/redip-jeri-4336.tf, terraform-v2/keycloak-prod/standard-clients/redip-jeri-4336.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000/keycloak</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000/keycloak</li></ul>```
</details>
=> request: add client files for redip-jeri-4336

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1263-4337.tf
=> request: add client files for service-account-team-1263-4337

terraform-v2/keycloak-dev/standard-clients/time-machine-4338.tf, terraform-v2/keycloak-prod/standard-clients/time-machine-4338.tf, terraform-v2/keycloak-test/standard-clients/time-machine-4338.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>https://web-ed57f0-dev.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>https://web-ed57f0-test.apps.silver.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://web-ed57f0-prod.apps.silver.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for time-machine-4338

terraform-v2/keycloak-dev/standard-clients/front-counter-bc-fider-4293.tf, terraform-v2/keycloak-prod/standard-clients/front-counter-bc-fider-4293.tf, terraform-v2/keycloak-test/standard-clients/front-counter-bc-fider-4293.tf
```<ul>✔️Valid Redirect Urls<li>https://fcbcdevfider.apps.gold.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://fcbctestfider.apps.gold.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://fcbcfider.apps.gold.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for front-counter-bc-fider-4293

terraform-v2/keycloak-dev/standard-clients/call-web-api-4339.tf, terraform-v2/keycloak-prod/standard-clients/call-web-api-4339.tf, terraform-v2/keycloak-test/standard-clients/call-web-api-4339.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for call-web-api-4339

terraform-v2/keycloak-dev/standard-clients/exit-survey-admin-4340.tf, terraform-v2/keycloak-prod/standard-clients/exit-survey-admin-4340.tf, terraform-v2/keycloak-test/standard-clients/exit-survey-admin-4340.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for exit-survey-admin-4340

terraform-v2/keycloak-dev/standard-clients/new-job-survey-admin-4341.tf, terraform-v2/keycloak-prod/standard-clients/new-job-survey-admin-4341.tf, terraform-v2/keycloak-test/standard-clients/new-job-survey-admin-4341.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for new-job-survey-admin-4341

terraform-v2/keycloak-dev/standard-clients/my-wes-4342.tf, terraform-v2/keycloak-prod/standard-clients/my-wes-4342.tf, terraform-v2/keycloak-test/standard-clients/my-wes-4342.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for my-wes-4342

terraform-v2/keycloak-dev/standard-clients/epd-digital-services-4343.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for epd-digital-services-4343

terraform-v2/keycloak-dev/standard-clients/pims-app-4344.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for pims-app-4344

terraform-v2/keycloak-dev/standard-clients/github-kc-4345.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcregistry/*</li></ul>```
</details>
=> request: add client files for github-kc-4345

terraform-v2/keycloak-dev/standard-clients/bceid-kc-4346.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcregistry/*</li></ul>```
</details>
=> request: add client files for bceid-kc-4346

terraform-v2/keycloak-dev/standard-clients/github-registries-idp-4348.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcregistry/*</li></ul>```
</details>
=> request: add client files for github-registries-idp-4348

terraform-v2/keycloak-dev/standard-clients/bceid-registries-idp-4349.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/bcregistry/*</li></ul>```
</details>
=> request: add client files for bceid-registries-idp-4349

terraform-v2/keycloak-dev/standard-clients/my-wes-4350.tf, terraform-v2/keycloak-prod/standard-clients/my-wes-4350.tf, terraform-v2/keycloak-test/standard-clients/my-wes-4350.tf
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/wes/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/test/wes/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/wes</li></ul>```
</details>
=> request: add client files for my-wes-4350

terraform-v2/keycloak-dev/standard-clients/new-job-survey-admin-4352.tf, terraform-v2/keycloak-prod/standard-clients/new-job-survey-admin-4352.tf, terraform-v2/keycloak-test/standard-clients/new-job-survey-admin-4352.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li>,<li>https://localhost:5051/*</li></ul>```
</details>
=> request: add client files for new-job-survey-admin-4352

terraform-v2/keycloak-dev/standard-clients/exit-survey-admin-4353.tf, terraform-v2/keycloak-prod/standard-clients/exit-survey-admin-4353.tf, terraform-v2/keycloak-test/standard-clients/exit-survey-admin-4353.tf
```<ul>✔️Valid Redirect Urls<li>*</li>,<li>http://local-frontend-c746eb-tools.apps.silver.devops.gov.bc.ca</li>,<li>http://localhost:3000/*</li>,<li>http://localhost:5051/*</li>,<li>https://localhost:5051/*</li>,<li>https://securesurveys.gov.bc.ca/dev/Exit/admin/*</li>,<li>https://securesurveys.gov.bc.ca/dev/exit/admin/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/test/Exit/admin/*</li>,<li>https://securesurveys.gov.bc.ca/test/exit/admin/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/Exit/*</li>,<li>https://securesurveys.gov.bc.ca/exit/*</li></ul>``` …
=> request: add client files for exit-survey-admin-4353

terraform-v2/keycloak-dev/standard-clients/servicebc-4354.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/servicebc/*</li></ul>```
</details>
=> request: add client files for servicebc-4354

terraform-v2/keycloak-dev/standard-clients/roadsafety-digital-forms-gold-4355.tf, terraform-v2/keycloak-prod/standard-clients/roadsafety-digital-forms-gold-4355.tf, terraform-v2/keycloak-test/standard-clients/roadsafety-digital-forms-gold-4355.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080/*</li>,<li>http://localhost:8080/roadside-forms/*</li>,<li>https://dev.jag.gov.bc.ca/roadside-forms/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.jag.gov.bc.ca/roadside-forms/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://jag.gov.bc.ca/roadside-forms/*</li></ul>```
</details>
=> request: add client files for roadsafety-digital-forms-gold-4355

terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-b-ce-id-4356.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-b-ce-id-4356.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-git-hub-b-ce-id-4356

terraform-v2/keycloak-dev/standard-clients/idir-registries-idp-test-4357.tf
```<ul>✔️Valid Redirect Urls<li>https://bc-registry-namerequest-sre-3b2420-tools.apps.silver.devops.gov.bc.ca/namerequest/*</li></ul>```
</details>
=> request: add client files for idir-registries-idp-test-4357

terraform-v2/keycloak-dev/standard-clients/exit-survey-admin-4359.tf, terraform-v2/keycloak-prod/standard-clients/exit-survey-admin-4359.tf, terraform-v2/keycloak-test/standard-clients/exit-survey-admin-4359.tf
```<ul>✔️Valid Redirect Urls<li>*</li>,<li>http://local-frontend-c746eb-tools.apps.silver.devops.gov.bc.ca</li>,<li>http://localhost:3000/*</li>,<li>http://localhost:5051/*</li>,<li>https://localhost:5051/*</li>,<li>https://securesurveys.gov.bc.ca/dev/Exit/admin/*</li>,<li>https://securesurveys.gov.bc.ca/dev/exit/admin/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/test/Exit/admin/*</li>,<li>https://securesurveys.gov.bc.ca/test/exit/admin/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/Exit/*</li>,<li>https://securesurveys.gov.bc.ca/exit/*</li></ul>``` …
=> request: add client files for exit-survey-admin-4359

terraform-v2/keycloak-dev/standard-clients/my-wes-4361.tf, terraform-v2/keycloak-prod/standard-clients/my-wes-4361.tf, terraform-v2/keycloak-test/standard-clients/my-wes-4361.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:4200/*</li>,<li>http://localhost:4201/*</li>,<li>http://localhost:4202/*</li>,<li>https://localhost:44311/*</li>,<li>https://securesurveys.gov.bc.ca/*</li>,<li>https://securesurveys.gov.bc.ca/wes/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/test/wes/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/wes</li></ul>```
</details>
=> request: add client files for my-wes-4361

terraform-v2/keycloak-dev/standard-clients/kuro-test-example-app-4362.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for kuro-test-example-app-4362

terraform-v2/keycloak-dev/standard-clients/pims-api-sa-4366.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for pims-api-sa-4366

terraform-v2/keycloak-dev/standard-clients/isd-icm-wm-kkcfs-4367.tf
```<ul>✔️Valid Redirect Urls<li>https://kkcfs-wm.api.gov.bc.ca/callback</li></ul>```
</details>
=> request: add client files for isd-icm-wm-kkcfs-4367

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1256-4368.tf
=> request: add client files for service-account-team-1256-4368

terraform-v2/keycloak-dev/standard-clients/test-mds-script-nk-4369.tf, terraform-v2/keycloak-test/standard-clients/test-mds-script-nk-4369.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
=> request: add client files for test-mds-script-nk-4369

terraform-v2/keycloak-dev/standard-clients/icm-diona-4370.tf
```<ul>✔️Valid Redirect Urls<li>https://icmwmdevds.icm.gov.bc.ca/api/v1/portal/genAPITest</li></ul>```
</details>
=> request: add client files for icm-diona-4370

terraform-v2/keycloak-dev/standard-clients/community-corrections-case-management-3997.tf, terraform-v2/keycloak-prod/standard-clients/community-corrections-case-management-3997.tf, terraform-v2/keycloak-test/standard-clients/community-corrections-case-management-3997.tf
```<ul>✔️Valid Redirect Urls<li>https://cccm-keycloak-abb712-dev.apps.gold.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cccm-keycloak-abb712-test.apps.gold.devops.gov.bc.ca/realms/cccm/broker/idir/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cccm-keycloak-abb712-prod.apps.gold.devops.gov.bc.ca/realms/cccm/broker/idir/endpoint</li></ul>```
</details>
=> request: add client files for community-corrections-case-management-3997

terraform-v2/keycloak-dev/standard-clients/junmin-new-project-4371.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
=> request: add client files for junmin-new-project-4371

terraform-v2/keycloak-dev/standard-clients/social-4372.tf, terraform-v2/keycloak-prod/standard-clients/social-4372.tf, terraform-v2/keycloak-test/standard-clients/social-4372.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/social/broker/gsa/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/social/broker/gsa/endpoint</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://loginproxy.gov.bc.ca/auth/realms/social/broker/gsa/endpoint</li></ul>```
</details>
=> request: add client files for social-4372

terraform-v2/keycloak-dev/standard-clients/exit-survey-admin-4373.tf, terraform-v2/keycloak-prod/standard-clients/exit-survey-admin-4373.tf, terraform-v2/keycloak-test/standard-clients/exit-survey-admin-4373.tf
```<ul>✔️Valid Redirect Urls<li>*</li>,<li>http://local-frontend-c746eb-tools.apps.silver.devops.gov.bc.ca</li>,<li>http://localhost:3000/*</li>,<li>http://localhost:5051/*</li>,<li>https://securesurveys.gov.bc.ca/dev/Exit/admin/*</li>,<li>https://securesurveys.gov.bc.ca/dev/exit/admin/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/test/Exit/admin/*</li>,<li>https://securesurveys.gov.bc.ca/test/exit/admin/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://securesurveys.gov.bc.ca/Exit/*</li>,<li>https://securesurveys.gov.bc.ca/exit/*</li></ul>```
</details>
=> request: add client files for exit-survey-admin-4373

terraform-v2/keycloak-dev/standard-clients/digital-talent-fider-ux-4374.tf, terraform-v2/keycloak-test/standard-clients/digital-talent-fider-ux-4374.tf
```<ul>✔️Valid Redirect Urls<li>https://dtalentfider.apps.silver.devops.gov.bc.ca/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dtalentfider.apps.silver.devops.gov.bc.ca/</li></ul>```
</details>
=> request: add client files for digital-talent-fider-ux-4374

terraform-v2/keycloak-dev/standard-clients/digital-talent-fider-ux-4375.tf, terraform-v2/keycloak-prod/standard-clients/digital-talent-fider-ux-4375.tf, terraform-v2/keycloak-test/standard-clients/digital-talent-fider-ux-4375.tf
```<ul>✔️Valid Redirect Urls<li>https://dtalentfider.apps.*.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dtalentfider.apps.*.devops.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://dtalentfider.apps.*.devops.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for digital-talent-fider-ux-4375

terraform-v2/keycloak-dev/standard-clients/hetsnew-4376.tf, terraform-v2/keycloak-prod/standard-clients/hetsnew-4376.tf, terraform-v2/keycloak-test/standard-clients/hetsnew-4376.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/</li>,<li>http://localhost:3000/*</li>,<li>https://dev-hets.th.gov.bc.ca/</li>,<li>https://dev-hets.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://tst-hets.th.gov.bc.ca/</li>,<li>https://tst-hets.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://hets.th.gov.bc.ca/</li>,<li>https://hets.th.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for hetsnew-4376

terraform-v2/keycloak-dev/standard-clients/test-4377.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
=> request: add client files for test-4377

terraform-v2-custom/keycloak-dev/custom-realms/testing-nk.tf
Creating this custom realm in dev to test the migration
=> chore: adding a custom realm to test migration

terraform-v2-custom/keycloak-dev/custom-realms/testing-nk.tf
=> chore: removing custom realm testing-nk

terraform-v2/keycloak-dev/standard-clients/migrate-cstm-rlm-users-nk-4378.tf, terraform-v2/keycloak-test/standard-clients/migrate-cstm-rlm-users-nk-4378.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
=> request: add client files for migrate-cstm-rlm-users-nk-4378

terraform-v2/keycloak-dev/standard-clients/property-services-project-app-4379.tf, terraform-v2/keycloak-prod/standard-clients/property-services-project-app-4379.tf, terraform-v2/keycloak-test/standard-clients/property-services-project-app-4379.tf
```<ul>✔️Valid Redirect Urls<li>https://dev-pims.th.gov.bc.ca/*</li>,<li>https://pims-app-3cd915-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://pims-app-test-3cd915-dev.apps.silver.devops.gov.bc.ca/*</li>,<li>https://tst-pims.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://pims-app-uat-3cd915-test.apps.silver.devops.gov.bc.ca/*</li>,<li>https://uat-pims.th.gov.bc.ca/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://pims-app-3cd915-prod.apps.silver.devops.gov.bc.ca/*</li>,<li>https://pims.th.gov.bc.ca/*</li></ul>```
</details>
=> request: add client files for property-services-project-app-4379

terraform-v2/keycloak-dev/standard-clients/property-services-project-api-4380.tf, terraform-v2/keycloak-prod/standard-clients/property-services-project-api-4380.tf, terraform-v2/keycloak-test/standard-clients/property-services-project-api-4380.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for property-services-project-api-4380

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1295-4381.tf
=> request: add client files for service-account-team-1295-4381
